### ISSUE TITLE
missing documentation: is this for a boiler and/or for thermostatic radiator valves?

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#104]
I cannot find any information about the hardware requirements of this integration. Is it used to control a central boiler, heating many rooms (which might contain temperature sensors) at once, or is it used to control thermostatic radiator valves (TRV) which control the amount of hot water flowing to a radiator?

Personally I'd be interested in moving my dozen Eve Thermo thread based TRVs to Home Assistant, which currently are all still part of my old Homekit setup, but I'm unsure if this integration would be able to control each of them by altering their target temperature based on presence, motion, schedule etc. and also control the valve opening percentages based on measured temperature (either from the integrated sensor of the valves or from a room temperature sensor), target temperature, outdoor temperature etc.

(As my Vaillant boiler is way oversized for the required heating, unfortunately the following happens frequently in autumn and spring: the boiler starts heating the circulating water and the pump, the radiators cannot convert all the heat quickly enough, so the hot water returns to the boiler within a minute, causing the boiler to stop heating, but as the temperature is still lower than required, it turns on the heating only a minute later. The way to minimise this issue is to set all valves to 100%, which is the opposite of the Eve Thermo do, as they try to keep the valves as closed as only possible, therefor making it even harder for the boiler to get rid of the excess generated heat.)

Thanks!

**Comment by jmcollin78** [comment]
If you already have some climate entities for your equipment, you can simply use the VTherm over climate. This is certainly the best way to add VTherm features to your existing configuration.

**Comment by maia** [comment]
@jmcollin78 Thanks, but I think I still don't understand if this is to control Thermostatic radiator valves (TRVs), especially for the Eve Thermo of which I own a dozen and which currently are controlled via Thread/Homekit.

**Comment by jmcollin78** [comment]
VTherm was done to control:
1. an electric heater by turning it on and off in cycle until a target temperature is reach,
2. a underlying existing climate entity already working in HA.

VTherm is NOT specific to a equipment brands or models.

More usage are possible but because I cannot tests it, I cannot says that it is fully usable.
just give it a try: it is very easy to install and to configure. In Vtherm over climate mode, you don't have to touch your existing configuration. So it is very easy to remove.

I cannot says more, sorry for that.

**Comment by maia** [comment]
@jmcollin78 Thanks. If VTherm controls binary devices, it's not suitable for TRVs which alter their valve opening percentage-wise.

**Comment by jmcollin78** [comment]
With the second mode (VTherm over climate), I'm pretty sure you can do what you want.
All you need is an existing climate entity which is controlling your TRVs and then you can create a VTherm over this climate to add features likes window detection, etc

**Comment by maia** [comment]
@jmcollin78 Can you point me to the documentation of the "second mode"? I cannot find anything in the repo named "VTherm over climate". My Eve Thermo TRV as Homekit device shows up in developer tools state inspector the following way:

```
hvac_modes:
  - 'off'
  - heat
min_temp: 10
max_temp: 30
current_temperature: 21.5
temperature: 16
hvac_action: idle
friendly_name: WC Thermo
supported_features: 1
```

Its controls are the target temperature and heating on/off, it provides a sensor of the current temperature and a battery level. It does not seem to provide direct control to valve opening percentage. 

Thanks!

**Comment by jmcollin78** [comment]
Hello, you have a very interesting discussion here on exactly the same cases: https://community.home-assistant.io/t/versatile-thermostat-a-full-feature-thermostat-energy-door-window-presence-motion-preset-management/546761/28?u=jmcollin

I will integrate this in the documentation next week.

**Comment by maia** [comment]
Please see #115 for my suggestion on how to solve the issue.
