### ISSUE TITLE
Off Cycle Duration

### ISSUE THREAD

**Issue by kadaan** [jmcollin78/versatile_thermostat#107]
**Is your feature request related to a problem? Please describe.**
I'm using Versatile Thermostat to control a Pellet Stove and to protect the igniter I would like to ensure that the stove can have only up to a configured maximum number of cycles per 24h period.

**Describe the solution you'd like**
If there was a boolean parameter that could invert the "Cycle Duration" parameter to "Off Cycle Duration" then I could ensure that the pellet stove ignites no more than X times per day.  Also, given how a pellet stove works, I would prefer that it continue running as long as needed to get to the set temperature, rather than shutting off after "Cycle Duration".  With "Off Cycle Duration", the stove would remain off, regardless of temperature, for the number of seconds specified.

**Describe alternatives you've considered**
I don't think there is a way of achieving this at the moment in Versatile Thermostat.

**Additional context**
None

**Comment by jmcollin78** [comment]
Hello @kadaan ,

Thank you for your report. There is parameter in VTherm (Versatile Therm ...) that have been introduced for such needs.
This is the "Minimal duration delay" (the first parameter in the screen copy).

![Uploading Capture d’écran 2023-09-24 à 18.10.58.png…]()

If you set the cycle to be very long (let say two hours) and this parameter to one hour, the pellet stove will be activated for one hour minimal every two hours. This ensure you that you will never more than 12 (24 / 2) activation per days.

Is is what you are lokking for ?

**Comment by kadaan** [comment]
Cool. Actually for a pellet stove, the opposite seems nice. The issue is that with a minimum on duration the target temp could be greatly overshot on the high side. With a minimum off duration, I can ensure that the stove only starts X times a day,  it doesn’t overheat the house. I imagine I would set minimum on duration to 15 minutes (which gives the igniter time to start the stove and the stove to reach temp, as this is not an instant or constant duration). I would also set the minimum off duration to 15 minutes, which would ensure that the stove would cycle no more than 4 times per hour (preserving the igniter lifespan).

**Comment by jmcollin78** [comment]
> I can ensure that the stove only starts X times a day, it doesn’t overheat the house

Yes but you will have the opposite: the house can be very cold.

> ... on duration to 15 minutes
this sounds good depending on the heating curve

**Comment by jmcollin78** [comment]
Is it ok for you ? Can I close this issue ?

**Comment by kadaan** [comment]
Sure, sounds good.
