### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by zadori** [jmcollin78/versatile_thermostat#109]
Hey there,

I was running the Beta2 version and just upgraded to the 3.3.7 via HACS but I am getting an Invalid Config from the integration with the following logs:

> This error originated from a custom integration.
> 
> Logger: homeassistant.setup
> Source: custom_components/versatile_thermostat/climate.py:21 
> Integration: Versatile Thermostat configuration (documentation, issues) 
> First occurred: 12:00:50 AM (1 occurrences) 
> Last logged: 12:00:50 AM
> 
> Setup failed for custom integration versatile_thermostat: Unable to import component: cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
>     component = integration.get_component()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
>     ComponentProtocol, importlib.import_module(self.pkg_path)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/config/custom_components/versatile_thermostat/__init__.py", line 11, in <module>
>     from .climate import VersatileThermostat
>   File "/config/custom_components/versatile_thermostat/climate.py", line 21, in <module>
>     from homeassistant.helpers.device_registry import DeviceInfo, DeviceEntryType
> ImportError: cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)

I looked at the commit for 3.3.7 and see things have changed in the import for DeviceInfo.
I am a le to revert to beta2 and have it working again in the meantime.

**Comment by jmcollin78** [comment]
3.3.7 will work only with HA 2023.9. There were a breaking change in HA 2023.09.
