### ISSUE TITLE
Multiple thermostats when using "thermostat over another thermostat" mode

### ISSUE THREAD

**Issue by EPicLURcher** [jmcollin78/versatile_thermostat#113]
**Is your feature request related to a problem? Please describe.**
Ish - I have a room with 2 water radiators, each with their own TRV. I cannot seem to create a single control for this room

**Describe the solution you'd like**
Be able to add 2 thermostats, like you can when using thermostat over a switch

**Describe alternatives you've considered**
Have to have 2 configurations - one per radiator. doesn't seem optimal

**Additional context**
none

**Comment by jmcollin78** [comment]
Hello @EPicLURcher ,

The main purpose of having multiple switch for VTherm over switch is to be able to sequentialize the activation and avoid having all heater on at the same time.

With VTherm over climate, because the regulation is done by each TRV directly, this does not make sense.
However having many TRV managed by one VTherm seems a good idea. I will consider this in a future release.

**Comment by EPicLURcher** [comment]
Thank you!

I think this would be a good, otherwise I need 2 entries for a single room, as it has 2 radiators. It means I also need to have 2 scheduler entries (well, I can multi select in 1 so actually not too much of an issue!). I'd like to be able to just set the target temp of the room, and have all the TRVs in that room do their thing and managed in 1 config. Furthermore, if I want to raise the room temp to say 20c, I have to ask my amazon device to do it 2x - once on Living room and again on Living room 2

See screenshot below of the current implementation - I have 2 entries. 

![image](https://github.com/jmcollin78/versatile_thermostat/assets/74502301/3b385745-fb66-47ee-bf58-6aa8240f49e0)

Im not code savvy enough to help with the implementation of this, but let me know if there is any extra feedback / testing I can help out with, if this does make a future release :)

**Comment by jmcollin78** [comment]
Yes I would probably need you to test the feature when implemented. I keep you in touch

**Comment by EPicLURcher** [comment]
Thank you for adding this feature @jmcollin78 - seems to be working great!

**Comment by jmcollin78** [comment]
Thank you for the beer ! I really appreciate
