### ISSUE TITLE
[Bug] Thermostat not reporting on / off properly (90s delay)

### ISSUE THREAD

**Issue by MaxWaldorf** [jmcollin78/versatile_thermostat#114]
Since last update (multi-thermostat support), piloting thermostat over thermostat has become very hard as the versatile thermostat doesn't report properly the underlying thermostat state...

There is a sort of 90s delay which is bad if you have other automations behind it...

It does transmit the command properly though...

**Comment by jmcollin78** [comment]
Hello @MaxWaldorf ,

I'm very sad to here that. I really don't understand this delay. I don't experience any problem on my side.
Can you please tell me more so that I will be able to reproduce the problem and give me some logs if possible and your configuration ?

**Comment by MaxWaldorf** [comment]
Well, I have a specific setup...

I am piloting a heat pump with SmartIR (Broadlink) and thus I am using versatile thermostat to enhance the thermostat experience but now I wonder if this is a core issue of HASS...

It takes time to report now but might not be up to you since it happens on 3.4.0...

Something changed but can't say for sure where is the delay.

**Comment by jmcollin78** [comment]
For multi-climate feature, I typically have to change this part of code. So I suspect something is wrong.
I will have a look. If it is real problem rollback to 3.3.7.

**Comment by MaxWaldorf** [comment]
Happens with 3.3.7
So I guess this is probably not your issue...

2023.10 changed something but can't see what

**Comment by MaxWaldorf** [comment]
actually... I'm not how to downgrade... system report still 3.5.0

**Comment by MaxWaldorf** [comment]
Ok, I confirm that 3.3.7 works fine...

Sorry but it is definitely something with the last updates :)

**Comment by jmcollin78** [comment]
Yes I'm on it. This was something which was already reporting : some AC report Idle when VTherm ask to shutdown down.
I think this piece of code was not necessary anymore and I removing it.
I will do a beta release with this fix, can you please install it and tell me if all is ok from your point of view ?

**Comment by MaxWaldorf** [comment]
sure

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/3.5.1.beta1

Please wait 10 minutes. I will install it on my home and tells you if you can try it.

**Comment by jmcollin78** [comment]
It sounds good.

**Comment by MaxWaldorf** [comment]
yup, seems to be fine now.

Thanks for your quick response!

**Comment by jmcollin78** [comment]
Thank you for your quick report ;)

**Comment by jmcollin78** [comment]
I will add some tests and make a release (not beta)

**Comment by jmcollin78** [comment]
Done in https://github.com/jmcollin78/versatile_thermostat/releases/tag/3.5.1
