### ISSUE TITLE
Explanation of the two general modes (control of a switch vs control of a thermostat)

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#115]
While the codebase might be very similar for the two general modes, I think Versatile Thermostat would improve of a better documentation and UI regarding these two modes. 

I suggest to use the following for the two modes in the documentation and/or configuration screen:

> **Control of a switch**: Versatile Thermostat will regulate the length of a heating cycle and the pauses in-between by controlling a binary on/off switch. This mode is e.g. suitable for an electrical radiator controlled by a switch.
> **Control of a thermostat**: Versatile Thermostat will regulate the target temperature of a climate entity. Common examples for this mode are the control of thermostatic radiator valves (TRV), air-conditions (AC), floor heating systems and pellet heating.

As many configuration options are only relevant for one of these two modes, I suggest to add a note to each option that is only available for one of the two modes, so that people know what they need to skip when configuring. Or even better would be to grey out the options that are not relevant for the chosen mode.

**Comment by jmcollin78** [comment]
Done in README and README-fr (directly in Github)
