### ISSUE TITLE
Configuring (motion) delays

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#116]
I suggest to rename the options "motion delay" and "minimal activation delay" so it's easier to understand what they do:

**rename "Motion delay" to:** 
`motion_on_delay`: Switch heating mode to higher heating only when motion is detected for at least XXX seconds

**rename "Minimal activation delay to:"**
`motion_off_delay`: Switch heating mode to lower heating XXX seconds after last motion detected

If you'd want to use a paragraph of text in the documentation, here's something you could use:

> Controlling a room temperature is a slow process. We suggest to use mmWave based presence sensors in your rooms to control the target temperature, as these sensors will also detect people who are not moving. But in case you want to use (much cheaper) motion sensors instead, please be aware that they go from off to on to off again within seconds and might not notice your presence if you're sitting still without movement, e.g. when watching TV or at a desk. In such cases you might want to:
> - configure `motion_on_delay` to 1-2 minutes to ensure that your heater doesn't turn on if you're only in the room for a very brief amount of time and
> - set `motion_off_delay` to e.g. 10 minutes so that the heating will stay on as long as the motion sensor registers a movement every 10 minutes.

Also I suggest to move both config options that are related to delays to the same configuration pane.

**Comment by jmcollin78** [comment]
Hello @maia ,

There is misunderstanding at that point:

> rename "Minimal activation delay to:"motion_off_delay: Switch heating mode to lower heating XXX seconds after last motion detected

The minimal activation delay is not what you describe but a minimal delay after switching on a heater before it could be turned off. This is to avoid too many switching which can degrade some equipment (pellet, floor heating, central gas or fuel heating devices which are slow to get in temperature).

There is no `motion_off_delay` but a unique `motion_delay` acting for start of motion or end of motion.

**Comment by maia** [comment]
I see, then our conversation on the HA forums were a misunderstanding. In that case I'd like to suggest to add a feature for a `motion_off_delay`. Versatile Thermostat is about not having to create additional scripts/automations and I'd prefer not to create a dozen helpers (one for each motion sensor) that stay in `on` state for `(last detected motion + 10 minutes)` to control my `boost` setting.

**Comment by jmcollin78** [comment]
I understand the need. If I understand well, you want the `motion_off_delay` to be most greater that the `motion_on_delay`.

**Comment by maia** [comment]
As motion sensors rather tend to be "off" even with people present, a longer delay for `motion_off_delay` probably is more common. But I can imagine situations where someone will want to heat a room to a higher temperature only after being there for a longer time and then to quickly reduce the target temperature when leaving, e.g. in a garage.
