### ISSUE TITLE
unique_id does not slugify the device_name before concatenating with a _suffix

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#117]
Edit: the original issue evolved into something else: the unique_ids that Versatile Thermostat creates do not slugify `device_name`, resulting in unique_ids including spaces and uppercase letters.

I've configured a VTherm over another thermostat and am using an input_boolean as presence sensor entity. Unfortunately the created presence state sensor always shows "Away". I assume it's expecting the presence sensor to report "true/false" instead of "on/off" like a binary sensor does?

As an explanation why my presence is an input sensor: I'm using the Homekit tools to identify if someone is at home. Home Assistant exposes a binary switch for each person and a Homekit automation turns these switches on/off when people arrive/leave. In Home Assistant I then created another binary helper that with automation that will turn on whenever at least one person is at home and otherwise is off.

I also noticed that the entity unique_ids naming seems to have a bug as they include spaces and uppercase letters, e.g. `"unique_id": "Vorzimmer Heizung_presence_state"` as listed below. Not sure if that is a possible issue, but actually all sensors of VTherm have the status "Unknown" (or: "Away" or "Safe").

**.storage/core.config_entries**
```
{
        "entry_id": "50d0339f39d1aed1f470ab16d33f354c",
        "version": 1,
        "domain": "versatile_thermostat",
        "title": "Vorzimmer Heizung",
        "data": {
          "use_window_feature": false,
          "use_motion_feature": false,
          "use_power_feature": false,
          "use_presence_feature": true,
          "name": "Vorzimmer Heizung",
          "thermostat_type": "thermostat_over_climate",
          "temperature_sensor_entity_id": "sensor.vorzimmer_eve_trv_current_temperature",
          "external_temperature_sensor_entity_id": "sensor.terrasse_temperature",
          "cycle_min": 5,
          "temp_min": 12.0,
          "temp_max": 26.0,
          "device_power": 1.0,
          "climate_entity_id": "climate.vorzimmer_eve_trv",
          "ac_mode": false,
          "eco_temp": 15.0,
          "comfort_temp": 17.0,
          "boost_temp": 19.0,
          "eco_away_temp": 13.0,
          "comfort_away_temp": 15.0,
          "boost_away_temp": 17.0,
          "presence_sensor_entity_id": "input_boolean.presence_someone",
          "minimal_activation_delay": 10,
          "security_delay_min": 60,
          "security_min_on_percent": 0.5,
          "security_default_on_percent": 0.1
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": null
      }
```
**.storage/core.entity_registry:**
```
      {
        "aliases": [],
        "area_id": null,
        "capabilities": null,
        "config_entry_id": "50d0339f39d1aed1f470ab16d33f354c",
        "device_class": null,
        "device_id": "03d812f04a660aa22599de7d7757e8d7",
        "disabled_by": null,
        "entity_category": null,
        "entity_id": "binary_sensor.vorzimmer_heizung_presence_state",
        "hidden_by": null,
        "icon": null,
        "id": "27f9362620e1a35be2e1c9abb318511d",
        "has_entity_name": true,
        "name": null,
        "options": {
          "cloud.alexa": {
            "should_expose": false
          },
          "cloud.google_assistant": {
            "should_expose": false
          },
          "conversation": {
            "should_expose": true
          }
        },
        "original_device_class": "presence",
        "original_icon": "mdi:nature-people",
        "original_name": "Presence state",
        "platform": "versatile_thermostat",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "Vorzimmer Heizung_presence_state",
        "unit_of_measurement": null
      },
```

**Comment by jmcollin78** [comment]
Hello,

> I've configured a VTherm over another thermostat and am using an input_boolean as presence sensor entity. Unfortunately the created presence state sensor always shows "Away". I assume it's expecting the presence sensor to report "true/false" instead of "on/off" like a binary sensor does?

For my test I use also input_boolean as presence sensor, and it is working fine. If I look at my fake presence sensor I see 'on' and 'off' for values (it is for what I see the same values as for binary_sensor):

![Capture d’écran 2023-10-08 à 17 57 51](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/f12422b6-298b-48e0-88da-44c63f7fca34)

**Comment by maia** [comment]
Thanks. After an hour or so the sensors started updating, so it's now working. Weird, as I didn't do anything in that time inbetween. 

Still I believe that the automatic unique_id naming is wrong: `"unique_id": "Vorzimmer Heizung_presence_state"`, it should not contain spaces or upper case letters, should it?

**Comment by jmcollin78** [comment]
> "unique_id": "Vorzimmer Heizung_presence_state"

It is never a good idea to have space into id. I don't ever know it was possible

**Comment by jmcollin78** [comment]
May I close the issue ?

**Comment by maia** [comment]
> It is never a good idea to have space into id. I don't ever know it was possible

I did not define the unique id myself. The unique_id is created by versatile thermostat. I consider it a bug in versatile thermostat.

**Comment by jmcollin78** [comment]
Hum, you are right the unique_id is build by concatenation of the device_name (which is the entry name) and a _suffix.
So if your entry name (your VTherm name) have white space it will be in the unique_id.

That is not accurate and I will have to fix that. Changing a unique_id is an issue. All people will loose their entities I guess.

**Comment by maia** [comment]
ouch, that‘s bad news, sorry to hear that.

**Comment by jmcollin78** [comment]
After some research it seems this doesn't generate any problem. I've got many entities with unique_id containing whitespace
(`"unique_id": "Thermostat chambre 4_security_state"`). What is important is that the unique_id is unique.

And because it will generate inconsistency with all existing users and will not take the risk to change this.
