### ISSUE TITLE
Use window/door sensors that are not binary_sensor

### ISSUE THREAD

**Issue by xoferz** [jmcollin78/versatile_thermostat#118]
My alarm system (HikVision AX Pro) has magnet sensors attached on every door and window. I can get them to show up in HA like sensor.ax_pro_home_magnet_6 with status "Off" or "On". Versatile Thermostat only shows binary_sensors for open window management.

**Comment by maia** [comment]
As a workaround, you could create a binary sensor and an automation that updates the binary sensor whenever the magnet sensors detect a change.

**Comment by xoferz** [comment]
> As a workaround, you could create a binary sensor and an automation that updates the binary sensor whenever the magnet sensors detect a change.

As a workaround, I created a binary sensor throut template:
`- platform: template
  sensors:
    open_garage:
        friendly_name: "Garage door open"
        value_template: "{{ states('sensor.ax_pro_home_magnet_6')}}"
        device_class: garage_door`

**Comment by xoferz** [comment]
Good point. Will try that.

Next up - could we define multiple windows/doors here? Or should I use a group helper.

**Comment by jmcollin78** [comment]
You should use a group. For temperature sensor also if needed. A group can be done directly from "Entry" menu (near devices).

**Comment by xoferz** [comment]
Brilliant. Thank you for the comments.
