### ISSUE TITLE
VT thinks that all TRVs are turned off and must be turned on at startup

### ISSUE THREAD

**Issue by Ra72xx** [jmcollin78/versatile_thermostat#136]
When I restart HA, VT always assume that all thermostats it controls are turned off and must therefore turned on, e.g.:

`VersatileThermostat-MZ: Smart Thermostat-climate.mz_thermostat - The hvac mode is ON, but the underlying device is not ON. Turning on device climate.mz_thermostat`

The underlying devices, however, were ON all the time, which can be asserted by the logs.

**Comment by maia** [comment]
I'm seeing this too, the log details states the following source: `custom_components/versatile_thermostat/underlyings.py:144`

**Comment by jmcollin78** [comment]
ok. Is that a problem or just an observation ?

**Comment by maia** [comment]
For me Ii‘s just a line in the logfile, no issue.

**Comment by Ra72xx** [comment]
As far as I can see, only a line in the log file, too. However it seems to indicate a somehow erroraneous state detection at least when starting.

**Comment by jmcollin78** [comment]
Fix is published on https://github.com/jmcollin78/versatile_thermostat/releases/tag/3.7.0.beta3
if you want to test. The release will come soon.
