### ISSUE TITLE
security_delay_min in over climate mode?

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#145]
The documentation says the following about `security_delay_min`: "If the temperature sensor is no more giving temperature measures, the thermostat and heater will turns off after this delay and the preset of the thermostat will be set to security."

I can understand the usefulness for this feature in the "over switch" mode, but I wonder what it does in the "over climate" mode? If the temperature sensor loses connection (e.g. zigbee network down, battery empty,…), will the underlying climate entity really be turned off? So when I'm on vacation for two weeks and the temperature sensor goes down, the heating will be completely turned off at home and it'll start to freeze? 

I would prefer if `security_delay_min` had no effect in the "over climate" mode.

**Comment by jmcollin78** [comment]
Hello, that's it. There is no security mode with VTherm over climate. So `security_delay_min` is no more used.
I will update the documentation.

**Comment by maia** [comment]
Thanks for info and updating the documentation!

**Comment by jmcollin78** [comment]
Fix in last README. Thanks for the tips !
