### ISSUE TITLE
Mean Power cycle

### ISSUE THREAD

**Issue by adi90x** [jmcollin78/versatile_thermostat#146]
Hello, 

Seems that when using 2 ( or more ) heater entity, power consumption input in configuration is multiply by ```n``` heater.
However, if both heater are not same power it leads to a wrong power for the climate ( with impact on power management )
We should either configure each 4 underlying heater with their own power , or maybe just configure total power in configuration no ? 

Good evening ,

**Comment by jmcollin78** [comment]
Hello @adi90x,

Your second proposal make sense. Having the total of power since the better option. I don't want to configure each heater separately.

**Comment by adi90x** [comment]
Could be usefull to have separate info, only if we decide to implement smart power management, like one big and one small heater could be more interesting to switch on maybe only small for 100% instead of 30% small/30% big. But not even sure it is interesting to do that ( as if there is several heater I guess we prefer all at 30% than one full and other switch off !)

**Comment by adi90x** [comment]
Closing with #150
