### ISSUE TITLE
coefficient for external temp doesn't accept decimals...

### ISSUE THREAD

**Issue by MaxWaldorf** [jmcollin78/versatile_thermostat#157]
Version 3.8.1

Very straight forward issue... TPI parameters and the external coefficient cannot accept decimal values...

**Comment by jmcollin78** [comment]
Yes you can. Tell me.more ?

**Comment by MaxWaldorf** [comment]
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/49fe8474-6546-4b6b-9170-9a84d9c0f24c)

I can't modify the second value in that picture with "0.02" it doesn't accept "."

**Comment by jmcollin78** [comment]
Ah ok. It's a running in the ui but not on VTherm. Thé solution is to
copy/paste the value you want to add.

**Comment by TTLucian** [comment]
Same issue on 6.8.0.beta12

**Comment by TTLucian** [comment]
OK! Got it! Sorry to have mentioned it!

**Comment by jmcollin78** [comment]
There is more than 2600 issues open in HA. I suggest, you try to find the good one 😉

**Comment by maia** [comment]
> There is more than 2600 issues open in HA. I suggest, you try to find the good one 😉

I assume this is where you define the input form? https://github.com/jmcollin78/versatile_thermostat/blob/0a658b7a2a3c6ed329e082b81e363d143dc8cc9d/custom_components/versatile_thermostat/config_schema.py#L206-L211

Based on my current search the issue was fixed in 2022 and that you should not be using `vol.Coerce(float)` but rather something like this:

```py
import voluptuous as vol
from homeassistant.helpers import selector

STEP_CENTRAL_TPI_DATA_SCHEMA = vol.Schema(
    {
        vol.Required(
            CONF_TPI_COEF_INT,
            default=0.6
        ): selector.NumberSelector(
            selector.NumberSelectorConfig(
                min=0.0,
                max=10.0,
                step=0.1,
                mode=selector.NumberSelectorMode.BOX
            )
        ),
        vol.Required(
            CONF_TPI_COEF_EXT,
            default=0.01
        ): selector.NumberSelector(
            selector.NumberSelectorConfig(
                min=0.0,
                max=1.0,
                step=0.01,
                mode=selector.NumberSelectorMode.BOX
            )
        ),
    }
)
```

…but as I have no Python experience, I might be completely wrong.

**Comment by jmcollin78** [comment]
@maia this workaround is working fine. Thank you. It wil be in the next release.
/

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.8.1
