### ISSUE TITLE
have global option to start and stop all VTherm automatically

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#158]
To avoid an automatisation that start (HVACMode.ON) and stop (HVACMode.OFF) all VTherm we need an input_boolean or a binary_sensor which can control the HVACMode of the VTherm. I could also be a input_select so that we can choose Off / Heat / Cool useful for VTherm with AC Mode.

The idea is to simplify this feature which needs an automation:
![Capture d’écran 2023-11-04 à 09 04 55](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/11be2a39-69ea-4c80-88ea-68917c3b4a73)

**Comment by MBRetrofit** [comment]
I would add a Note because this "Mode" has no any management syncronisation or algorithm as is just a switch and in the event of using electrical heaters, starting all at once could be tricky...
