### ISSUE TITLE
Only first heater over 3 is started/stopped.

### ISSUE THREAD

**Issue by prigal** [jmcollin78/versatile_thermostat#160]
## Version of the custom_component

Latest. 3.8.1

## Configuration

```yaml

Add your logs here.

```

## Describe the bug
I have 9 rooms configured. 8 of them have only 1 heater, the last one has 3. I configured the integration of your thermostat with 3 heater but only the first one is started/stopped.

## Debug log

```text

Add your logs here.

```

Nb : super projet, merci pour le travail 👍 je viens de migrer depuis smart thermostat qui m'a fait le dernier hiver.

**Comment by jmcollin78** [comment]
Bonjour @prigal, 

Je propose de continuer en Français, je suis beaucoup plus à l'aise comme ça.
Ca ne devrait pas arriver, je suis le premier utilisateur de cette fonction et elle marche très bien chez moi.
Il va falloir que j'en sache un peu plus pour trouver ce qui ne va pas.

J'aurai besoin de ta configuration du VTherm qui ne va pas : dans Outils de dev / Etats, essaye de copier / coller tous les attributs du VTherm qui ne va pas.

Si tu peux me faire aussi un historique des activations de chacun des switchs pilotés par le VTHerm. Ca doit ressembler à ça :

![Capture d’écran 2023-11-05 à 10 22 26](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/229be31c-81fd-486d-bef9-0296e293ac46)
(notamment la partie du bas qui m'intéresse).

**Comment by franckcosta** [comment]
Hello

J’ai le même problème avec 2 thermostat, 2 pieces différentes composé de deux radiateurs.
Je pilote HA depuis HomeKit peut être que c’est ça le problème ? 

Les autres thermostat avec un seul radiateur semble très bien fonctionner, j’ai pas beaucoup de recul, j’ai mis en place ce matin :) 
Lorsque j’initie le chauffage, il lance toujours le « 1er » du setup.

> 

hvac_modes: heat, off min_temp: 16 max_temp: 23 preset_modes: none, eco, comfort, boost current_temperature: 19.7 temperature: 20 hvac_action: idle preset_mode: none hvac_mode: heat type: null eco_temp: 16 boost_temp: 22 comfort_temp: 20 eco_away_temp: null boost_away_temp: null comfort_away_temp: null power_temp: null ext_current_temperature: 13.61 ac_mode: false current_power: null current_power_max: null saved_preset_mode: none saved_target_temp: 20 saved_hvac_mode: null window_state: null motion_state: null overpowering_state: null presence_state: null window_auto_state: false window_bypass_state: false security_delay_min: 60 security_min_on_percent: 0.5 security_default_on_percent: 0.1 last_temperature_datetime: 2023-11-05T14:09:43.763516+01:00 last_ext_temperature_datetime: 2023-11-05T14:09:43.763516+01:00 security_state: false minimal_activation_delay_sec: 10 device_power: 1 mean_cycle_power: 0.27 total_energy: 0.44 last_update_datetime: 2023-11-05T14:09:43.763545+01:00 timezone: Europe/Paris window_sensor_entity_id: null window_delay_sec: null window_auto_open_threshold: null window_auto_close_threshold: null window_auto_max_duration: null motion_sensor_entity_id: null presence_sensor_entity_id: null power_sensor_entity_id: null max_power_sensor_entity_id: null is_over_switch: true underlying_switch_0: switch.flush_pilot_2 underlying_switch_1: switch.flush_pilot underlying_switch_2: null underlying_switch_3: null on_percent: 0.27 on_time_sec: 80 off_time_sec: 219 cycle_min: 5 function: tpi tpi_coef_int: 0.6 tpi_coef_ext: 0.01 friendly_name: Chauffage Salon supported_features: 17
--

**Comment by franckcosta** [comment]
J’ajoute une capture de la configuration…
Et ma version: 2023.10.5
![IMG_0751](https://github.com/jmcollin78/versatile_thermostat/assets/94916534/5beab259-518d-450c-8d68-bd873d7a4d54)

**Comment by diyanei** [comment]
Salut,

(Version Versatile Thermostat: 3.8.1 - Version Home Assistant: 2023.11.1)

J'ai aussi eu cette impression sur une zone avec 3 radiateurs, mais il semble que la chauffe arrive sur les autres, en décalé:
![Screenshot 2023-11-05 at 15-47-11 Historique – Home Assistant](https://github.com/jmcollin78/versatile_thermostat/assets/2079281/732ae16c-9dd7-4610-b305-450a2618a93c)

Est-ce attendu ? À voir si c'est aussi ce qui se passe chez @prigal et @franckcosta ...

Et bien entendu, merci à @jmcollin78 , c'est de la bombe VTherm!

**Comment by jmcollin78** [comment]
... et n'hésitez pas au fur et à mesure que vous progressez dans l'utilisation à aller jeter un oeil au README. Y a pas mal d'infos dedans. Je comprends qu'il faille un peu de temps pour tout comprendre, mais l'info était là-bas.

**Comment by prigal** [comment]
Mea culpa, c'est effectivement ce qu'il se passe. L'algo balance entre les 3 radiateurs. C'est top :)

**Comment by franckcosta** [comment]
Yes cela semble être la même. 

Désolé et merci pour le boulot !
