### ISSUE TITLE
Feature Request: Humidity Data Integration for Better Thermostat Card Display and Calculation

### ISSUE THREAD

**Issue by syberx** [jmcollin78/versatile_thermostat#167]
I'd like to propose the integration of humidity data within the versatile thermostat. While the temperature control is working well, the ability to factor in humidity would be beneficial for more accurate temperature adjustments. At the very least, displaying humidity data in the Better Thermostat Card would be helpful, as it already shows temperature. This could enhance user experience by providing a more comprehensive overview of the environment's conditions. It may also allow for advanced features in the future, such as humidity-based temperature control.

**Comment by jmcollin78** [comment]
Hello, it was already asked and rejected.
Supposing someone will implements this feature, how to integrate humidity into the TPI algorithm ?

**Comment by syberx** [comment]
@jmcollin78 Oh okay sorry, but then at least to the “advertisement”? So not for the calculation but so that it can be displayed in the “Better Thermostat card”?

**Comment by jmcollin78** [comment]
It seems feasible yes.

**Comment by syberx** [comment]
That would be really great :) I would be happy about it.

**Comment by DrDimedrol** [comment]
> Hello, it was already asked and rejected. Supposing someone will implements this feature, how to integrate humidity into the TPI algorithm ?

I think maybe it possible to precalculate target temperature depending of humidity and actual temperature (there is a algorithms to calculate "feels like temperature"  based on humidity) and then do final calculation based on "feels like temperature".

**Comment by maia** [comment]
From what I know, the „Heat Index“ differs from the measured temperature mainly when it‘s very hot or very windy. At an indoor temp of ~20 degrees Celsius the difference between a room with 40% and 60% humidity is less than 0,5 degrees probably less than 0,3. So while there is technically no problem doing that calculation as suggested, I wonder if it‘s worth the effort, if the difference is frequently just a tenth of a degree. Or is my calculation wrong?

**Comment by enryIT** [comment]
Do use the latest Simmer index, that is the "standard" most accurate index.
http://summersimmer.com/home.htm

**Comment by jmcollin78** [comment]
For now, I got too much feature request to deal with, and I have to make some choice. I decide for not doing this yet with the small added value it gives.

Sory if you were waiting for this. Nevertheless I will add the capability to display sensors in the VTherm UI card once a day. This will enable the first initial request
