### ISSUE TITLE
Since PR #150 overpowering is not working as expected

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#174]
In PR #150 , we change the way the power is configured.
This lead to a regression in overpowering calculation.

Expected:
The overpowering calculation should calculate the max(`device_power` / `nb_heater`, `device_power` * `on_percent`) in VTherm overpowering calculation,

So that when on_percent is 100% all the power should be available, or only one heater power (in average).

**Comment by adi90x** [comment]
Hello,
This may lead to an unsecured situation 🫤 where we fired up a heater that use more than the average. 
Don't we want to secure by checking for full power available ?
Regards
