### ISSUE TITLE
Setting for the holiday with automatic insertion by querying the Holiday integration.

### ISSUE THREAD

**Issue by mmazzuro** [jmcollin78/versatile_thermostat#179]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jmcollin78** [comment]
Please add the description and text describing what you want.

**Comment by mmazzuro** [comment]
in my installation I developed it by creating a binary sensor that is activated via the Holiday integration taken from HACS here https://github.com/bruxy70/Holidays, I set Italy in the calendar and the holidays automatically come out . Already tested with 01/11 a national holiday for us.
I saw that Homeassistant has its own integration called Workday https://www.home-assistant.io/integrations/workday/ which is ultimately the same thing, but I discovered it late.
In the scheduler proposed in the versatile_thermostat documentation I created 3 schedules, weekdays, weekends, holidays.
In the programming it allows you to insert a condition, so I inserted the test to the binary sensor created above for the selection of the setting.

**Comment by jmcollin78** [comment]
This is fine and the best to do what you achieve.

So what do you expect for VTherm ? How VTherm should integrate the holidays information ?

**Comment by mmazzuro** [comment]
Hi @jmcollin78,

I was thinking of getting an option to consider a binary sensor like workday , https://www.home-assistant.io/integrations/workday/ or the HACS Holidays integration that everyone chooses and integrates into their installation to allow switching between holidays which can occur on days other than the weekend automatically in comfort, or better if there was an appropriate temperature setting, because on the holiday some might also be interested in a temperature other than comfort.
In the beautiful and brand new UI also insert a specific indication.

**Workday configuration**

![image](https://github.com/jmcollin78/versatile_thermostat/assets/92892064/2aede1ab-47f2-44b7-8aba-87af09bddb9d)


**Holidays configuration**

![image](https://github.com/jmcollin78/versatile_thermostat/assets/92892064/698814a8-f4e0-4841-9ee8-2704c5ca6e63)

**Comment by jmcollin78** [comment]
So, in your opinion, VTherm should do something where you are on Holidays. Fine, but what ?
Switch to a preset ? Turn-off the VTherm ? Other actions ? What is Holidays is detected but there is someone at home ? Should we stop heating ?

The way you integrate it, is the good way and I don't see any added value to have something automated on VTherm.
Every person will want to take its own action.

So, I guess there is nothing sufficiently generical, usable by every one that I can do in VTherm.

In my case, I do nothing when I'm on Holidays. It just let the presence feature do its job: switch to Eco.

**Comment by mmazzuro** [comment]
Ok, maybe I wasn't able to explain my idea well.
I'll give you an example. If you are at home and not traveling somewhere, and like this year Christmas falls on a Monday, I think it's nice, at least for me it is to automatically find a comfortable programming mode like when you stay at home on weekends and not like when one goes to work and therefore generally sets eco because there is no one at home via the presence sensor.
However it doesn't matter, as far as I'm concerned I created it independently with a bit of code, because I really love smart activities and having all the options at my disposal without always having to fiddle around, especially when you're not alone at home and the others are not as smart as elderly people or those who are used to turning the old-fashioned thermostat knob and not using a smartphone or computer.
Thanks

**Comment by jmcollin78** [comment]
I understand you case very well, but I continue to consider it is too specific to have an direct implementation on VTherm.
Holidays information should be combined with presence or activity sensors to have something usable and its creates too much combinaison.

Thank anyway for this proposal. I will close the issue. If you think you want to continue the discussion, open a discussion and not an issue.

Thanks !
