### ISSUE TITLE
Mise en sécurité du thermostat si pas de changement de température

### ISSUE THREAD

**Issue by rhcpdu13** [jmcollin78/versatile_thermostat#18]
Hello,
Une feature request :) 
Ajouter un champ avec le délai entre de 2 changements de température. Le thermostat passe en arrêt / défectueux si pas de changement de valeur de température au bout de x min

**Comment by jmcollin78** [comment]
Les thermomètres à pile n'envoient les températures que si il y a un changement.
Sachant cela, quelle durée sur la mise en sécurité serait pertinente ? On parle en heure ou en minutes ?

**Comment by jmcollin78** [comment]
Release 1.1.0
