### ISSUE TITLE
typo "mesure" in code

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#210]
https://github.com/jmcollin78/versatile_thermostat/blame/ae568c8be26f225629f1569969c38e31e9a4d74b/custom_components/versatile_thermostat/base_thermostat.py#L132

There are many occurrences of the typo `mesure` across `base_thermostat.py` (and maybe other files too?) and I suggest to replace them all with `measure` to prevent future issues.

**Comment by jmcollin78** [comment]
Done in 4.3.0
