### ISSUE TITLE
Force Heating

### ISSUE THREAD

**Issue by adi90x** [jmcollin78/versatile_thermostat#212]
Hello,

In several case it could be usefull to force heating for a given time at the moment, you either have to set temp to something very high or switch hvac off to force heater manually.
This force heating service could be helpfull for example for :

> Force a towel heater to dry towel after a shower
> Reduce humidity in a room
> Make sure a heater run at least xx min per day even if temp > target

And maybe other setup !

Regards,
Adrien

**Comment by xoferz** [comment]
Versatile thermostat usually drives a relay (or other thermostat). When I need "forced" heating, I switch this relay on directly from HA, no need to mix Versatile Thermostat into it.

**Comment by jmcollin78** [comment]
@xoferz if you do that, VTherm will turn-off the switch at next cycle. This has to be included in VTherm if we want to do something clean and reliable.

**Comment by xoferz** [comment]
My "force" automation switches off VTHerm, then relay on directly. When it is finished, relay off and then VTHerm to "heat". No issues so far.

**Comment by jmcollin78** [comment]
Not sure I will take that. This can be easily workaround with an automation as proposed by @xoferz and the use cases seems  specific. 

I keep it open for now, if others need this feature.

**Comment by jmcollin78** [comment]
Hello, no news from a long time, I will close this issue. Don't hesitate to reopen if you think it is relevant.

**Comment by adi90x** [comment]
Hello,

Still interested as I have several scenario where I want to force heating for some time (whatever température is set in vtherm)

Regards,
