### ISSUE TITLE
Gestion mode fils pilote

### ISSUE THREAD

**Issue by drannou** [jmcollin78/versatile_thermostat#214]
**Is your feature request related to a problem? Please describe.**
J'utilise le module de Legrand pour la sortie fils pilote de radiateurs ( type LEG064879). Mes chauffages ne réagissent pas au switch "on/off", mais ils réagissent correctement lorsque la consigne est clairement choisie dans le "input_select".

<img width="308" alt="Capture d’écran 2023-11-20 à 12 19 07" src="https://github.com/jmcollin78/versatile_thermostat/assets/27675549/89f200ba-4884-4033-a90c-1b28b4b4f6a5">

**Describe the solution you'd like**
Dans la liste, il y a principalement le mode "comfort" et "off".
Est-ce qu'il serait possible, lors de la création du thermostat, de choisir le mode switch (comme actuellement) ou un mode "choisir les états" qui demanderait, lorsqu'un input_select est choisis, quels sont les états "on" et "off".

**Comment by jmcollin78** [comment]
Bonjour @drannou ,

Il y a déjà beaucoup de réponses qui traitent de ce point. La solution est un switch virtuel qui va controller le input_select de ton module Legrand en fonction de l'ordre d'allumage / extinction du VTherm.

Look at this one for example: https://github.com/jmcollin78/versatile_thermostat/discussions/209

This are guideline you have to adapt.

**Comment by jmcollin78** [comment]
Ou ce point là : https://github.com/jmcollin78/versatile_thermostat/discussions/177
