### ISSUE TITLE
Unreliable climate temperature reading management

### ISSUE THREAD

**Issue by cova-fe** [jmcollin78/versatile_thermostat#215]
I have a setup with two heaters in the same room (water, centralized heating system) with two different TRV models. Both temperature readings from TRVs are not really reliable, but I have a temperature/humidity/pressure in the same room that works quite well. Unfortunately, only one of the two TRV has the % valve setting, the other allows only the temperature setting, so I'm using over_climate option.

Is there any recommended setup for the versatile_thermostat that basically allows to ignore the TRV temperature reading and use only the wall-mounted sensor? (Maybe something that behaves like a switch, but setting the temperature on TRV very high (to simulate a switch on) and very low (switch off) according to the wall sensor reading.)
Is this situation manageable at all with this thermostat or maybe some coding is required? I can have a look, but only if it is not yet doable.

**Comment by jmcollin78** [comment]
Hello @cova-fe ,

VTherm never reads the TRV temperature. It always read the temperature sensor you gave it in the configuration. If you give the wall-mounter temperature sensor, VTherm will use it exclusively.

**Comment by cova-fe** [comment]
Ok, thanks for the clarification. So my next question would then be: how VTherm tells a TRV in climate mode to increase the heating? If I recall correctly it will send to the TRV the target temperature (from docs it says sends on/off and target temperature), but then the TRV will use his own reading (unreliable). A similar situation could happen if the heater is far from the room sensor.  What happens if the wall sensor reads (say) 18 and Vtherm is set to 20? If Vtherm sends "set to 20" to trv but the TRV reading is unreliable or reads only the local temperature and reads , say, "23", there will be no heating. It could be that I'm reading the docs in the wrong way, I started to read the code but I'm a bit slow in that :)

**Comment by maia** [comment]
> Ok, thanks for the clarification. So my next question would then be: how VTherm tells a TRV in climate mode to increase the heating? If I recall correctly it will send to the TRV the target temperature (from docs it says sends on/off and target temperature), but then the TRV will use his own reading (unreliable). A similar situation could happen if the heater is far from the room sensor. What happens if the wall sensor reads (say) 18 and Vtherm is set to 20? If Vtherm sends "set to 20" to trv but the TRV reading is unreliable or reads only the local temperature and reads , say, "23", there will be no heating. It could be that I'm reading the docs in the wrong way, I started to read the code but I'm a bit slow in that :)

Please try the "slow" setting in the auto-regulation. It will slowly increase the target temperature sent to the TRV so the valve opens.

**Comment by jmcollin78** [comment]
> Ok, thanks for the clarification. So my next question would then be: how VTherm tells a TRV in climate mode to increase the heating? If I recall correctly it will send to the TRV the target temperature (from docs it says sends on/off and target temperature), but then the TRV will use his own reading (unreliable). A similar situation could happen if the heater is far from the room sensor. What happens if the wall sensor reads (say) 18 and Vtherm is set to 20? If Vtherm sends "set to 20" to trv but the TRV reading is unreliable or reads only the local temperature and reads , say, "23", there will be no heating. It could be that I'm reading the docs in the wrong way, I started to read the code but I'm a bit slow in that :)

In that case, the temperature error will increase, and the regulated temp will augment (and sends to the heaters) until the heater heats and target temperature is reach. That is the self-regulation algorithm basis.

You can have a try with Slow regulation as said by @maia . If not sufficient (I have some feedback that sometimes it is not sufficient), tries with more powerfull regulation (the Strong at last).

Slow was not accurate for very cold country (-20°) because it takes the external temperature in consideration with too high level. If you are in temperate country, it could works fine. You have to try and let the regulation stabilize before changing (you maybe should at least wait 24h to see in different configuration how it behave).

**Comment by jmcollin78** [comment]
I close this issue because it seems it is not an issue. Don't hesitate to open a Discussion in the discussion section if needed
