### ISSUE TITLE
The self regulating algorithm needs to relate to heat pumps limit in set-temp range. 

### ISSUE THREAD

**Issue by gunmalmg** [jmcollin78/versatile_thermostat#217]
A little ting that needs to ble solved regarding the Strong-regulation.(and maybe the other levels also)

The Heatpumps have a temperature operation range that can vary from model to model. My models are of two kind. Some operates from 10-30c, and others from 16-30c.
It occurs a problem when the Regulated temperature issues a temperature that is lower (or maybe higher) than the operation range for the underlaying heatpump. The underlaying heatpump simply ignore then new Regulated temperature value if its out of its operation range.
So when I e.g. leave my cottage and lower the VTSet-Temp fra 23c to 10c - the Regulated temperature respond by trying to set the underlaying set-temp to 5c. But since the temperature is outside the temperature operation range of the heatpump, the heatpump simply ignores it and keeps the set point it had before the regulation.
The result of this is that the VT-termostat shows 10c set temp, and 5c Regulated temp, but the underlaying heatpump hase kept its previous set-temp - which is e.g. 25c.
Maybe this hase to be solved by 2 ekstra configuration settings - min and max operation temp for the underlaying unit, and that the algorithm keeps the regulated temp inside these boundaries.

Regards Gunnar

**Comment by gioele-antoci** [comment]
I am having a similar issue, in my case I am trying to use this integration because the temperature sensor is located in a unconditioned place and therefore it reads below the min temperature the airconditioner could reach

I wonder if a solution is to optionally turn on/off the underlying HVAC rather than the integration setting the target temperature

**Comment by gunmalmg** [comment]
Are you using the HVAC as a heater og cooler ?

In my case I use it for heating. I that case it could be a solution to turn the Heat-pump(HVAC) OFF if the integration seeks to lower the set-temperature below the lower range of set-temp for the heat-pump. 
But it that case I think I should decide to turn my heat-pump OFF manually by my self.

**Comment by gioele-antoci** [comment]
>In my case I use it for heating. I that case it could be a solution to turn the Heat-pump(HVAC) OFF if the integration seeks to lower the set-temperature below the lower range of set-temp for the heat-pump.

heating for me to. my issue is kinda unique driven by the fact the underlying unit's sensor is in the wrong spot. for my (maybe) unique situation I would love to have the versatile thermostat turn off the underlying climate rather than trying to reduce the temp below the supported one

**Comment by jmcollin78** [comment]
Same issue as #249 (we need to check if the interval of well working is satisfied before sending regulation).

**Comment by jmcollin78** [comment]
Hello, I publish the beta release just now: https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.1.0.beta1

@gunmalmg can you please give it a try ?

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.1.0

**Comment by gunmalmg** [comment]
Hello 
Little hectic towards Christmas. I will try it as soon as I can :-)

**Comment by gunmalmg** [comment]
It seems to work perfectly 👍

Thanks



tir. 19. des. 2023 kl. 20:50 skrev Jean-Marc Collin <
***@***.***>:

**Comment by jmcollin78** [comment]
@gunmalmg what about the Strong regulation in your very cold country ? Is it working as expected ?

**Comment by gunmalmg** [comment]
It is working very well for the heat pumps. I think you(we) nailed it.

Btw : Norway is not very cold all the time 😜 but it can be. Today it's +2
degrees.

fre. 22. des. 2023 kl. 10:56 skrev Jean-Marc Collin <
***@***.***>:
