### ISSUE TITLE
Frost Protection preset - (hors-gel)

### ISSUE THREAD

**Issue by FredRbn** [jmcollin78/versatile_thermostat#218]
Bonjour et félicitation pour ce travail, chapeau bas. 
Je cherchais un thermostat simple à paramétrer (sans création de multiplies entrée par radiateur par exemple) et ton Vtherm + la carte UI sont mer-vé-illeux. Ils vont au delà de ce j'avais besoin, un travail d'artiste.

La nuit et le weekend je mets certaines pièces en 'hors-gel', et je n'ai pas trouvé ce preset. Je le contourne en utilisant le preset 'boost' réglé sur 7° donc pas de problème pour mon usage.

Voilà c'est juste une suggestion pour une amélioration future : inclure un preset 'hors-gel'.

Encore merci pour ton partage et le temps passé dessus pour notre grand bonheur à tous

**Comment by jmcollin78** [comment]
C'est très demandé en effet. Pour l'instant le mieux c'est de le passer en manuel. Ça se fait avec un service ou avec l'UI

**Comment by jmcollin78** [comment]
Bonjour, c'est implémenté en 4.3.0

**Comment by FredRbn** [comment]
Merci infiniment, très sympa de votre part.

J’adore votre travail, très bien fait et très ’friendly user’

 

 <http://www.capinformatique26.fr/> 

 

De : Jean-Marc Collin ***@***.***> 
Envoyé : dimanche 10 décembre 2023 16:53
À : jmcollin78/versatile_thermostat ***@***.***>
Cc : FredRbn ***@***.***>; Author ***@***.***>
Objet : Re: [jmcollin78/versatile_thermostat] Mode hors gel (Issue #218)

 

Bonjour, c'est implémenté en 4.3.0

**Comment by jmcollin78** [comment]
Merci c'est gentil. N'hésitez pas à me payer une bière à l'occasion avec BuyMeABeer. Ca m'encourage beaucoup à continuer.

**Comment by FredRbn** [comment]
Je le fais dès ce soir, selon mes petits moyens

Frédéric ROBIN - CAP INFORMATIQUE 26

Le dim. 10 déc. 2023, 17:27, Jean-Marc Collin ***@***.***> a
écrit :
