### ISSUE TITLE
Clarification of `temperature_sensor_entity_id` and `external_temperature_sensor_entity_id` 

### ISSUE THREAD

**Issue by escamoteur** [jmcollin78/versatile_thermostat#222]
Hi,

I'm currently testing your amazing thermostat in control over climate but I'm not sure I understand and use the temperature_sensor settings correctly.

I currently have set `temperature_sensor_entity_id` to an external ZigBee sensor because the built-in sensor of the AC unit is often totally off the record in heating mode. I also have set sef regulation to strong which seems to work fine.

But what is `external_temperature_sensor_entity_id` meant for? Outside temperature?

And why are both settings in the table set to '-' when it seems that the thermostat uses the correct temperature from `temperature_sensor_entity_id`

![image](https://github.com/jmcollin78/versatile_thermostat/assets/16635729/27f99842-6297-4d6e-959d-ee3d16a2ee8f)

Thanks a lot

**Comment by maia** [comment]
@jmcollin78 Would you consider to use "outdoor" instead of "external"? Because anyone who has a heating device with a built in sensor will assume that "external" is the room sensor, as this is "external" to the heating device.

**Comment by jmcollin78** [comment]
Yes. It is outdoor temperature sensor. There was a '-' because outdoor temperature was not used until the self-regulation which is still an experimental feature as now.

The documentation should be improved, I agree.

This is done in the master branch
