### ISSUE TITLE
auto-fan mode: Include fan control in self regulation

### ISSUE THREAD

**Issue by escamoteur** [jmcollin78/versatile_thermostat#223]
Hi,

self-regulation in control over climate works great, but it could be greatly enhanced if it would include the fan speed. 
rooms get heated much faster to the target temperature if the delta is big by increasing the fan speed compared to increasing the set temperature and it takes less energy.
Have you ever thought of this as an option?

Best regards
Thomas

**Comment by jmcollin78** [comment]
This seems a good idea. I will keep that for an eventual futur improvement.

What can be the use-case ? When should VTherm activate the fan and deactivate the fan ? Should VTherm deactivate or slow at the end (at the end of what ?) ?

Please try to imagine how VTherm could manage the fan. Maybe it is not so easy.

**Comment by escamoteur** [comment]
I see these scenarios:

- define different fan speeds for the presets, so boost could also set the fan to max
- when the delta of target temp and measured temp is very high set the fan to medium to max because the internal regulation of ACs in heating mode often gets a too high temperature from its internal temp sensor and will then reduce the fan speed too early if the fan is in auto mode
- you also could keep track in how fast the temperature is changing and if it is very slow increase the fan speed and possibly the target temperature. Especially to heat up bigger rooms with an AC the auto mode of the fan is often to low to get the room heated quickly.

when the target temperature is reached I would set the fan to auto. Additionally as I proposed in my other thread I would turn off the AC till the temperature has dropped by as set limit. If then would start off with fan in auto mode which should be fine to hold the temperature.

**Comment by jmcollin78** [comment]
I like the point 2. The point 3 is covered by the self-regulation. Coupling self-regulation algorithm with your point 2 can be great improvement. Thank you for this.

**Comment by jmcollin78** [comment]
Hello @escamoteur 

If you want a preview you can download the `main` branch in HACS. It is working on my environment and I would like to know if it is working in your too. README have been updated.

**Comment by jmcollin78** [comment]
Included in release 4.3.0

**Comment by escamoteur** [comment]
Hey, aweseome, I didn't have the time yet to test it because too busy with other stuff.
Cheers
Thomas

**Comment by jmcollin78** [comment]
Let me know when you will have time.
