### ISSUE TITLE
Documentation change for Homematic thermostats

### ISSUE THREAD

**Issue by Ra72xx** [jmcollin78/versatile_thermostat#228]
I propose the following change of the wording for the Homematic problems:
Instead of
`“Homematic radio” thermostatic valves. They have a duty cycle incompatible with control by the Versatile Thermostat,
`
you could write
`"Homematic" (and possible Homematic IP) thermostats are known to have problems with Versatile Thermostats because of limitations of the underlying RF protocol. This problem especially occurs when trying to control several Homematic thermostats at once in one Versatile Thermostat instance. In order to reduce duty cycle load, you may e.g. group thermostats with Homematic-specific procedures (e.g. using a wall thermostat) and let Versatile Thermostat only control the wall thermostat directly. Another option is to control only one thermostat and propagate the changes in HVAC mode and temperature by an automation.`
My (not necessarily correct) explanation for the problem: Any change from VT is not at once taken over by all thermostats in the same moment because the protocol may take some time. So the thermostats start to be in an inconsistent state, and then VT somehow tries to get all in sync because it thinks there has been a change, and this results in flooding the RF protocol. At least Homegear in imitation of a Homematic central sooner or later gives up in this situation  and looses contact to all devices.
This behaviour is reproducable in my setup and can be avoided by "outsourcing" the synchronisation of multiple thermostats to other mechanisms.

**Comment by jmcollin78** [comment]
Thank you for the explanations ! It is integrated in the README.
