### ISSUE TITLE
Cannot find the underlying climate entity - Log Spam

### ISSUE THREAD

**Issue by Mangomc** [jmcollin78/versatile_thermostat#233]
Hey. Im using your Integration to control my climate device.
But whenever i restart my home Assistant the whole System gets unresponsive for a while because its spamming the anove error into my log. 75.105 Times the same error

Cannot find the underlying climate entity. The error comes because it takes a while for HA to connect to the mqtt Broker and list all devices. 
![Screenshot_20231129-110033](https://github.com/jmcollin78/versatile_thermostat/assets/31132518/e02376d7-25f1-42a4-b284-3ccafc00fc5d)

Maybe u can add a Pause of 30secs or something and try then again to Start the integration

Thanks in advance

**Comment by maia** [comment]
I'm seeing this error (it's not warning but error) about 60 times on each startup, as a thread network needs a few minutes to make all devices available to HA.

**Comment by jmcollin78** [comment]
I will change this to a Warning level as it is only a warning if it is temporary. But this can be also a misconfiguration if this persists.

**Comment by Mangomc** [comment]
I reinstalled my HA today because everything was crashing and HA rebooted all the time on its own.
Now the 75.000 log entries are gone :D
Now only a few. 2-10.
Sorry for the report. I will Mark it as resolved. Thanks for the Quick Support
