### ISSUE TITLE
Impossible de baisser les coef à moins de 0.1

### ISSUE THREAD

**Issue by Idaho947** [jmcollin78/versatile_thermostat#235]
Par défaut le coefficient externe est à 0.01.
J'ai voulu l'augmenté parce que sur certains radiateur je n'atteins pas la cosigne. Sauf que je ne peux pas mettre moins que 0.1 est c'est trop. J'ai essayé plusieurs navigateur mais c'est la même chose.

**Comment by jmcollin78** [comment]
C'est un bug de l'UI et je n'ai pas du tout la main dessus. Le mieux est de faire un copier/coller depuis un éditeur de texte ou de taper 0.1 et d'ajouter le zéro manquant après
