### ISSUE TITLE
Central configuration panel

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#239]
I've just come across an integration (via HACS) that offers one "central" configuration and then one configuration per device: https://github.com/krahabb/meross_lan

See here:
<img width="881" alt="Bildschirmfoto 2023-11-30 um 19 01 36" src="https://github.com/jmcollin78/versatile_thermostat/assets/9836/c3ce8608-6ae6-48d5-9809-a8c00f529c3c">

The first entry is what could be used as "central" configuration for versatile_thermostat:
<img width="880" alt="Bildschirmfoto 2023-11-30 um 19 01 25" src="https://github.com/jmcollin78/versatile_thermostat/assets/9836/2fb12b9e-3722-4ed3-aa25-99708e15a53c">

Next are all devices of this integration:
<img width="889" alt="Bildschirmfoto 2023-11-30 um 19 05 02" src="https://github.com/jmcollin78/versatile_thermostat/assets/9836/d80959a7-c59e-4d54-82df-7edfeacd2103">

Using this logic could drastically reduce the configuration screens for versatile_thermostat, as probably >50% of all config options can probably be centralised, once for all rooms.

**Comment by jmcollin78** [comment]
Starting development of this.

**Comment by maia** [comment]
That's great news!

**Comment by jmcollin78** [comment]
A preview is here: https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.0.0-alpha1

The documentation have been update in the branch 5.0.0-alpha1.

You can give it a try (or wait that I do the first test in real environment).

**Comment by jmcollin78** [comment]
It is ok on my env. You can test if you want.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.0.0
