### ISSUE TITLE
Security State seems to never stop after having been activated ?

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#241]
### Discussed in https://github.com/jmcollin78/versatile_thermostat/discussions/238

<div type='discussions-op-text'>

<sup>Originally posted by **kitty99hub** November 30, 2023</sup>
Hi,
Since 2 days, I have had problems with my versatile thermostat.
I used it to control an electrical radiator, and it worked fine for about 2 weeks.
If I turn the thermostat to "heat", after a short time (one or two minutes), it turns automatically off.
Now I have seen that it has an entity called "security state" and that this was tripped to "unsafe"....
Unfortunately, I could not find any information about this entity and the state "unsafe".
Any idea what will cause such an unsafe state?
Many thanks
kind regards</div>

**Comment by jmcollin78** [comment]
I cannot reproduce the case. We have to store log when this happens.

**Comment by jmcollin78** [comment]
I add some clues and dianostics into the README here : https://github.com/jmcollin78/versatile_thermostat/blob/main/README.md#why-does-my-versatile-thermostat-go-into-safety

I wait a few and then I will close this issue if it is not reproduced anymore. This can always be reopen if issue reappears.

**Comment by jmcollin78** [comment]
Please reopen if you think there is some real issue and follow the diagnostic link above

**Comment by jezzaaa** [comment]
Hi. I seem to have this problem right now. Unsafe state for the last few hours, but both temp updates are coming through.

From developer tools > states:

```
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-06-06T13:16:19.998409+10:00"
last_ext_temperature_datetime: "2024-06-06T13:32:13.870588+10:00"
security_state: true
last_update_datetime: "2024-06-06T13:41:07.211010+10:00"
```
The heater is actually still coming on and going off, but the thermostat card is showing a blur, with room temp 7 min and external temp 6 min:
![image](https://github.com/jmcollin78/versatile_thermostat/assets/2043918/d6779c39-14dd-43e3-a238-55d8e8e50e27)

The history graph doesn't seem to show it being turned on by the thermostat, yet it's definitely being switched on and off with the smart switch (ZigBee).
![image](https://github.com/jmcollin78/versatile_thermostat/assets/2043918/84674e03-864a-4e5e-8507-91a9a4bed582)

**Comment by jezzaaa** [comment]
I believe the thermostat was coming on and off, but not enough to warm up to the target temp.

I had to get the thermostat working again, because it was too cold. So I reconfigured the vtherm (without changing any settings) and the state has changed back to "safe", and the thermostat is working correctly again.

**Comment by jmcollin78** [comment]
Thank you for your report.

**Comment by jezzaaa** [comment]
This has started happening again for me. The "Last temp" is showing 27 minutes ago, but the security state is still "Unsafe".
![image](https://github.com/user-attachments/assets/d343f8bf-3a75-4eb8-bb1c-f25145d39dfb)

The heater is still going on and off, switched by VT.

![image](https://github.com/user-attachments/assets/9d695fd0-f995-4bc8-810c-513bfb51c9e9)

**Comment by jezzaaa** [comment]
Is there any more diagnostics I can do to identify the problem? The relevant details are updated here:

security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-07-19T13:26:01.683800+10:00"
last_ext_temperature_datetime: "2024-07-19T13:25:56.683557+10:00"
security_state: true
last_update_datetime: "2024-07-19T13:27:36.926443+10:00"
last_updated: "2024-07-19T03:27:36.930172+00:00"

**Comment by jmcollin78** [comment]
Hello @jezzaaa ,

I have no idea of what happens. Last dates seems ok:
```
last_temperature_datetime: "2024-07-19T13:26:01.683800+10:00"
last_ext_temperature_datetime: "2024-07-19T13:25:56.683557+10:00"

ast_update_datetime: "2024-07-19T13:27:36.926443+10:00"
```
but the safety seems to be on : `security_state: true`
and the display is not coherent: 
![Capture d’écran 2024-08-14 à 08 00 22](https://github.com/user-attachments/assets/7ea7b9c1-d291-4667-a07a-08b45dbc130b)
but anymay it is below the configuration threshold (60 min).

It is totally not understandable. Are you sure all these elements are taken at the same time ?

**Comment by jezzaaa** [comment]
Yes I'm sure they were all in the one set of attributes.

Next time the thermostat goes into secure state, I will provide the complete set of attributes. I've turned on debug logging too, so I should be able to provide that.

The problem corrected itself, I think when I rebooted due to an upgrade of HA, about a week ago. It hasn't failed since then.

**Comment by jmcollin78** [comment]
Thank you for your report
