### ISSUE TITLE
Add the device power and device energy into attributes

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#25]
.. and see if it possible to expose a _power attribute which is the radiator_power * on_percent.
Don't know if it is a good value.

Maybe a most global energy value which the sum (radiator_power * on_percent * cycle) is most useful. Or the both ?

But this don't work if the power of radiator is not known or if it is changing over time. This will be an issue for hvac for which power is not a constant.

**Comment by Egainmoney** [comment]
I confirm, having the possibility of knowing the consumption of our basic convectors and being able to calculate a cost would be a plus. We could finally add them to the Energy panel of HA. for the moment my pilot thread cannot trace this kind of data.

**Comment by adi90x** [comment]
Hello,
The idea is to have something like powercalc custom integration include directly in versatile_thermostat ?
Regards,

**Comment by jmcollin78** [comment]
Yes ans this have been released Yesterday.

**Comment by adi90x** [comment]
Thanks, just got the update in HA
I will have a look and see whether it makes sense to make the move !

Have a good evening and thank a lot for your hard work !

Le lun. 27 févr. 2023, 20:40, Jean-Marc Collin ***@***.***> a
écrit :
