### ISSUE TITLE
Why the VT continue to pilot the output?

### ISSUE THREAD

**Issue by lio908** [jmcollin78/versatile_thermostat#252]
## Configuration

My VTherm attributes are the following:

hvac_modes: heat, off
min_temp: 7
max_temp: 20
target_temp_step: 0.1
preset_modes: none
current_temperature: 18.2
temperature: 18
hvac_action: idle
preset_mode: none
is_on: true
hvac_mode: heat
type: null
eco_temp: 0
boost_temp: 0
comfort_temp: 0
eco_away_temp: null
boost_away_temp: null
comfort_away_temp: null
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 9.5
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 20
saved_hvac_mode: heat
window_state: off
motion_state: null
overpowering_state: null
presence_state: null
window_auto_state: off
window_bypass_state: false
security_delay_min: 5
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2023-12-08T10:41:11.052608+01:00
last_ext_temperature_datetime: 2023-12-08T10:28:11.828343+01:00
security_state: true
minimal_activation_delay_sec: 30
device_power: 1000
mean_cycle_power: 100
total_energy: 37502.5
last_update_datetime: 2023-12-08T10:41:11.068455+01:00
timezone: Europe/Paris
window_sensor_entity_id: null
window_delay_sec: 5
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
temperature_unit: °C
is_device_active: false
ema_temp: 18.22
is_over_switch: true
is_inversed: false
underlying_switch_0: input_boolean.on_off_fp_chambre_sl_vt
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0.1
power_percent: 10
on_time_sec: 60
off_time_sec: 540
cycle_min: 10
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
friendly_name: CHAMBRE_SL
supported_features: 17

## Describe the bug

Sometimes,
t
![Capture](https://github.com/jmcollin78/versatile_thermostat/assets/33791050/14c755ba-5455-4828-ad4f-436de072bf71)
he VT continues to pilot the output even if the temperature is higher than the reference
```

**Comment by lio908** [comment]
![Salon](https://github.com/jmcollin78/versatile_thermostat/assets/33791050/a0d420d3-d4e6-48a0-b019-5f1dd8583815)
 And now, power limited and temp not reach

**Comment by jmcollin78** [comment]
Hello, all of your temperature preset are 0 or null. Is that normal ?

```
eco_temp: 0
boost_temp: 0
comfort_temp: 0
```

**Comment by jmcollin78** [comment]
Ok I understand what happens: your VTherm is in security mode:

```
security_state: true
```

because you have put 5 minutes into the security delay:
```
security_delay_min: 5
```

and the last external_temperature refresh is more thatn 15 min ago:
```
last_ext_temperature_datetime: 2023-12-08T10:28:11.828343+01:00
```

In that case, the VTherm heats with a default percent of 10%:
```
security_default_on_percent: 0.1
```

Just fix the `security_delay_min` to 60 min and all will comes back to normal life.

**Comment by jmcollin78** [comment]
> Oui mes preset sont à 0 car je les force par un sélecteur (TEMPO ROUGE,
HORS GEL, ABSENT, ECO, CONFORT, CONFORT+)
Dans la doc, c'est marqué qu'on peut utiliser le mode manu et donc pas
renseigner ces valeurs.

Oui y a pas de soucis mais le coeur du fonctionnement du VTherm c'est de fonctionner avec les presets. Tu es le premier que je vois a ne pas avoir du tout de presets. Tu ne pourras pas faire de détection des absences et des mouvements typiquement.

> J'ai mis 5min car si pb de sonde, je veux rapidement mettre en sécu car je chauffe avec des convecteurs.

Je vois bien l'idée, mais il faut doser ce paramètre convenablement en fonction de tes sondes de température (intérieur et extérieur).

**Comment by lio908** [comment]
Merci du retour

En fait j'utilise les fils pilotes des mes radiateurs pièce par pièce.
Et comme il n'y a que 3 options dans le VT (Fil pilote 3 ordre?), j'ai
délocalisé cette gestion et force la température cible des VT selon le mode
choisis dans la pièce: HORS_GEL=14, ABSENT=16, ECO=17, NUIT= 18,
CONFORT=19, COMFORT+ = 20.

Ce serait bien d'ajouter une option fil pilote 6 ordres permettant
d'étendre à 6 modes.
Avec la possibilité de forcer ces modes en délocalisé, j'ai un mode MAISON
qui touche tous les modes en même temps.

Et là, problème, j'ai 2 sondes de temp en 433mhz qui bougent plus.
J'ai des zigbee en plus pour contrôler. Une fois c'est les Zigbee, une fois
c'est les 433mhz (Oberon).
Pas très stable toutes ces sondes...


Le ven. 8 déc. 2023 à 16:11, Jean-Marc Collin ***@***.***> a
écrit :

**Comment by jmcollin78** [comment]
C'est prévu d'ajouter le hors gel mais pas plus. Le absent peut être gérer nativement par VTherm avec la gestion de la présence, le mode nuit est géré nativement soit par la gestion de mouvement soit par un passage en Eco et le Confort+ c'est le boost.

Avec les presets, les presets si absent, les presets si AC et les switchs automatique de preset tu devrait te séparer de ton automatisation. Je l'ai d'ailleurs fait pour avoir le minimum d'automatisations à coté.

C'est l'esprit (mais après chacun fait comme il veut).

**Comment by jmcollin78** [comment]
Si c'est ok, tu peux fermer l'issue (je préfère le mode discussion, les issues c'est pour les bugs ou les demandes d'évol)

**Comment by jmcollin78** [comment]
Le hors gel est livré en 4.3.0.
