### ISSUE TITLE
[Enhancement]: specify hvac_mode to use when window open is detected.

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#255]
### Discussed in https://github.com/jmcollin78/versatile_thermostat/discussions/254

<div type='discussions-op-text'>

<sup>Originally posted by **Abyssmal** December  8, 2023</sup>
Firstly - thank you for your great work! It's amazing how much thought went into this project. I will be making a donation in a bit.
I've been using VTherm for 2 months now (start of heating season here). I've incorporated door/window sensors, motion/presence, power meters on the hvacs. Everything! Also using it over two convector heaters. And it's working flawlessly. Energy bill went 15% down, maybe more.
In cold season as can be expected windows and doors are being opened just a few times a day to freshen up the air. I've made some node red automations to switch mode to fan_only when window is open and VTherm turns off, so it ventilates the room faster. And after closing - switching to heat mode.

**Problem** is - the integration turns completely off the hvacs on window open, which can significantly impact the life of the hvacs - closing and opening the covers.

**Proposal**: add option to _**change hvac mode**_ on window open, instead of turning off.

Again keep up the great work, my friend. You, sir, are a time saver!

PS: Sorry for incomplete topic title.</div>

**Comment by raphpa** [comment]
I would like to set the thermostat to a (low) target temperature on window open.

The Aqara TRV E1 does a full valve cycle (moving to full open, then to full close) when you set it to Off. This obviously drains a lot of battery. Setting it to a low target temperature would just make it close the valve directly.

**Comment by jmcollin78** [comment]
Développement in on the way.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.3.3
