### ISSUE TITLE
Modes mapping for connected climate devices

### ISSUE THREAD

**Issue by diabl0** [jmcollin78/versatile_thermostat#258]
**Is your feature request related to a problem? Please describe.**
In most of my rooms, I have an AC unit (kinda dumb) and a central heating radiator with TRV valve (Tuya TS0601). Both of them have incompatible modes. In my case:

TRV:
- heat - valve always fully opened
- auto - valve controlled by heating setpoint
- off - valve fully closed

AC:
- off
- heat_cool - switches between heat/cool but without temperature control (hard set to 25).
- cool
- heat
- fan_only
- dry

I wanted to use VT to control them together - especially since self-regulation works great using external temperature sensors (my AC units have very bad built-in thermostats). Unfortunately, when selecting multiple climate entities created climate entity has hvac_modes copied from the first climate entity, and since they don't match (especially heat mode between AC and TRV) that makes them unusable. 
Current situation:
In VT AC is set as the first unit, TRV as second and mode on VT is set to heat at 21°C. After 2 hours room temperature is 23°C, AC setpoint dropped to 20°C idling and the TRV is also set to 20°C but due to the mode set as heat valve is still fully opened.

**Describe the solution you'd like**
Manually match modes between VT modes and underlying controlled climate entities

**Describe alternatives you've considered**
Overwrite hvac_mode for entity - eg forcing heat to be auto for TRV

**Comment by jmcollin78** [comment]
Hello,

You cannot have non consistent devices under the same VTherm. This will cause many issues like this one. This is just impossible to do something with such a configuration. Very sorry.
