### ISSUE TITLE
Combine Motion and presence feature: when no motion use Eco or Eco_away preset depending of the presence state.

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#267]
### Discussed in https://github.com/jmcollin78/versatile_thermostat/discussions/264

<div type='discussions-op-text'>

<sup>Originally posted by **mldytech** December 10, 2023</sup>
Hi,

is there any way to set a temperature in motion preset when there is no presence at all? 
Right now, the motion state is configured to eco when "no motion" is detected, and to comfort if there is "motion". When nobody is home, the temperature is therefore set to eco. However, I would like to set this to a lower temperature.

Thanks and best regards,
mldy</div>

**Comment by jmcollin78** [comment]
Hello, I understand your case but this is not possible to natively use both presence and motion and combine them.
But this could be an interesting improvement and I think very simple to do.

What I think is to use the Eco preset temp if present or the Eco_away preset temp if not present.
I will keep it as an enhancement issue.

**Comment by cdenfert** [comment]
I vote for it :)
I had to make a few automations to get around the problem, but it would be better in native mode.

**Comment by jmcollin78** [comment]
Done in https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.8.0

**Comment by cdenfert** [comment]
Great news, thank you for all your work !

**Comment by gdessard** [comment]
Un grand merci, cela marche super. 2 evenements maintenant pour le chauffage pour le passage en mode éco la nuit et activity le jour.

Au départ, j’avais  20 événements pour gérer l’arrivé de chaque personne, le départ ets les détecteurs de mouvements...

Et l’état des vannes est super clair. Mes thermostats netatmo sont  plus efficaces que la programation base du constructeur. 

Vraiment génial. Merci
