### ISSUE TITLE
[5.0.1] Preset not saved

### ISSUE THREAD

**Issue by MaxWaldorf** [jmcollin78/versatile_thermostat#284]
Once configured a first time, the values of the preset configurations are not shown or saved (?).

Once configured, if I go back to configuration of the device, the values show all 0...

![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/1634abfa-a000-451a-ade1-1d13f360f644)

**Comment by jmcollin78** [comment]
Hello @MaxWaldorf,

I am very surprise of this. Have you some error logs ?
Can you send me the exact sequence of screen reproducting the issue please ?

**Comment by MaxWaldorf** [comment]
Here are all windows:

![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/a3a33697-c302-4c4a-b478-a439c8bb7020)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/b2f109e8-dfc9-440d-884e-4e9e20217678)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/de6530db-b89b-4f96-ad21-d02a050d0e3c)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/d7cb4277-7f4c-420d-8aa4-0088272cee6c)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/dc7e8992-c0ca-46a4-ae54-64a63c655bce)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/1bcda88e-aff7-4464-bbdf-de5a92ae5b7f)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/7392e66a-96c3-4889-9ce4-4d825ac53dfb)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/136b06f0-4333-47f6-ba48-0dd93007828c)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/932ca95c-f9f3-44cd-98c1-c4a35dc7dae8)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/fd179e49-1913-439f-889a-cb61f60455ce)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/0529c909-d556-4913-8a19-0ae6a3feb7ab)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/32c9c6f9-cb74-4098-8c62-a6181ec2f9cf)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/2894fcaf-dcbd-4a45-abab-640786890290)

**Comment by MaxWaldorf** [comment]
No, it saves as expected but my point is that if I change the configuration then all values show up execpt preset that is 0 everywhere...

I would have thought it would bring back the former values I set...

**Comment by jmcollin78** [comment]
Yes it should bring back the previous values of the presets.

**Comment by jmcollin78** [comment]
I just try and you are right the values are resetted to 0 when I come back on the same screen. Thank you for the report !

**Comment by jmcollin78** [comment]
The presets are well saved, they are "just" not recalled on the update screen.

**Comment by jmcollin78** [comment]
Done in main branch (ora wait for next release)

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.1.0
