### ISSUE TITLE
[5.0.1] Missing AC presence values in configuration...

### ISSUE THREAD

**Issue by MaxWaldorf** [jmcollin78/versatile_thermostat#285]
The default setting page when ticking the AC box is correct but the presence doesn't offer any AC dedicated presets for presence...

**Comment by jmcollin78** [comment]
Strange. I have automated test for this which are working as expected.
Can you please send the exact sequence of configuration screen which reproduce this issue. Will try to reproduce myself, but yesterday when publishing 5.0.1 I have done a lot of automated and manual tests.

**Comment by MaxWaldorf** [comment]
Here are the relevant pages:
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/6007991a-d8f6-43d9-bb83-a9f762bac59a)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/324d9862-d3d7-400b-9ef8-feaa043502ce)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/15877853/c25cafda-ca10-4135-ac60-9941419fc56c)

**Comment by jmcollin78** [comment]
Hello, I guess this is normal. A switch cannot manage both mode (heat and cool) but only heat or only cool.
There is no way to change the hvac_mode of a switch.
So for a switch with ac_mode checked you only give the target temperature of the ac mode.

I know this can be a few confusing.

**Comment by MaxWaldorf** [comment]
Well I did manage to have an automation to switch the heat pump between summer and winter mode (heat / cool)...

In this case, the thermostat card offers both heat and cool which is confusing because it should one or the other if I understand your point.

Anyway, I'm evaluating what to do with version 5 given that it is changing again my approach on saving heat and cool and electricity...

**Comment by MaxWaldorf** [comment]
It is not ideal but that was a layer on top of your plug-in.

I didn't like the fact that heat pump was on all the time and overheating the room even with adaptation.

Some heat pump presets are way too inaccurate compared to 3rd party sensors that have a 0,1 precision.

I end up with +1 to +2c over temp... 

So making a switch automation on top allows me to have better control over it so far.

I'll rethink the strategy later...

**Comment by jmcollin78** [comment]
> I end up with +1 to +2c over temp...

With sekf-regulation, you should not have this.


My strategy is the following:
- have an Scheduler which starts (hvac_heat) / stop (hvac_off) the clim at specific hours and in the same Scheduler, change the preset. The clim is in the bedroom so it can't be shutoff on the morning (10:00) and turned on at 22:00 during the offpeak hour. If it is really cold, and need some heating during the day, I turn it on manually.
