### ISSUE TITLE
Cannot enable or configure self-regulation /  auto-regulation

### ISSUE THREAD

**Issue by GeitjeG** [jmcollin78/versatile_thermostat#287]
For some reason I cannot find the options for auto-regulation mode (or is it called self-regulation?). If I work through the configuration flow in HA, I come not accross these settings... Where to find them? 

![image](https://github.com/jmcollin78/versatile_thermostat/assets/17948603/899af26d-55cf-4ccd-bfd5-58d95c3bb310)

**Comment by jmcollin78** [comment]
Hello @GeitjeG ,

Auto (or self) regulation is available only for VTherm over climate. I don't know what kind of VTherm you are trying to configure but that may be your point.

**Comment by GeitjeG** [comment]
Sorry, I double checked before reporting this, but for some reason I had an old version after all. I updated yesterday and now I can configure self-regulation. It is working great! Thanks... This thread can be removed.
