### ISSUE TITLE
Thermostat stop without any raison

### ISSUE THREAD

**Issue by Chilgl0rd** [jmcollin78/versatile_thermostat#296]
Hello,

I started yesterday evening the heater of a room at 13°C in order to benefit of the electricity low rate to obtain 19°C.
The thermostat switched off without any raison and start again and continue to bug this morning and again this afternoon. I tried to start manualy and force preset & on/off the thermostat doesn't react

I was expecting the thermostat keeping heater on until #19°C and then cycle to keep the heat using TPI.

## Version of the custom_component
5.1.0

## Configuration
hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 23
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 16.4
temperature: 19
hvac_action: idle
preset_mode: none
is_on: true
hvac_mode: heat
type: null
frost_temp: 7
eco_temp: 17
boost_temp: 21
comfort_temp: 19
frost_away_temp: 7
eco_away_temp: 7
boost_away_temp: 7
comfort_away_temp: 7
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 10
ac_mode: false
current_power: 303.8
current_power_max: 4500
saved_preset_mode: comfort
saved_target_temp: 19
saved_hvac_mode: heat
window_state: "off"
motion_state: null
overpowering_state: false
presence_state: null
window_auto_state: "off"
window_bypass_state: false
security_delay_min: 30
security_min_on_percent: 0.5
security_default_on_percent: 0
last_temperature_datetime: "2023-12-24T14:39:50.823519+01:00"
last_ext_temperature_datetime: "2023-12-24T14:31:40.734738+01:00"
security_state: true
minimal_activation_delay_sec: 10
device_power: 3.6
mean_cycle_power: 0
total_energy: 61.97
last_update_datetime: "2023-12-24T14:39:50.826653+01:00"
timezone: Europe/Paris
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: null
power_sensor_entity_id: sensor.power_supply_electric_consumption_w
max_power_sensor_entity_id: input_number.shedding_limit
temperature_unit: °C
is_device_active: false
ema_temp: 16.37
is_over_switch: true
is_inversed: false
underlying_switch_0: switch.heater_living_room
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 600
cycle_min: 10
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
friendly_name: Thermostat Living Room
supported_features: 17

![Capture d'écran 2023-12-24 141811](https://github.com/jmcollin78/versatile_thermostat/assets/99122085/1a3b80fa-167c-41c9-ac53-fc4c2543a0dc)

**Comment by Chilgl0rd** [comment]
I use an helper for temperature of the room (group of sensors, arithmetic mean).
Is it possible than after an delay sometimes the thermostat goes to safety mode because the temperature measurement is not correctly taken in account ?
I restarted HA and the thermostat has run well for  30 minutes (safety delay) before to stop again. I setup now the delay to 300 minutes to check.

Regards,
Xtof

**Comment by dizzydnallov** [comment]
I'm not sure if this is related, so I'm just commenting before I open a new case

Since I upgraded to 5.1.0 I have a similar issue; after instructing a switch-on; my unit (AC Unit) switches on as it should but then switches off for no reason after just a couple of seconds.  I have to do it again, and it seems to stick the second time of asking.  What's really annoying is that this is screwing up my schedule, as nothing is on in the morning.

See below showing the kitchen and living room; the schedule engages at 08:30 to turn on, Versatile turns AC on, but it immediately turns off 

I will collect some logs and open a new issue, but for now see what is said here

![Screenshot 2023-12-25 113617](https://github.com/jmcollin78/versatile_thermostat/assets/105526388/66db41e4-3d9f-45b6-bcde-c76ff79ee2bf)

**Comment by jmcollin78** [comment]
Hello,

You are in security/ safety mode. Please read this: https://github.com/jmcollin78/versatile_thermostat/blob/main/README.md#why-does-my-versatile-thermostat-go-into-safety

I see this because of `security_state: true` in your attributes.
