### ISSUE TITLE
README.md index entries do not link to sections 

### ISSUE THREAD

**Issue by HACS-bank** [jmcollin78/versatile_thermostat#301]
The contents index hyperlinks to the page, rather than to sections within the page, as experienced in the github app on android.

**Comment by jmcollin78** [comment]
I don't have your point. Can you give me an example. ?

**Comment by HACS-bank** [comment]
Looking at the readme, if I click on any part of the blue contents, it links to the top of the page. This may be a restriction of the Andriod Github app.

Jem
________________________________

**Comment by jmcollin78** [comment]
It is working normally in the Github web site I guess. Can you confirm ?

**Comment by HACS-bank** [comment]
Works in chrome on windows.
On android, chrome launches github app.
Problem only seen in android github app.
