### ISSUE TITLE
Issue starting climate after schedule set to off

### ISSUE THREAD

**Issue by MaxWaldorf** [jmcollin78/versatile_thermostat#304]
Been here while but forgot to report it.

When you set the scheduler to off for a period of set time and then configure a preset like eco or comfort then the climate doesn't start...

I need to set to heat and temperature to start it over...

**Comment by jmcollin78** [comment]
Hello @MaxWaldorf ,

You should start the VTherm before changing preset. I will not start automatically the VTherm on preset change.
This is to avoid wrongly starting a VTherm because the scheduler is still running.

But you simply start the VTherm with the Scheduler. I do that on a VTherm.
