### ISSUE TITLE
The desired step size for setting the target temperature

### ISSUE THREAD

**Issue by ckellerdk** [jmcollin78/versatile_thermostat#311]
Hi
I would like an option to change the step size of the desired temperature.

Would this be an option?

**Comment by HACS-bank** [comment]
In my home, some of the thermosensors have 1° resolution. In an ideal
world, the UI would find that out somehow and automatically use the same
step size.

**Comment by jmcollin78** [comment]
If someone is ready to do a PR of this subject I will be glad to merge it. It is something easy to do, and I can help if needed.
I'm on more important subjects for now.

**Comment by giopeco** [comment]
I will also add to the request! beer offer guaranteed!
thanks for the great work!

**Comment by giopeco** [comment]
for the time being, is it possible to manually modify some parameter to bring target_temp_step to 0.5?

**Comment by jmcollin78** [comment]
@giopeco so many thanks for the beer ! You rocks 

The update is available on the main branch if you don't want to wait the next release.
