### ISSUE TITLE
central configuration description vs device configuration description

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#313]
It seems as if vTherm is using the same description for some panels regardless if one is configuring a central instance or a specific device. For example in the central configuration panel "motion management" there's written: "Leave corresponding entity_id empty if not used." but there obviously is no entity_id available in the central configuration panel. It's the same issue for "power management" panel and "presence management".

**Comment by jmcollin78** [comment]
OPk, I got your point. Thank you for the report.

**Comment by jmcollin78** [comment]
Release 5.2.1
