### ISSUE TITLE
central configuration: two very similar checkboxes in the config

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#314]
When editing the configuration of a single device, there are two options related to the central configuration shown on the same panel:

```
[x]  Enable the control by central mode ('central_mode')
…
[ ]  Use central main configuration
```
It's unclear what the difference between the two is. In my personal case, I configured a central configuration after upgrading to 5.x, then wanted to reconfigure all existing climate devices to use this central configuration. 

In case the configuration really needs two checkboxes related to the central configuration panel, I suggest to a) place them underneath each other instead of having a few other options inbetween, b) add a description for the 4 combination options (both unchecked, one checked, both checked), c) remove the `('central_mode')` in the text as no user will ever see the variable names used internally and d) improve their naming.

For now I won't reconfigure my existing devices as I do not know what the proper combination of checked and unchecked boxes is that does not cause something I wouldn't want. :)

**Comment by jmcollin78** [comment]
Hello @maia ,,

There is two features:
1. a central configuration that allow to centralize some configuration,
2. a central mode which allow to control all VTherm with a unique select entity. The select entity needs the central config but is a separate feature.

It is really not easy to explain and certainly more easier to understand when you use it.

Is it more clear now ?

**Comment by maia** [comment]
Hmm, I'm not sure if I correctly understand the explanation, let me try. Is this interpretation correct?

Three modes are available:
1. Every Versatile Thermostat climate entity is completely configured on its own. Choose this option, if you don't want to have any kind of central configuration or management.
2. Some aspects of Versatile Thermostat climate entities are configured centrally. This allows to e.g. define min/max temperature, open window detection,… at a central, single instance. For each climate entity you configure you can then choose to use the central configuration or to override them with custom settings.
3. All Versatile Thermostat climate entities are controlled with a single entity. This requires a central configuration, only some aspects (like the room temperature sensor) are specific to the climate entities. But everything else (target temperature, preset, climate mode) is controlled with the single entity.

In case this description is more or less correct, I suggest not only to put it into the documentation but also to update the config panel itself as currently it's very confusing ("control by central mode" versus "central main configuration"). Also, if there are only three options and not 4 (no central mode possible without central configuration), this shouldn't be two checkboxes but rather three radio items (or a dropdown).

**Comment by jmcollin78** [comment]
Correct. I will take that into future documentation.

Just one thing: a mode is a runtime way of working in my vocabulary and a configuration is to configure at rest (not in runtime). That is why a central configuration or a standalone configuration in not a mode.

But that is certainly only in my head.

Thanks for the head up !

**Comment by jmcollin78** [comment]
README have been updated here: https://github.com/jmcollin78/versatile_thermostat/blob/main/README.md#configuration

I will see to adapt the configuration box.

**Comment by maia** [comment]
Thanks. I totally agree, it's very hard to tell what is clear to everyone and what needs explanation.

**Comment by jmcollin78** [comment]
Release 5.2.1
