### ISSUE TITLE
resume from previous state

### ISSUE THREAD

**Issue by cyrildumas** [jmcollin78/versatile_thermostat#315]
Hello,
I have observed that the thermostat is taking some time before finding the correct setup in order to stabilize the temperature in the room at the target. Sometimes hours and sometimes more.
If at some point there is an update which needs a restart of home assistant, the thermostat will start all over again from the beginning. Since almost all addons request a restart and there is also home assistant core and OS. Well we frequently have to reboot HA ...
Can you maybe store in a file the state of the thermostat after each modification and use this file after a reboot in order to resume the regulation as if no reboot happened?
Thanks
Cyril

**Comment by jmcollin78** [comment]
Hello,

What is very annoying is that you don't respect the issue template. So try again with the template and I will answer.I have to check something on your configuration before answering.

**Comment by cyrildumas** [comment]
Hello Jean-Marc,
My apologies, I will do it again.
Regards
Cyril
