### ISSUE TITLE
make frost protection a central configuration and independent of presence

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#319]
I would like to suggest to move the "frost protection" to the central configuration, instead of having it twice with the presets (once normal, once with presence management). 

If I want a frost protection, I most likely want it at the same temperature for all rooms (e.g. 12°C) and also I doubt people will ever want to define different frost protection temperatures when away/preset.

**Comment by LennardPlay** [comment]
Good Idea. This already seems to be part of the new "central mode" entity.

**Comment by jmcollin78** [comment]
I agree (it is just more easier to not make a special case for the Frost protection preset). I consider all presets the same way but it doesn't make sense to have it for presence.

**Comment by maia** [comment]
@jmcollin78 I completely understand your motivation for keeping frost protection with the other presets and I value your continuous work. :)

**Comment by jmcollin78** [comment]
For now, I will not consider this enhancement. The idea was valuable and make sense but I got for now too much important think to do.
