### ISSUE TITLE
resume from previous state

### ISSUE THREAD

**Issue by cyrildumas** [jmcollin78/versatile_thermostat#325]
Hello,

**Is your feature request related to a problem? Please describe.**
I have observed that after a restart of home assistant the regulation of the room start again from the beginning which is the target temp indicated in the VT. The slave thermostat is configured back again with the target temp and the regulation can take few hours before finding again the correct temperature the slve thermostat has to have in order to have the target temp in the room. Since we have to reboot HA very frequently because of the different updates this is very annoying

**Describe the solution you'd like**
Maybe you can save the state of the VT on a local file after each order sent to the slave thermostat so that it can be resumed after a restart of HA

**Describe alternatives you've considered**
none

**Additional context**
My setup:
I have reversible air conditioning at home therefor I am using thermostat over climate. 4 splits are configured with medium self regulation and with expert mode like below

versatile_thermostat:
     auto_regulation_expert:
         kp: 0.4
         ki: 0.08
         k_ext: 0.0
         offset_max: 10
         stabilization_threshold: 0.1
         accumulated_error_threshold: 50

Regulation Threshold 1
Regulation minimal period 30

![image](https://github.com/jmcollin78/versatile_thermostat/assets/150172815/388bc7fd-6e02-4c18-9a24-51d2749e3dd6)

I hope this time I did it correctly.
Regards
Cyril

**Comment by jmcollin78** [comment]
Hello @cyrildumas ,

> I have observed that after a restart of home assistant the regulation of the room start again from the beginning which is the target temp indicated in the VT. 

This should not. The `accumulated_error` which is the parameter that controls the regulation is persistent.
You can check this by looking its value in the VTherm attributes after a reboot. It should be restored to its value after a reboot.

I cannot understand why you have such behaviour. Can you please add the EMA in the graph ?. When you restart the EMA is recalculated and maybe this is point.

**Comment by cyrildumas** [comment]
Hello Jean-Marc,

In my example, Chambre_Victoria, the regulation parameters are:
kp: 0.4
ki: 0.08
k_ext: 0.0
offset_max: 10
stabilization_threshold: 0.1
accumulated_error_threshold: 50

Before reboot, the accumulated error parameter for this climate equal 47.3 and after reboot 2.9 so it seems that the previous value was not restored. I am attaching the logs just in case but I did not see anything useful.
[home-assistant_2024-01-09T10-13-46.427Z.log](https://github.com/jmcollin78/versatile_thermostat/files/13872301/home-assistant_2024-01-09T10-13-46.427Z.log)

In regards to your second question, the graph is already using the EMA. This behavior is because I am using a broadlink universal remote including a temperature sensor. One of the only location I have in this room is in the direction of the air flux of the air conditioner hence the spike. I moved it.

![image](https://github.com/jmcollin78/versatile_thermostat/assets/150172815/d067c12f-88d6-43ce-8a5a-7a639278bde3)

Regards
Cyril

**Comment by jmcollin78** [comment]
The EMA is a entity that it is not displayed in your graph. 
If you look at the README, you have missed this part I guess (in the Plotly definition) :
```
    - entity: '[[climate]]'
      attribute: ema_temp
      yaxis: y1
      name: Ema
```

**Comment by cyrildumas** [comment]
For the graph, yes I saw it in the readme file, I just kept only the EMA and renamed it for my own convenience. See below
![image](https://github.com/jmcollin78/versatile_thermostat/assets/150172815/762d9c42-81ce-44e2-b2a9-f6713ed31927)

For the bug, if bug there is, I will help in anyway I can.
Regards
Cyril

**Comment by turbolooser** [comment]
Not sure but seems I am having the same issue. 
When i turn off my climate and then turn it on again it all starts from scratch. On reboot the same also.
Hopefully you find something

**Comment by jmcollin78** [comment]
Before restart:
```
current_temperature: 18.8
temperature: 17
is_regulated: true
ema_temp: 18.96
regulated_target_temperature: 14.5
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: -20.800000000000004
```

Just after restart of HA:
```
is_regulated: true
regulated_target_temperature: 17
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: 0
```

So I can confirm there is a bug. The regulation_accumulated_error have been restored.

**Comment by jmcollin78** [comment]
Found and fixed !

**Comment by cyrildumas** [comment]
Fantastic. Thank you very much Jean-Marc.

**Comment by jmcollin78** [comment]
You can have the fix in beta release here: https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.4.0-beta2

**Comment by cyrildumas** [comment]
I have tested it for few days and so far so good.

**Comment by jmcollin78** [comment]
Thank you for the feedback. I will try to release this week-end (I have another big change running)

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.4.1
