### ISSUE TITLE
climate with window state configured with sensor is *also* using the centrally configured slope detection, which it shouldn't

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#327]
One of my rooms does not use the temperature slope to detect open windows, as this room has a door sensor. I've configured this climate entity to use the door sensor:
<img width="577" alt="Bildschirmfoto 2024-01-08 um 19 14 36" src="https://github.com/jmcollin78/versatile_thermostat/assets/9836/a473c056-d061-4bbc-956e-e1265911b433">
<img width="578" alt="Bildschirmfoto 2024-01-08 um 19 14 55" src="https://github.com/jmcollin78/versatile_thermostat/assets/9836/eb40e7b2-d40c-4d9e-9b3a-729e953f3ad5">
Unfortunately the entity seems to *also* use the temperature slope detection I configured in the central config (which is used by all other rooms), as any time the slope falls drastically, the heating turns off (see upper two history charts in the image below). 

So besides the issue that the EMA calculation isn't yet working for me (see graphs below), the bug is that a climate entity configured to use a door sensor should *not* also use the central config.
<img width="1234" alt="Bildschirmfoto 2024-01-08 um 19 19 13" src="https://github.com/jmcollin78/versatile_thermostat/assets/9836/bc063279-5d6f-4115-9792-00e922382a63">

**Comment by jmcollin78** [comment]
Idem #324
