### ISSUE TITLE
Adaptation de la répartition de charge sur plusieurs radiateurs 

### ISSUE THREAD

**Issue by machintrucbidule** [jmcollin78/versatile_thermostat#330]
Hello, 

Si on met plusieurs radiateurs (over_switch) sur un même thermostat, la charge est repartie entre eux. Mais celle ci est repartie de façon égale entre les différents appareils, c'est ça ? 
Serait il possible de pouvoir configurer ceci, afin de pouvoir par exemple demander à ce que l'un soit plus utilisé que les autres ? Par exemple en permettant de spécifier un pourcentage d'utilisation pour chaque radiateur d'un même thermostat ?

**Comment by jmcollin78** [comment]
bonjour,

Ce n'est pas prévu. Quel est le cas d'usage exactement ? Ca fait beaucoup de configuration supplémentaire qu'il faudrait justifier.

**Comment by machintrucbidule** [comment]
Bonjour, l'idée est de pouvoir privilégier l'utilisation d'un radiateur plus efficace

**Comment by jmcollin78** [comment]
ok. Pas sur que je le fasse, on ne va pas se mentir. Ca reste qd même des cas très particuliers qui risque de complexifier la configuration pour tout le monde. je garde ouvert pour l'instant si beaucoup d'utilisateur sont intéressés.

**Comment by machintrucbidule** [comment]
Pas possible sinon que ça n'apparaisse pas dans la GUI (même priorité par défaut pour tous les équipements), et que ça se gère via un fichier de config ?

**Comment by jmcollin78** [comment]
Tout est possible avec du temps et de l'argent 😉 

Est-ce que tu sais développer sous HA ?

**Comment by machintrucbidule** [comment]
Haha 😁
Et non, j'ai jamais touché au code de HA ou ses intégrations. Mais si tu sais rapidement m'expliquer où trouver de la doc, et quelle partie du code de Versatile Thermostat gère ce que je souhaite modifier, je peux essayer de regarder

**Comment by jmcollin78** [comment]
Tu as un tuto complet fait par moi ici: https://hacf.fr/tag/developpement/

Ca peut aider pour démarrer. C'est un peu touchy qd même pour faire ça donc le conseil, ce n'est pas démarrer avec cette évol.

**Comment by danvy** [comment]
Il me semble que c'est le système de délestage d'une installation traditionnelle éventuellement couplée à des zones.
Dans vterm, cela revient à ne pas configurer le power management de certains thermostats (ils respecteront toujours leurs consignes) alors que les autres, avec power management vont s'éteindre en cas de surconsommation.

**Comment by jmcollin78** [comment]
Je clos ce sujet que je ne vais pas développer.
