### ISSUE TITLE
Versatile thermostat algo polué par un poële Pelets

### ISSUE THREAD

**Issue by Crapoto94** [jmcollin78/versatile_thermostat#332]
Bonjour tout le monde,
Je vous explique mon problème. 

Mon fils, handicapé, dispose dans sa GRANDE pièce de vie de :
- 1 radiateur contrôlé par un relais, le tout piloté par VTherm.
- 1 poêle à Pelets commandé par une app, utilisé je jour uniquement.

Le problème (je pense) est lié à l'apprentissage. 
En effet, en journée, le poêle fonctionne, et donc VTherm n'a pas besoin de faire beaucoup fonctionner le radiateur (en complément du poêle) car la majeur partie de la chaleur de la pièce est fournie par le poêle. 
Cette nuit, la température est descendue à 15 degrés, (Poêle OFF et Vtherm sur radiateur OK) alors que Vtherm était réglé sur 21 degrés.
J'ai remarqué que Vtherm demandait au radiateur un allumage de 1 minute 30 toutes les 15 minutes, ce qui est vraiment trop peu.
Je pense que c'est du au fait que Vtherm a appris comment piloter le radiateur quand le pôele fonctionne (de jour) mais que c'est pas le mode souhaité pour la nuit.

J'ai pensé à faire 2 Vtherm, 1 pour la nuit et un pour le jour, pour qu'ils disposent de leur apprentissage spécifique. 
Est-ce la bonne méthode ? Y-a-t-il une autre solution ?

Merci de vos éclairages et bonne journée.

**Comment by jmcollin78** [comment]
Dommage de ne pas avoir respecté le template et notamment sur les attributs de ton VTherm, j'aurai pu répondre du 1er coup.

Tout ce que je peux dire, c'est qu'il n'y a pas "d'apprentissage" pour les radiateurs pilotés par des relais (over_switch je suppose donc).

Tout est recalculé à chaque cycle. J'ai moi même un poële à bois qui tourne la journée et pas la nuit. Je ne constate pas ton soucis. Il y a autre chose qui ne va pas et j'ai besoin des attributs de ton VTherm pour tenter d'y voir plus clair (au moment ou ça devrait chauffer et que ça ne chauffe pas). Idéalement, il me faudrait aussi les courbes de températures comme indiquées dans le README (chercher Plotly).
