### ISSUE TITLE
Cannot enter external coefficient value under 0.1 in configuration UI with the keyboard

### ISSUE THREAD

**Issue by teeten** [jmcollin78/versatile_thermostat#337]
Home Assistant version : Core = 2023.12.3, Frontend = 20231208.2
Versatile Thermostat version : 5.2.2
Using the UI on macOS with Chrome (latest versions)

The issue happens when configuring a "switch mode" thermostat, when typing a value starting with 0.0 (such as 0.03 for example). Behavior is difficult to describe exactly, but it seems that when the second character is '.' and the third is '0', the next digit input resets the field content.

To enter 0.03, I have to paste the value copied from a text editor, or I have to enter 1.13 and then replace the '1's with '0's.

<img width="338" alt="image" src="https://github.com/jmcollin78/versatile_thermostat/assets/24637509/c60291d5-19a4-44d5-b476-92644fb1c8a6">

**Comment by jmcollin78** [comment]
This is a bug in the UI which is not controlled by the integration, you should type number without the . and go back and type the dot after as a workaround.

**Comment by teeten** [comment]
😮
