### ISSUE TITLE
Régulation trop fréquente (over_valve)

### ISSUE THREAD

**Issue by Thejul67** [jmcollin78/versatile_thermostat#338]
Bonjour,

Tout d'abord un grand merci pour cette intégration.
J'ai cependant un petit problème avec la fonction over_valve.

## Version of the custom_component
5.2.2

## Describe the bug
En effet j'ai des tètes thermostatiques de type Eurotronic Zwave qui sont donc sur piles , le but étant évidement d'économiser au maximum les piles.
Le soucis c'est que versatile thermostat envoie très  souvent des modification minimes d'ouvertures de valve (parfois toutes les 30 secondes) ce qui fait fondre la batterie de la tete en quelques jours.

Je ne comprends pas le soucis car j'ai bien réglé le minimal_activation_delay_sec sur 600s

Voici la configuration du thermostat :
## Configuration
hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 35
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
friendly_name: Versatile Thermostat WC
supported_features: 17
current_temperature: 20.1
temperature: 20
hvac_action: heating
preset_mode: none
is_on: true
hvac_mode: heat
is_controlled_by_central_mode: false
frost_temp: 1
eco_temp: 15
boost_temp: 28
comfort_temp: 21
frost_away_temp: 7
eco_away_temp: 7
boost_away_temp: 7
comfort_away_temp: 7
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: -3.4
ac_mode: false
saved_preset_mode: none
saved_target_temp: 20
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
security_delay_min: 80
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-01-14T10:47:25.702514+01:00"
last_ext_temperature_datetime: "2024-01-14T10:44:09.352804+01:00"
security_state: false
minimal_activation_delay_sec: 600
device_power: 1
mean_cycle_power: 0.2
total_energy: 0
last_update_datetime: "2024-01-14T10:47:27.035322+01:00"
timezone: Europe/Paris
window_sensor_entity_id: binary_sensor.fenetrewc_contact
window_delay_sec: 15
window_auto_enabled: false
temperature_unit: °C
is_device_active: true
ema_temp: 20.21
valve_open_percent: 20
is_over_valve: true
underlying_valve_0: number.thermostatwc_valve_control
on_percent: 0.2
on_time_sec: 0
off_time_sec: 2700
cycle_min: 45
function: tpi
tpi_coef_int: 0.3
tpi_coef_ext: 0.01

En pieces jointe les evenement sur les vannes (toutes les 30s) ainsi que les logs
[home-assistant_versatile_thermostat_2024-01-14T10-35-41.108Z.log](https://github.com/jmcollin78/versatile_thermostat/files/13931127/home-assistant_versatile_thermostat_2024-01-14T10-35-41.108Z.log)

Merci par avance pour votre aide
![thermostat](https://github.com/jmcollin78/versatile_thermostat/assets/7628556/77a1d8da-afa2-49c6-aa4b-7b38d96b482a)

**Comment by Thejul67** [comment]
Je pense (en partie) savoir pourquoi il y a de telles variations 
Mes capteurs de températures remontent très régulièrement les temperatures : A chaque variation de température versatile thermostat réajuste la puissance en % ..

Est-il possible de limiter la régulation  en suivant strictement le minimal_activation_delay_sec  ? (Ici toutes 600 s soit 10min)
Encore mieux : rajouter un offset de temperature au delà du quel le  minimal_activation_delay_sec  est ignoré 


Cordialement

**Comment by jmcollin78** [comment]
Hello @Thejul67 ,

> Est-il possible de limiter la régulation en suivant strictement le minimal_activation_delay_sec ? (Ici toutes 600 s soit 10min)
Encore mieux : rajouter un offset de temperature au delà du quel le minimal_activation_delay_sec est ignoré

Ces 2 paramètres existent en mode `over_climate` avec l'auto-regulation d'activée pour exactement le cas que tu décris.
Comme il n'y a pas d'auto-regulation sur les valves (c'est l'algo TPI qui fait le job), je n'ai pas reporté ces paramètres.

Le minimal_activation_delay n'est pas un paramètre adapté pour faire ce que tu veux faire. Il conditionne le temps en sec minimal pour activer un switch. Mais il ne sert pas pour les valves pour lesquels on donne juste un % d'ouverture. (cf. tableau des paramètres). Donc ca va commander a chaque cycle (45 min -> c'est très très long) ou à chaque remontée de température qui adapte le % d'ouverture.

Il me faut en effet, un mécanisme identique et pourquoi pas utiliser ce paramètre en effet pour les valves.

Je vais regarder ça en priorité (mais j'ai plein de modifs sur le feu, donc va falloir être un peu patient).

Ce que tu peux faire en attendant :
1. mettre un VTherm `over_climate` par dessus le VTherm `over_valve` avec l'auto-régulation. Là tu pourras spécifier les 2 paramètres qui te manque. C'est un peu l'empilement mais ca va marcher.
2. tu devais avoir un climate fournit avec l'intégration d'origine. Tu peux mettre un VTherm `over_climate` sur ce climate et activer aussi l'auto-régulation avec les fameux 2 paramètres.

C'est 2 solutions vont permettre d'attendre un peu (1 mois environ, je pense).

**Comment by jmcollin78** [comment]
Will be available for test in a beta release: https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.4.0-beta1

I hope you will be able to give it a try because I've got no TRV at home to test in real life. You will find 2 new parameters in the configuration for `over_valve`:

![Capture d’écran 2024-01-21 à 19 44 13](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/ea1c3ee5-7a06-4c00-ae8b-a4810f47d39f)

In the example, if the delta percent is less than 10% new regulation is not sent and if the delta time (between last sent) is < 5 min the new open percent is not sent also.

Let me know please, if it works.

**Comment by fredericseiler** [comment]
Tested on 10 shelly TRVs with temperature sensors from different brands, I confirm that it works really well.

![2024-01-23-22-38-02 Google Chrome Historique – Home Assistant](https://github.com/jmcollin78/versatile_thermostat/assets/954168/bd6fefcb-e25c-4bc6-baeb-81da036eaab5)

Thanks @jmcollin78 !

**Comment by jmcollin78** [comment]
Thank you for your feedback @fredericseiler  ! I will release this week-end.
