### ISSUE TITLE
Retour log

### ISSUE THREAD

**Issue by prodoff** [jmcollin78/versatile_thermostat#344]
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.versatile_thermostat.commons
Source: custom_components/versatile_thermostat/commons.py:125
Integration: Versatile Thermostat configuration (documentation, issues)
First occurred: 20:05:56 (12 occurrences)
Last logged: 20:05:56

<entity sensor.thermostat_shelly_energy=unknown> - no entity to listen. Try later
<entity sensor.thermostat_shelly_mean_power_cycle=unknown> - no entity to listen. Try later
<entity sensor.thermostat_shelly_power_percent=unknown> - no entity to listen. Try later
<entity sensor.thermostat_shelly_on_time=unknown> - no entity to listen. Try later
<entity sensor.thermostat_shelly_off_time=unknown> - no entity to listen. Try later

**Comment by jmcollin78** [comment]
At startup this can be normal. Else that means the the switch configured or the climate doesn't exists or be alive.

This is not an issue of VTherm but an issue in your configuration or environment.
