### ISSUE TITLE
Target Temp at Specified Time

### ISSUE THREAD

**Issue by kadaan** [jmcollin78/versatile_thermostat#35]
**Is your feature request related to a problem? Please describe.**
It is suggested to use an external scheduling component to schedule temperature changes for the thermostat.  That is great, but it would be ideal to be able to set a schedule (ie. 7am 69f, 9pm 66f) and have the thermostat choose when enable heating/cooling such that it attempts to reach the target temperature at the specified time.

**Describe the solution you'd like**
I would like to be able to configure a schedule (ie. 7am 69f, 9pm 66f), have the thermostat account for internal temperature, external temperature, and historical heating/cooling metrics, and use this information to enable heating/cooling earlier than the scheduled time.  The goal is that the internal temperature reaches that set point at the scheduled time (ie. 6am for a 7am 69f schedule), rather than the set point being changed at the target time and then the thermostat needs to catch up.  This is especially important for systems which take a while to reach the target temperature (ie. heat pumps).

**Describe alternatives you've considered**
An external scheduling component may work, but it will need a much of the logic of a thermostat to be able to accomplish this.

**Additional context**

**Comment by jmcollin78** [comment]
I understand but I really have no idea on how to implement this.
I use scheduler to switch preset temperature (and this can be done for temperature also) but I don't known to switch something BEFORE the scheduler switch.
