### ISSUE TITLE
Central Configuration Switch

### ISSUE THREAD

**Issue by adi90x** [jmcollin78/versatile_thermostat#358]
Hello,

Il me semble que le switch de configuration central permettant de basculer l'ensemble des vtherm n'est pas updaté lorsque un vtherm est modifié.
Exemple : J'utilise le central mode pour basculer l'ensemble des vtherm sur Hors-Gel, aucun problème, en revanche si après je rebascule un vtherm sur un autre preset, la config centrale devrait switcher sur ``auto`` au lieu de rester sur ``Frost Protection`` non ?

Encore bravo pour tout ces développements !
Adrien

**Comment by jmcollin78** [comment]
Hello @adi90x, it was done on purpose. If you have chosen to go on vacation by putting all your VTherms on Frost Protection, you don't want the scheduler to put your VTherm into heating mode. I'm sure, you don't want.

So in Frost protection central mode, you cannot change VTherm manually. You have to switch the central mode to Auto.

**Comment by adi90x** [comment]
Ok, a bit strange but I understand the logic !
In that case it should put any vtherm manually change back to Frost right ?
( maybe I didn't wait enought)

Regards,
Adrien

Le lun. 22 janv. 2024, 19:03, Jean-Marc Collin ***@***.***> a
écrit :

**Comment by jmcollin78** [comment]
Je vais le refaire en Français du coup. Le changement de central mode ne peut se faire que manuellement. C'est une décision de l'utilisateur qui sait ce qu'il fait.
Si le scheduler en changeant un VT repasse tous tes radiateurs en auto pendant que tu es en vacances, tu ne seras pas content, je pense.

Moi vivant, il n'y aura pas de mise à jour automatique du central mode dans le dos de l'utilisateur. C'est totalement contraire à l'objectif de ce central mode.

**Comment by adi90x** [comment]
Bien compris, mais du coup si tu passes manuellement un vtherm en heat, et
que ton central est en Frost, est ce que ton vtherm ne devrait pas être
remis en Frost pour être aligné avec le central ?


Cordialement
Adrien

Le lun. 22 janv. 2024, 19:25, Jean-Marc Collin ***@***.***> a
écrit :

**Comment by jmcollin78** [comment]
Je pense que ça ne marche pas si tu changes le preset d'un VTherm alors que le central est bloqué sur Hors gel. Mais peut être que je vais retester si ça marche bien. Je suis d'accord avec toi que ce que tu décris peut être vu comme un état incohérent.

**Comment by jmcollin78** [comment]
Bon je viens de tester et en effet, on peut changer le preset alors que le central mode est Hors-gel. Il me semblait l'avoir fait et tester. Je vais réfléchir un peu pour savoir ce qui est le mieux.

Qu'elle est ta position ? Est-ce que je devrais refuser le chgt ou est-ce que je dois laisser la possibilité à l'utilisateur de le faire ?
(sachant que quand tu vas remettre le central mode en Auto, ca va écraser le choix de l'utilisateur).

Exemple:
- le vtherm est Eco,
- tu mets central mode a Hors gel,
- tu changes le VTherm en Comfort,
- tu remets le central mode sur Auto,
- -> ca remet le VTherm en Eco (l'état d'avant le changement du central mode)

**Comment by adi90x** [comment]
Le deux possibilités semblent cohérente, soit on empêche l'utilisateur de
basculer un vtherm si central est en Frost, alors on garde forcé en Frost,
ou alors on laisse l'utilisateur potentiellement modifier et on remet
l'état lorsque l'on repasse en auto.

J'ai juste peur que la deuxième possibilité, crée pas mal de problèmes si
l'on a plusieurs vtherm tous modifié manuellement alors que central est en
Frost cela peut amener à des situations assez illogique pour le user ( même
si explicable)

J'aurais donc tendance à privilégier la première solution : tant que
central est en Frost aucun vtherm ne peut être sur autre chose non ?


Cordialement,
Adrien

Le mar. 23 janv. 2024, 09:54, Jean-Marc Collin ***@***.***> a
écrit :

**Comment by jmcollin78** [comment]
Oui c'est aussi mon point de vue. et faut bloquer les chgts auto par un schedule. Sinon on v reactiver les VTherms alors qu'on est en congés. Je pensais l'avoir fait comme ça d'ailleurs.

**Comment by jmcollin78** [comment]
Merged: https://github.com/jmcollin78/versatile_thermostat/pull/445

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.2.2
