### ISSUE TITLE
Problem wiith driven entity  Versatile Thermostat

### ISSUE THREAD

**Issue by pgiulio** [jmcollin78/versatile_thermostat#371]
### Discussed in https://github.com/jmcollin78/versatile_thermostat/discussions/370

<div type='discussions-op-text'>

<sup>Originally posted by **pgiulio** February  1, 2024</sup>
I want to eliminate soft on and off. I want the heating activation to always remain active until the set point is reached. Now the output continues to turn on and off every 20 minutes.

![image](https://github.com/jmcollin78/versatile_thermostat/assets/75814425/00a0d3cb-8735-4d74-a757-c2a82759ff78)
</div>

**Comment by jmcollin78** [comment]
Already in discussion. Please do not duplicate issues (and this is really not an issue but the main feature of VTherm).
