### ISSUE TITLE
Preheat schedule

### ISSUE THREAD

**Issue by FireFury0** [jmcollin78/versatile_thermostat#376]
On the thermostat hardware that I am replacing with Home Assistant, the heating schedule set the time that the room should be at the target temperature, rather than the time that the heating would come on.  The thermostat would calculate how early to start heating, based on the current temperature, target temperature and (optionally) outdoors temperature.

i.e. if you set it to be 19° at 09:00, the thermostat would calculate that it would take 25 minutes to raise the temperature from the current temperature to 19°, and therefore start heating at 08:35.

Versatile Thermostat doesn't have a built in scheduler and I am using Scheduler Component to automatically change the preset between "Frost" and "Comfort".  I don't think its possible to achieve a similar "preheat" adjustment to the schedule since the scheduler and thermostat are independent of each other.

Manually setting the heating to start at a fixed time means that the target temperature is reached too early in warm conditions, or too late in cold conditions.

**Comment by jmcollin78** [comment]
Hello, yes. I confirm this is not possible yet. This has been asked many times but I have no solution.
So why do you consider it is an issue of VTherm ?
