### ISSUE TITLE
Erreur Home assistant

### ISSUE THREAD

**Issue by prodoff** [jmcollin78/versatile_thermostat#388]
Bonjour
J'ai Le message d'advertisement suivant dans Home assistant
Pouvez vous m'aider ?

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Thermostat (documentation, issues)
First occurred: 14:47:20 (1 occurrences)
Last logged: 14:47:20

Entity None (<class 'custom_components.versatile_thermostat.thermostat_switch.ThermostatOverSwitch'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/jmcollin78/versatile_thermostat/issues

**Comment by jmcollin78** [comment]
Hello @prodoff ,

This is just a warning due to recent changes in the Climate entity in HA. I will fix that in a future release. You can safely ignore it.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.0.1
