### ISSUE TITLE
shedding not checking if there is enough free power to start

### ISSUE THREAD

**Issue by R00S** [jmcollin78/versatile_thermostat#391]
version: 5.4.2

We only have 13A for 3 heaters and a couple of other stuff.
I am trying to get versatile_thermostat not to exceed a maximum power consumption not to make the fuse blow. However, instead of checking if there is enough power available before starting a heater it starts up och then goes into shedding only if it exceeds my maximum value. Would it be possible to make it check before starting instead?

**Comment by jmcollin78** [comment]
Hello @R00S 

Why don't you follow the issue template ? It would have been much easier for me to answer.

**Comment by jmcollin78** [comment]
The shedding works as you want: it checks before starting a device that power is available. There is some conditions for this to work and I need your VTherm attributes to answer.

**Comment by R00S** [comment]
Thanks for the reply!
Sorry, i didm't even understand where in the template i was supposed to write something. I may have been very tired...

I'll try to remove my central configuration. Hopefully, i may be able to create a vtherm after that. Right now there is no vtherm option when i press Add device.

**Comment by jmcollin78** [comment]
> Sorry, i didm't even understand where in the template i was supposed to write something. I may have been very tired...

When you create an issue, you have to follow a template: give VTherm attributes, ....
