### ISSUE TITLE
Automatic switching even if the power is 0% to dry towels or mantain temperature on floor heating

### ISSUE THREAD

**Issue by diegoflyer** [jmcollin78/versatile_thermostat#400]
The idea is to have that if the heat is not activa for more than x  minutes (parameter) the heat will be anyway switched on for y minutes (parameter).
This is to dry towels (on bath heather that usually are supporting towels) or mantain temperature on floor heating.
To avoid overheating if the thermostat remain active also in summer this funcion should be bypassed when:
1. General mode is Summer!
2. The temperature is z °C (parameter) more than the setpoint.

**Comment by jmcollin78** [comment]
Too much complexity for a questionable feature. Almost 4 new parameters.
I think I will not do that.

**Comment by diegoflyer** [comment]
Ok @jmcollin78  understand, do you think that if I check with an automation and activate the switch "behind" the thermostat (if the time from last switch is more than xx minutes) than the thermostat should manage the switch off after the minimum time as per parameter?

**Comment by jmcollin78** [comment]
Yes, if you activate the switch behind the Vtherm, it will turn it off at each cycle.
