### ISSUE TITLE
Target Temperature changes and nothing is seen in the history

### ISSUE THREAD

**Issue by jebeke65** [jmcollin78/versatile_thermostat#402]
-->

## Version of the custom_component
latest
-->

## Configuration (below script)

Below is the script I'm using to set the temperature.

alias: Climate Beneden - comfort
sequence:
  - if:
      - condition: state
        entity_id: climate.veranda_clima_smart
        state: "off"
    then:
      - service: climate.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: climate.veranda_clima_smart
  - service: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: heat
    target:
      entity_id: climate.veranda_clima_smart
  - service: climate.set_temperature
    metadata: {}
    data:
      temperature: 21
      hvac_mode: heat
    target:
      entity_id: climate.veranda_clima_smart
mode: single

My VTherm attributes are the following:
hvac_modes: heat_cool, heat, dry, fan_only, cool, off
min_temp: 15
max_temp: 26
target_temp_step: 0.5
fan_modes: auto, speed 1, speed 2, speed 3, speed 4, speed 5, speed 6
preset_modes: none, eco, comfort, boost
swing_modes: off, vertical, horizontal, both
current_temperature: 20.6
temperature: 21
fan_mode: auto
preset_mode: none
swing_mode: horizontal
is_on: true
hvac_action: null
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 0
eco_temp: 18
boost_temp: 24
comfort_temp: 21
frost_away_temp: 26
eco_away_temp: 26
boost_away_temp: 26
comfort_away_temp: 26
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 2.5
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 21
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 1
security_default_on_percent: 1
last_temperature_datetime: 2024-03-08T08:31:40.938823+01:00
last_ext_temperature_datetime: 2024-03-08T08:25:17.321711+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 2
mean_cycle_power: null
total_energy: 0
last_update_datetime: 2024-03-08T08:31:40.941632+01:00
timezone: Europe/Brussels
temperature_unit: °C
is_device_active: true
ema_temp: 20.45
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.veranda_3
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
auto_fan_mode: auto_fan_medium
current_auto_fan_mode: auto_fan_medium
auto_activated_fan_mode: null
auto_deactivated_fan_mode: auto
auto_regulation_use_device_temp: false
friendly_name: Veranda Clima Smart
supported_features: 441

## If it is releveant to regulation performance or optimisation some curves are needed
To have a great curves demonstrating what you think is a problem, please install and configure what is described here: [Even better with Plotly to tune your Thermostat](#even-better-with-plotly-to-tune-your-thermostat)

## Describe the bug
In the morning, I'm calling the script to set the temperature. I do see the 21 degrees being set, but then arbitrarily, the target temperature is set to 16 degrees, which I then have to correct manually.

I'm trying to:
set the target temperature with a script

And I expect:
the target temperature not to change

But I observe this ....
target temperature is changed at a later time (sometimes after 5min, sometimes after 30min), sometimes once, sometimes twice.

## Debug log
Before uploading the log (it can be quite big as I have a lot of stuff in home assistant, I want to check if I need to cut/paste certain things from the logging ?

**Comment by jmcollin78** [comment]
Hello, can you please format code au json with the <> formatter button. Else it is very difficult to read.

**Comment by jmcollin78** [comment]
Because you have an `over_climate` VTherm type, I guess this is the underlying climate which is changing itself. I talk about the `climate.veranda_3` one. And because VTherm is following the underlying to reflect the current state, you see VTherm switching.

What is this climate brand ? Is there any embedded automation or something like this with this thermostat ? Look for this way this is the only explanation possible.

**Comment by jebeke65** [comment]
Climate brand : Fujitsu 
I do not see any changes in the climate history of the Fujitsu :/

**Comment by jebeke65** [comment]
Sorry for the late reply. 
when I set the target temp on versatile thermostat i see the underlying climate going offline although it is still reachable in the climates app. 
if I change the target temp in the app, then it does not return to the lower target temp. 
If the underlying climate is going offline, what happens then when it comes back online in the versatile thermostat? I would expect it to resend the wanten target temp ?

**Comment by jebeke65** [comment]
@jmcollin78 Can you reopen please ?

**Comment by jmcollin78** [comment]
> Sorry for the late reply. when I set the target temp on versatile thermostat i see the underlying climate going offline although it is still reachable in the climates app. if I change the target temp in the app, then it does not return to the lower target temp. If the underlying climate is going offline, what happens then when it comes back online in the versatile thermostat? I would expect it to resend the wanten target temp ?

This seems so strange that I wonder if your Fujitsu is compatible with VTherm. There is sometime some specificities that prevent Vtherm to work normally. I think you are in that case.
The only to be sure is to give me some logs when the problems occurs as claimed 2 weeks ago.
