### ISSUE TITLE
Message d'erreur dans home assistant

### ISSUE THREAD

**Issue by prodoff** [jmcollin78/versatile_thermostat#420]
Bonjour

J'ai les messages d'erreur suivant dans home assistant depuis la mise à jour 2024.3.2

**premier message :**
`Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.versatile_thermostat.prop_algorithm
Source: custom_components/versatile_thermostat/prop_algorithm.py:59
intégration: Versatile Thermostat configuration (documentation, problèmes)
S'est produit pour la première fois: 13:02:55 (1 occurrences)
Dernier enregistrement: 13:02:55

Proportional algorithm: calculation is not possible cause target_temp or current_temp is null. Heating/cooling will be disabled`

**Second message :**
`Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.versatile_thermostat.number
Source: custom_components/versatile_thermostat/number.py:115
intégration: Versatile Thermostat configuration (documentation, problèmes)
S'est produit pour la première fois: 13:02:55 (4 occurrences)
Dernier enregistrement: 13:02:55

Thermostat Shelly - configuring Number non central, non AC, non AWAY for preset frost_temp
Thermostat Shelly - configuring Number non central, non AC, non AWAY for preset eco_temp
Thermostat Shelly - configuring Number non central, non AC, non AWAY for preset comfort_temp
Thermostat Shelly - configuring Number non central, non AC, non AWAY for preset boost_temp`

**3ème message:**
`Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.versatile_thermostat.number
Source: custom_components/versatile_thermostat/number.py:143
intégration: Versatile Thermostat configuration (documentation, problèmes)
S'est produit pour la première fois: 13:02:55 (4 occurrences)
Dernier enregistrement: 13:02:55

Thermostat Shelly - configuring Number non central, non AC, AWAY for preset frost_away_temp
Thermostat Shelly - configuring Number non central, non AC, AWAY for preset eco_away_temp
Thermostat Shelly - configuring Number non central, non AC, AWAY for preset comfort_away_temp
Thermostat Shelly - configuring Number non central, non AC, AWAY for preset boost_away_temp`

Merci pour votre aide

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.0.2
