### ISSUE TITLE
No longer able to edit preset temperatures

### ISSUE THREAD

**Issue by FireFury0** [jmcollin78/versatile_thermostat#439]
Previously I was able to change my preset temperatures, but this does not work any more.

Go to:
Settings -> Devices & Services -> Versatile Thermostat configuration

Click CONFIGURE next to one of the devices.  A menu of configuration items pops up.

Click "Presets" and a box pops up with a single "Use central presets configuration" checkbox.  The checkbox is unticked (which is correct).  Click SUBMIT and the box disappears.  Nothing pops up allowing the presets themselves to be configured.

**Comment by jezzaaa** [comment]
You need to configure presets through the "service"  and not the "device".

Try going to Settings -> Integrations -> Versatile Thermostat -> "1 service"

alternatively go to Settings -> Devices -> <name of thermostat>

**Comment by FireFury0** [comment]
Thanks. My Frost preset is set to 5c, but when I select frost in the versatile thermostat card it sets my heating to 15c (which is the Comfort preset).

**Comment by jmcollin78** [comment]
Hello @FireFury0 ,

Please read documentation about the 6.0 release. This have change.
