### ISSUE TITLE
Thermostat over climate, cannot use climate device's current temperature as temperature sensor

### ISSUE THREAD

**Issue by jezzaaa** [jmcollin78/versatile_thermostat#440]
When I create a new "Thermostat over a climate" device/service, I must choose a temperature sensor. My real thermostat (ZigBee controller for a gas-powered heater) is entity climate.heater. The thermostat has a temperature sensor, reported as attribute "current-temperature" in the climate entity. I'm unable to select this as the temperature sensor.

When selecting the source for "Room Temperature" I would like to be able to choose the underlying climate device and have Versatile Thermostat use the number from the current_temperature attribute. Ideally, for a thermostat-over-client device, the underlying climate device would be the default source for room temperature.

**Comment by jmcollin78** [comment]
Hello @jezzaaa ,

I will transform this into a discussion, as it is really not an issue but more a question.
