### ISSUE TITLE
Thermostat commands to heat despite target temperature exceeded

### ISSUE THREAD

**Issue by Kriss1670** [jmcollin78/versatile_thermostat#449]
As shown on screenshots, my thermostat commands heating despite target temperature exceeded. 
![IMG_9212](https://github.com/jmcollin78/versatile_thermostat/assets/80743001/1a28e4a7-d004-4fae-9104-99eaa2f55aa0)
I use a central configuration with default TPI values. Each radiator is commanded by a switch to send a signal to change from OFF or NORMAL (Fil pilote).

**Comment by Kriss1670** [comment]
Doing some testing... maybe some automation interfering.

**Comment by jmcollin78** [comment]
Hello @Kriss1670 ,

See in the Troubleshoot section of the readme. You will have some clues to troubleshoot this "common" case.

**Comment by Kriss1670** [comment]
Bonjour Jean-Marc,

Merci pour la réponse mais les paramètres TPI étaient ceux d'origine. Je pense qu'il y avait une interaction avec une automatisation que je viens de supprimer (elle est inutile avec la gestion des ouvrants de l'intégration). J'ai également supprimé la configuration centrale et le thermostat lié pour tout re-paramétrer en partant de zéro. Ca a l'air de très bien fonctionner depuis hier et je vais clore l'issue.

Désolé pour le désagrément et merci pour ton implication.
________________________________
De : Jean-Marc Collin ***@***.***>
Envoyé : lundi 22 avril 2024 08:09
À : jmcollin78/versatile_thermostat ***@***.***>
Cc : Kriss1670 ***@***.***>; Mention ***@***.***>
Objet : Re: [jmcollin78/versatile_thermostat] Thermostat commands to heat despite target temperature exceeded (Issue #449)


Hello @Kriss1670<https://github.com/Kriss1670> ,

See in the Troubleshoot section of the readme. You will have some clues to troubleshoot this "common" case.
