### ISSUE TITLE
Using VT as Diyless Opentherm controller

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#451]
### Discussed in https://github.com/jmcollin78/versatile_thermostat/discussions/450

<div type='discussions-op-text'>

<sup>Originally posted by **johnbur1** April 22, 2024</sup>
Hi, I currently use VT central boiler to switch a Shelly relay to control the boiler on/off. To avoid too much modulating, I would really like to control the boiler by OpenTherm instead.
I have purchased one of these:
[https://diyless.com/product/opentherm-thermostat2#connection]
Before I start trying to work it out, has anyone got the two integrations working together already?
</div>

**Comment by tbrasser** [comment]
Probably we can be smart about how to control the central boiler thermostat: weighted average instead of the highest one. Or also have "use temperature of underlying" on central boiler for people who cannot set an external sensor to use as "current temperature".

**Comment by jmcollin78** [comment]
Thank you for this valuable proposal but I'm not able to do that (too much important work to do now).
