### ISSUE TITLE
In central configuration, "use window detection" seems broken.

### ISSUE THREAD

**Issue by tomtom13** [jmcollin78/versatile_thermostat#463]
It's pretty simple:
in central configuration, when selecting "use window detection" and hitting submit - it ignored it, and instead it selects "use motion detection"

<img width="582" alt="Screenshot 2024-05-20 at 15 59 27" src="https://github.com/jmcollin78/versatile_thermostat/assets/22304458/a42a8ebd-3a53-47e6-98b5-853a5d8acaf6">

**Comment by jmcollin78** [comment]
Will try to reproduce.

**Comment by Ra72xx** [comment]
For me it's a bit different - I can't get rid of the checked "use motion detection". Whenever I get back to central configuration, motion detection is again activated. Checking and unchecking "window detection" seems to work.

**Comment by jmcollin78** [comment]
Duplicate of #514  which will bee fixed in 6.3.0
