### ISSUE TITLE
Warning message skipping self régulation 

### ISSUE THREAD

**Issue by jsapede** [jmcollin78/versatile_thermostat#488]
Got a recurrent warning message in thé logs : 

_Temporarily skipping the self-regulation algorithm while the configured sensor for room temperature is unavailable_

I've set a thermostat over thermostat for a climate control (Daikin + faikin esp control module)

The faikin esp provides ambient température measurement from a bluetooth sensor witch in available in HA through mqtt

I got an external zigbee température measurement also

Ha is in  latest version and also versatile thermostat 

I dont really understand where IS the  problem as the warning message states a room température sensor unavailable that is provided by the faikin card with mqtt

**Comment by 2fst4u** [comment]
I'm getting the same as of yesterday. It might be related to the recent HA update?

**Comment by jmcollin78** [comment]
Hello @jsapede ,

I don't have any issue like that. Can you please post here the sensor entity configured in VTherm and its value from Dev Tools / State please.

**Comment by jsapede** [comment]
How to do ? What do you need exsctly ?

**Comment by jmcollin78** [comment]
In the VTherm configuration check what is the entity configured to obtain the temperature and give me the value in Dev Tools / State.

Something like that:
![Capture d’écran 2024-08-14 à 08 20 56](https://github.com/user-attachments/assets/4de53311-8ed1-4d3a-83d5-14ae90db604f)

![Capture d’écran 2024-08-14 à 08 21 41](https://github.com/user-attachments/assets/a4a8c458-5fd8-42f8-8a3e-5675ad8ab1d0)

**Comment by jmcollin78** [comment]
I want to be sure the temperature sensor is not available as explained by the log message.

**Comment by jmcollin78** [comment]
In the screen copy all is working fine I guess. Do you still have the error ?

**Comment by jsapede** [comment]
yes its working on the screenshots
this morning a reloaded the integration and got the same message : 

![image](https://github.com/user-attachments/assets/06f18aa9-3b42-4c15-9e62-f57aecd48ef5)

**Comment by jsapede** [comment]
since a i rechecked this morning i got a new error 

![image](https://github.com/user-attachments/assets/da7e8480-bc9f-444c-b4a4-8d9cf8d337d2)

i dont know where it comes form since i have no 5.0 settings 

![image](https://github.com/user-attachments/assets/7df9fd0b-2067-4394-9f46-0bcd3d4c964a)

![image](https://github.com/user-attachments/assets/89a7cba0-3d2b-40ec-b797-eb347998f491)

**Comment by jmcollin78** [comment]
Hello @jsapede ,

You are running into this issue (due to HA 2024.8): https://github.com/jmcollin78/versatile_thermostat/issues/489

The solution is in this issue (change the min temperature allowed in VTherm configuration).

**Comment by jmcollin78** [comment]
> yes its working on the screenshots this morning a reloaded the integration and got the same message :
> 
> ![image](https://private-user-images.githubusercontent.com/66303110/359858026-06f18aa9-3b42-4c15-9e62-f57aecd48ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzMwMjYsIm5iZiI6MTcyNDMzMjcyNiwicGF0aCI6Ii82NjMwMzExMC8zNTk4NTgwMjYtMDZmMThhYTktM2I0Mi00YzE1LTllNjItZjU3YWVjZDQ4ZWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEzMTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0N2Q2ZWFmMWM1Y2ZmNTMzNjk4ODE4MGU5NjZhOTYzMzNhZjg2NzJjNmMxODhmNjA1OGEwYzI1ZTQwZjBiNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nx_9LE2qRvlvf5005cTtJKrCj5MBj-PXFeY0tlhMPFE)
> 
> the sensor is available :
> 
> ![image](https://private-user-images.githubusercontent.com/66303110/359858908-4463126c-5802-42e5-a68f-ab11d012cd0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzMwMjYsIm5iZiI6MTcyNDMzMjcyNiwicGF0aCI6Ii82NjMwMzExMC8zNTk4NTg5MDgtNDQ2MzEyNmMtNTgwMi00MmU1LWE2OGYtYWIxMWQwMTJjZDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEzMTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MzQyYTJjNGQ2ZDc0MzA2MzVjMzViNjUwZGNkYzc0ZjljZDVhYjAwNDNlOTVhMzZhM2M5NWE2NjVjNjRjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mq7SQ5nsdSEufc8D409ykfyqPZ50jLpk7OL1M26ggvU)
> 
> but everytime a reload the integration i got the error message

What is possible is that you have this only at startup. This is possible if your thermostat device is started AFTER the VTherm. 
If it is only at startup, you can safely ignore this message.

**Comment by jmcollin78** [comment]
Please give a try to https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.3.4. It fixes and improve the behavior. I wish you will not see this message (only on startup as explained above).

**Comment by jmcollin78** [comment]
Closing because of stale. Don't hesitate to reopen if needed.
