### ISSUE TITLE
Door sensor timeout

### ISSUE THREAD

**Issue by MaxWaldorf** [jmcollin78/versatile_thermostat#490]
Since v6, there seems to be a change of behavior in sensor timeout.

I happen to leave door open all night to refresh a room and automatically turn off the heat pump.

When I wake up in the morning, the heat pump should be still off but that's not the case. What is the timeout for a sensor to be considered "dead"? Can we extend it? 

Thank you

**Comment by jmcollin78** [comment]
I have also seen something like that but because I have some automation, I wonder if one off the automation tries to turn on the heat pump.

May be there is something to enhance or fix. I will have a look.

**Comment by Hubert2208** [comment]
In my case i have several schedules to change the Preset e.g for night. 
If preset changes and the window is already open, then is the action (in my case the thermostat should choose the preset für frostprotection if window is open) ignored.

**Comment by jmcollin78** [comment]
Hello, I change the behavior on https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.3.4.
Please give it a try and I think this will solve this issue.

Please reopen, if you find out the issue is still there.

Thank you for your report.
