### ISSUE TITLE
Add a thermostat over a climate mode in addition to the thermostat over switch mode

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#5]
A climatisation or a reversible climatisation should be usable with this thermostat. What we want is that every existing climate entity can be controled by a VersatileThermostat

**Comment by jmcollin78** [comment]
We don't want to add the cooling but we prefer to user a VersatileThermostat over an existing thermostat which control the HVAC.

So that,
1. the underlying thermostat will benefit of the Versatile Thermostat features,
2. the implementation will remains simple,
3. every climate entity will be able to benefit the Versatile Thermostat features.

Do do that we need to configure:
1. a first page with the name and the VersatileThermostat type (climate over switch or climate overs climate) and the features we need for this thermostat (window, motion, power, presence),
2. have a second page which can configure the climate over switch containing temperature sensor, cycle and algorithm configuration
3. have a second page for the climate over climate type. In that page we should configure the underlying climate and maybe other options (not identified now)
4. subsequent pages will be displayed only if the features was claimed for that thermostat

This should be not very hard to implement.

Options:
- do we need to implement a V2 config entry and a migration between them ?
-> yes
- it should be better to implement also the https://github.com/jmcollin78/versatile_thermostat/issues/16 issue

This would be a great 2.0.0 release.

**Comment by kadaan** [comment]
@jmcollin78 Just found this project and it seems awesome.  I have a ducted mini-split system which three zone each with their own SmartSi.  I've love to use this thermostat "on top" of the current climate devices.  That said, I think there are some setting on the SmartSi that are needed to ensure that the mini-split system doesn't get short cycled:

- Min Cycle Off Time
- Min Cycle On Time
