### ISSUE TITLE
Échec d'appel du service climate/set_preset_mode. 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Davxci** [jmcollin78/versatile_thermostat#50]
Bonjour,

Dsl c'est en francais.

J'ai un souci sur des thermostat j'ai au bout de quelque heure ce message la
  Échec d'appel du service climate/set_preset_mode. 'NoneType' object has no attribute 'lower'

Cela apparait que sur des thermostat en zwave eurotronic via zwave-js-ui et mqtt
J’utilise cette carte en plus de simple-thermostat.

j'ai essayé différent réglages dans l'onglet security mais sans succès

Actuellement j'ai essayer avec pour le même résultat :
minimal_activation_delay_sec : 600
security_delay_min : 3600
security_min_on_percent : 1
security_default_on_percent : 0.3

Merci pour l'aide

**Comment by jmcollin78** [comment]
Bonjour, pas de soucis pour le Français, je préfère aussi.

Il n'y a pas de preset qui s'appelle 'lower' et c'est la cause de l'échec. Certainement que votre card utilise un preset nommé 'lower' mais ce n'est pas reconnu par le Versatile Thermostat.

Les préset utilisables sont: eco, comfort, boost, activity . Ce sont les preset standard du composant climate de Home Assistant

**Comment by Davxci** [comment]
Dsl, pas pu répondre avant, merci pour cees informations, je vais regarder.
Pour ton edit2 en faite plus j’augmente la durée de security_delay_min plus ça retard le message que j'ai mis plus haut

**Comment by jmcollin78** [comment]
Bonjour,

Est-ce que tu as des nouvelles ? Je vais faire une release donc si j'ai des corrections à faire, j'aimerai bien intégrer celle-ci.

**Comment by Davxci** [comment]
Dsl je revient juste de vacances, et j'ai pas trop regarder 
De ce que je peut te dire rapidement c'est que ce sont des vanne thermostatique eurotronics

https://www.domotique-store.fr/domotique/usages/domotique-chauffage-climatisation-a-distance/tetes-thermostatiques-radiateur-eau-sans-fil-domotique/1579-eurotronic-spirit-zigbee-tete-thermostatique-sans-fil.html

Qu'elle sont sous zigbee2mqtt et que cela passe par un serveur mqtt (mosquitto)

Je passe pas la carte simple-thermostat et scheduler-card pour les gérer le chauffage.
Que ce soit par les preset ou par réglage de température au bout d'un moment j'ai toujours le même message qui revient.

Je vais testé avec la version 3.0.0 en beta et je te fait un retour.

**Comment by jmcollin78** [comment]
Elle est en release maintenant.
Si tu as encore des soucis, il faut que tu m'envoies les attributs du thermostat (Outils de dev / Etats / choisir ton thermostat)
et si tu as des graphiques qui donnent l'évolution du % de puissance, les températeurs de consigne et courante, je prends.

Corrige d'abord les qqes erreurs que j'ai remontées au dessus notamment security_min_on_percent : 1 qui n'est vraiment pas bon. Entre 0,5 et 0,7 c'est bien. Ca se configure sur la dernière page de configuration de l'intégration.

**Comment by jmcollin78** [comment]
Chez moi j'ai eu le même genre de soucis et j'ai été obligé de changer security_delay_min avec 90 min.

Si tes thermometres sont à piles, ils peuvent ne pas envoyer de température pendant longtemps lorsque la température est stable.

**Comment by jmcollin78** [comment]
Si on regarde les dates:

last_temperature_datetime: '2023-03-07T08:01:00.119541+01:00'
last_ext_temperature_datetime: '2023-03-07T03:35:52.515076+01:00'
security_state: true
last_update_datetime: '2023-03-07T09:16:55.215814+01:00'

On voit que c'est surtout la température extérieure qui est très ancienne (> 6 h) et la température intérieure à 1h15

**Comment by Davxci** [comment]
Les thermostats et capteurs de température sont a pile.
La température extérieur est issue du capteur de ma chaudière, je vais regarder de ce coté la effectivement .

Par contre ce que je m'explique pas c'est que j'ai d’autre modèle de tête thermostatique et que je n'ai pas ce problème la alors que j'ai la même définition


versatil avec une tête thermostatique danfoss ally 
`
hvac_modes:
  - heat
min_temp: 8
max_temp: 28
target_temp_step: 0.5
preset_modes:
  - none
  - eco
  - comfort
  - boost
current_temperature: 17.2
temperature: 17
hvac_action: 'off'
preset_mode: eco
hvac_mode: heat
type: thermostat_over_climate
eco_temp: 17
boost_temp: 21
comfort_temp: 20
eco_away_temp: null
boost_away_temp: null
comfort_away_temp: null
power_temp: null
ext_current_temperature: 5.8
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 17
saved_hvac_mode: null
window_state: null
motion_state: null
overpowering_state: null
presence_state: null
security_delay_min: 3600
security_min_on_percent: 0.5
security_default_on_percent: 0.3
last_temperature_datetime: '2023-03-07T11:01:21.296582+01:00'
last_ext_temperature_datetime: '2023-03-07T10:57:22.623115+01:00'
security_state: false
minimal_activation_delay_sec: 300
device_power: null
mean_cycle_power: null
total_energy: 0
last_update_datetime: '2023-03-07T11:06:13.669039+01:00'
timezone: Europe/Paris
underlying_climate: climate.salon_thermostatique
start_hvac_action_date: '2023-03-07T06:31:22.449359+01:00'
friendly_name: Salon
supported_features: 17
`

et les info de la tête thermostatique dans ha

`
hvac_modes:
  - heat
min_temp: 5
max_temp: 35
target_temp_step: 0.5
current_temperature: 17.3
temperature: 17
hvac_action: 'off'
adaptation_run_control: none
adaptation_run_settings: true
adaptation_run_status: lost
algorithm_scale_factor: 1
battery: 54
day_of_week: thursday
external_measured_room_sensor: -8000
heat_available: true
heat_required: false
keypad_lockout: unlock
last_seen: '2023-03-07T11:07:21+01:00'
linkquality: 255
load_balancing_enable: true
load_estimate: 58
load_room_mean: -8000
local_temperature: 17.31
mounted_mode_active: false
mounted_mode_control: false
occupied_heating_setpoint: 17
pi_heating_demand: 0
preheat_status: false
programming_operation_mode: setpoint
radiator_covered: false
regulation_setpoint_offset: null
running_state: idle
setpoint_change_source: externally
system_mode: heat
thermostat_vertical_orientation: false
trigger_time: 660
update:
  progress: 58.59
  remaining: 3340
  state: updating
update_available: false
viewing_direction: false
window_open_external: false
window_open_feature: true
window_open_internal: closed
friendly_name: Salon_thermostatique
supported_features: 1
`
Je vais comparer entre les 2  et voir d’où cela peut venir

**Comment by jmcollin78** [comment]
Si on regarde ta conf je vois ça:

security_delay_min: 3600                 <---- 3600 min -> 60h presque 3 jours. Donc il ne se mettra jamais en security. la valeur est en minute
last_temperature_datetime: '2023-03-07T11:01:21.296582+01:00'.  <---- dernière mesure il y a 5 min
last_ext_temperature_datetime: '2023-03-07T10:57:22.623115+01:00' <---- dernière mesure il y a 10 min
last_update_datetime: '2023-03-07T11:06:13.669039+01:00'

**Comment by Davxci** [comment]
Ok je viens de voir d'ou viens le problème ce n'est pas un ssouci de versatile thermostat mais de la carte simple-thermostat
Problème visiblement pas regler :
https://github.com/nervetattoo/simple-thermostat/issues/265

je vais faire des test avec une autre carte

**Comment by jmcollin78** [comment]
ok pas sur d'avoir compris le problème de "set point" avec la card que j'utilise tous les jours.
Pas sur non plus de voir le lien avec le problème décrit juste au-dessus.

Je te laisse fermer le ticket si tu as résolu tes soucis

**Comment by Davxci** [comment]
Bon finalement une désinstallation et une ré-installation du module dans la version 3 à été bénéfique.
Touts les thermostat crée on été également refait.
Je penche donc pour un problème lors de l'installation la 1er fois.
