### ISSUE TITLE
Configuration de la gestion de la puissance plus prise en compte

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#514]
### Discussed in https://github.com/jmcollin78/versatile_thermostat/discussions/500

<div type='discussions-op-text'>

<sup>Originally posted by **slt14** September 21, 2024</sup>
Bonjour, anciennement sous Domoticz ou je gérai les radiateur avec mon délestage en fonction du linky, je suis passé sous HA au printemps.

J'ai ajouté tous les fils pilotes (14) (et passé en switch ceux qui étaient restés en light) et j'ai les capteurs de température.
Je suis connecté au linky en filaire, pas de soucis.

Ma problématique et que j'ai ajouté des thermostats.
J'indique bien la puissance... 1000 par exemple.

_Par ailleurs j'ai toujours un doute là dessus, il est dit qu'il faut que ce soit la même unité partout... donc je pense que c'est bon?
Dans mon central configuration j'ai mis : 
Puissance Totale :  Teleinfo 03196129xxxx SINSTS (ce qui correspont -à ce que linky transmet donc en VA)
Capteur de puissance max : Puissance MAX (qui est donc une entrée que j'ai fixé à 12000) J'ai un abonnement de 12 kVA_

J'ai ensuite l'option ou je prend le réglage par défaut.
Je finalise la configuration et.... une fois cela terminé la gestion de puissance n'est pas présente.

Le plus perturbant dans l'histoire ce qu'elle est bien présente sur 4 appareils sur 9

J'ai VTh 6.2.9

Core 2024.9.2
Supervisor 2024.09.1
Operating System 13.1
Interface utilisateur 20240909.1

Comme on dit, cela marchait avant... 
J'avais ajouté 4 Vth avant les vacances d'été sans soucis, et là je voulais finaliser...
Un BUG avec une mise à jour HA?

Je vais chercher dans les logs si je trouve des pistes

.../...

J'ai supprimé tout, recréé un vth et toujours que 13 entités présentes (18 lorsque la puissance était là) ...

.../...
VersatileThermostat-Bureau - power not valued. check_overpowering not available
</div>

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/pull/513

**Comment by slt14** [comment]
Il y a en effet du mieux, l'option est bien présente lorsque je reviens sur le thermostat.

En revanche j'ai cru un temps que cela fonctionnait pour le gestion de la puissance mais ... non

Le pire c'est que j'ai mis tous les thermosats sur OFF , cf PJ, la puissance de 8000 est bien dépassée.

Mais ils continuent a tourner aléatoirement et plus rien n'est mis à jour sur les thermostats

<img width="2400" alt="Capture d’écran 2024-09-29 à 15 51 16" src="https://github.com/user-attachments/assets/f556e8b0-59fb-454f-9af5-bea4fea8cc63">

J'ai par exemple un radiateur "bureau" qui a déjà dépassé la consigne de température mais s'allume régulièrement pour quelques secondes a peine

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.3.4
