### ISSUE TITLE
Heating and Cooling for underfloor water tubes

### ISSUE THREAD

**Issue by rudiratlos** [jmcollin78/versatile_thermostat#523]
Hello,
I have underfloor heating that works with water. In winter, warm water is fed through for heating. In summer, cold water is channelled through for cooling. Is it possible to extend the thermostat so that winter OR summer operation is possible? An external boolean variable indicates winter (ON), thermostat should offer only heating related control, if the variable indicates summer (OFF), only cooling control should be offered.

I'm using a wifi controlled shelly relay, which is switching a valve for open or close.

**Comment by jmcollin78** [comment]
Hello,

All thermostat in HA works with hvac_mode which can be Heat or Cool. If you are able to deal with those 2 hvac_mode in one thermostat, you will be able to use VTherm.

**Comment by schzffr** [comment]
@rudiratlos I'm interested as well. I'm using the same setup, a Shelly opens and closes a danfoss valve. Did you find a solution ?
