### ISSUE TITLE
When switching from Cool to Heat on a AC, the Target temp remains with the Cool preset(not switching to Heat preset)

### ISSUE THREAD

**Issue by gunmalmg** [jmcollin78/versatile_thermostat#524]
Hallo 

Sorry to report a potential bug in the VTherm.

But it seems that when switching from Cool to Heat on a AC, the Target temp remains with the Cool preset, not switching to back to Heat preset.

That made my room really hot today - because the Cool preset are much higher than the Heat preset 😜

Hope this is a easy fix 

Regards

Gunnar

**Comment by jmcollin78** [comment]
Hello @gunmalmg,

I have reproduce the issue. Thank you for your report. You should switch the preset to force the new temperature also.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.3.3

**Comment by gunmalmg** [comment]
Thank you 👍
