### ISSUE TITLE
Possibility to override energy measurment with energy sensor 

### ISSUE THREAD

**Issue by d96moe** [jmcollin78/versatile_thermostat#526]
As I have energy meters on all my radiators and HVACs I would live to have the possibility to override the internal energy measurment with a sensor value.

**Comment by jmcollin78** [comment]
Hello @d96moe ,

If you already have energy measurment why to you need to use this "approximative" and fake energy measurement from VTherm ?

This seems totally useless and will complexify the configuration with a very low added value. 

Don't hesitate to comment if needed, I will close this request

**Comment by d96moe** [comment]
Ah, I think I missunderstand your power shedding algorithm. I thought you used the momentary consumption of your thermostats.

**Comment by jmcollin78** [comment]
No, it use the max power of the device
