### ISSUE TITLE
controlling UI appearance by VTherm attributes

### ISSUE THREAD

**Issue by rudiratlos** [jmcollin78/versatile_thermostat#527]
How can I switch the cooling indication off/on (pls. see attached image) by setting an attribute?
I know, I can configure this in the 'Versatile Thermostat UI Card' itself, but this is static.
I want to display the cooling icon during summertime and the heating icon during wintertime, which is controlled by an external event/script/automation.

additional attributes in the VTherm entity would be nice. e.g. 
....
tpi_coef_int: 0.6
show_cooling_icon: on/off #######  additional attribute for controling appearance of UI card dynamically
show_heating_icon: on/off #######  additional attribute for controling appearance of UI card dynamically
....

![vt](https://github.com/user-attachments/assets/e2eec874-28df-4348-b963-a1d5dd2b7109)

**Comment by jmcollin78** [comment]
Hello, this is not possible and I will not implement this very specific need.
