### ISSUE TITLE
Option for Min Percentage of regulation for Thermostat over valve / in addition to delta percentage of regulation

### ISSUE THREAD

**Issue by ludog31** [jmcollin78/versatile_thermostat#536]
**Is your feature request related to a problem? Please describe.**
The feature request is related to some couple of valves / TRV not "well" calibrated. 
I own some TRV BOSCH BTH-RA (Thermostat 2) and my valve starts to really be opened and make water flow into convector at 15% of Pi Heating demand

**Describe the solution you'd like**
The solution could be to introduce into the thermostat over valve settings, an option where the user set a minimum regulation level (15% in my exemple) so that when the algorithm calculates lower (7% for instance), the valve percent remains at the lower limit (15% in my exemple), boiler keeps heating with flow inside convector. 
It could enable a finest tuning of boiler switch in combination with TPI parameters

**Additional context**
I hope being clear enough :)

Best regards,

**Comment by Kumalo** [comment]
hello @ludog31 ,

I fully understood your request.

I also asked yesterday in the post [hacf](https://forum.hacf.fr/t/nouveau-thermostat-type-proportionnel-avec-gestion-des-presets-portes-et-fenetres-detection-de-mouvement-gestion-de-presence-et-surconsommation/19160/1757) a solution to avoid having the thermostat over valve closed or almost closed and the boiler heating.

It is the same goal with a different vision : Like your example, an option where the user set a minimum regulation threshold (15% in your exemple) so when the algorithm calculates lower (7% for instance), the thermostat over valve is considering as inactive and the boiler stops heating.

In your solution, the thermostat over valve is never completly closed then the boiler is keeping heating without risk (more confortable)
In my solution,  the boiler is not heating when the thermostat over valve is almost closed (more economic)

Best regards,

**Comment by jmcollin78** [comment]
Implemented with the @Kumalo in https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.3.4.beta1

I close the issue. Don't hesitate to reopen if needed.
