### ISSUE TITLE
when scheduler changes temperature, while windows is open - thermostat just sheepishly listens. 

### ISSUE THREAD

**Issue by tomtom13** [jmcollin78/versatile_thermostat#537]
Pretty simple. 
Create a phoney window sensor you can control by hand (or use a spare door sensor) and assign it in configuration. 
Set the temp on the thermostat to what ever you want.
Set the schedule to change the temperature / set preset in next few minutes.
"open the window"

Now when the schedule kicks in one would assume that the window override will be still preserved, but nope - the schedule just sets the temp and radiator can successfully heat the neighbourhood :) 

After you close the window, the old temp gets set back. 

Tested with with frost protection preset and OFF.

Yeah, I know, me and my silly issues.

**Comment by jmcollin78** [comment]
Hello @tomtom13 ,

You didn't respect the template for issue. So sad, I cannot see your parameter. I need to know what is your window tuning ?

**Comment by tomtom13** [comment]
Default values.

**Comment by jmcollin78** [comment]
Turn to OFF when window is open ?

**Comment by jmcollin78** [comment]
I suppose yes. When changing preset or target temp when the window is open, the preset or target temp change but the VTherm is still turned off.

When you close the window, the Vtherm turns on and then the new target or preset is used.

This is totally wanted and a good behavior on my opinion: the scheduler does its life, the VTherm also and when VTherm turns on, the last Scheduler command is applied.

Agree ?

**Comment by tomtom13** [comment]
Disagree, because radiator start immediately heating even thou the window is open.
The other parts are "nice to have" but the fact that scheduler can override the open window thing is a bit daft.

**Comment by tomtom13** [comment]
OK, my presets are setup to do "Auto @ desired_temp". IF that is undesired, I might have missed that in the documentation (no, it's not a snarky "it's not there", your documentation is pretty big and I might have missed that part). 
But at least you've pointed out the culprit.
