### ISSUE TITLE
It seems I can't add a fifth heater for an over switch VTherm

### ISSUE THREAD

**Issue by pounard** [jmcollin78/versatile_thermostat#539]
I want to add a 5th heater commuter for a single VTherm, how can I do that ?

![image](https://github.com/user-attachments/assets/690c1c38-e2d3-4b97-a7db-14297a97d77d)

As you can see, the choices are blocked to only 4 inputs.

**Comment by jmcollin78** [comment]
Yes this is limited to 4 which is sufficient for 99.9 % of the cases. You cannot add a fifth one but you can always add another VTherm. 3 + 2 for example.

**Comment by pounard** [comment]
@jmcollin78 

That's terrible UX ! Couldn't you just raise the limit ? I have no idea about the implications of this, but if the limitation is purely UI driven, it's probably easy to fix ?

**Comment by jmcollin78** [comment]
No that is not easy at all. Config UI is totally driven by HA capabilities and is very constrained. I don't say it is impossible, but only very difficult.

If you think you are able to do better, please do it and I would be please to merge your PR.

**Comment by pounard** [comment]
Python is sadly not the language I work the most with, but if ever I managed to get some spare time, I'll try. Thank you very much for your time answering this and developping this great piece of software !
