### ISSUE TITLE
Feature request: Central configuration for presets

### ISSUE THREAD

**Issue by kvanbiesen** [jmcollin78/versatile_thermostat#550]
Versatile thermostat with central configuration work great with setting the target temperature.

But for the moment we have to set the preset like 'eco' to all the vtherm appliances separately.

Wouldn't it be nice if you set a certain preset on the central configuration, also propagates to all the underlying vtherms.

Kinda like the heating/cooling setting but for the presets

**Comment by jmcollin78** [comment]
Hello, what is the use case ?
On my home, it is really not a need: each VTherm have its own preset depending of presence, time of day, ...

I guess you have a special use case for needing something like that.

**Comment by kvanbiesen** [comment]
Cause usually all presets happen when they they go in frost or comfort.

Comfort can be different for different rooms but usually same a global
setting.  Cause since it's central config, and it can define global mode
(heating/cooling,...) I don't see why preset can be set globally. Should be
to much change? People don't have to use if, just be available

**Comment by jmcollin78** [comment]
No it is easy to do, but I only want to do useful things because I have a lot of work.
I will think about that.

**Comment by kvanbiesen** [comment]
Yeah no I get that. Just throwing up an idea. Thanks for your hard work!

**Comment by hilburn** [comment]
If you wanted to do this with just template work - you could use the following to get a list of all VTherm climates to pass into climate.set_preset:
```yaml
{{ states.climate | map(attribute="entity_id") | select("is_device_attr", "manufacturer", "JMCOLLIN") | list }}
```
It's what I used to use with my "override" buttons in a similar way to what you're asking for

**Comment by jmcollin78** [comment]
> If you wanted to do this with just template work - you could use the following to get a list of all VTherm climates to pass into climate.set_preset:
> 
> ```yaml
> {{ states.climate | map(attribute="entity_id") | select("is_device_attr", "manufacturer", "JMCOLLIN") | list }}
> ```
> 
> It's what I used to use with my "override" buttons in a similar way to what you're asking for

Yes. So, you are at least, two with the same needs.

**Comment by hilburn** [comment]
I've actually moved away from that now. I use the schedule state integration for setting the preset for each room and it that can do conditionals in a much more robust way than Scheduler - so when I press a button it switches all room schedules to follow the master schedule, giving me the behaviour I (very occasionally) want but individual control the rest of the time

**Comment by kvanbiesen** [comment]
It's not a high demand. Currently I made a select box helper with the
states and a run a automation when the state gets changed.  It's updates
all presets on all vtherms.
Works perfectly, even with the scheduler card.

**Comment by jmcollin78** [comment]
ok. I will close the feature request for now.
