### ISSUE TITLE
It is possible to validate a configuration over_switch without TPI parameters set

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#552]
An example is described here: https://forum.hacf.fr/t/vtherm-pas-dentite-climate/49408/2

**Comment by jmcollin78** [comment]
Reproduced !

When there is no central configuration, the checkbox 'use central configuration' for TPI parameters and also Preset is checked. Then the Finalize configuration is available but the VTherm couldn't start.

**Comment by jmcollin78** [comment]
Will be in next release.

**Comment by Shasdo** [comment]
Nice to see that you finally identified it.

Good job !

**Comment by jmcollin78** [comment]
Here you have a beta release that seems to fix the issue: https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.6.1.beta2

Can you please give it a try ?

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.6.1
