### ISSUE TITLE
Le chauffage continue alors que la maison n'est plus occupée

### ISSUE THREAD

**Issue by gael1980** [jmcollin78/versatile_thermostat#562]
Bonjour,

J’ai remarqué depuis hier que mon chauffage continue de chauffer, même si la maison n’est plus occupée.

Plusieurs cycles de chauffage se sont enchaînés, alors que l’état de présence de la maison indique qu’elle est absente.
Voir la pièce jointe.

Au bout d’un certain temps, le chauffage se coupe.

Merci pour votre aide.

Gaël

```
hvac_modes: heat, off
min_temp: 7
max_temp: 25
target_temp_step: 0.1
preset_modes: none, frost, eco, comfort, boost, activity
current_temperature: 18.9
temperature: 16
hvac_action: idle
preset_mode: activity
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Auto
frost_temp: 7
eco_temp: 16
boost_temp: 19
comfort_temp: 18
frost_away_temp: 7
eco_away_temp: 16
boost_away_temp: 16
comfort_away_temp: 16
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 17.32
ac_mode: false
current_power: 305
current_power_max: 11500
saved_preset_mode: activity
saved_target_temp: 16
saved_hvac_mode: off
motion_sensor_entity_id: input_boolean.fake_motion_sam
motion_state: off
power_sensor_entity_id: sensor.433_cm_180
max_power_sensor_entity_id: input_number.p_max
overpowering_state: false
presence_sensor_entity_id: binary_sensor.maison_occupee
presence_state: off
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: binary_sensor.bas_ouvert
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
window_action: window_turn_off
security_delay_min: 240
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-10-16T09:27:12.213195+02:00
last_ext_temperature_datetime: 2024-10-16T09:40:46.598728+02:00
security_state: false
minimal_activation_delay_sec: 60
device_power: 3500
mean_cycle_power: 0
total_energy: 39888.33
last_update_datetime: 2024-10-16T09:40:46.608091+02:00
timezone: Europe/Paris
temperature_unit: °C
is_device_active: false
ema_temp: 18.95
is_used_by_central_boiler: false
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_switch_0: switch.chauffage_salon
underlying_switch_1: switch.chauffage_manger
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 600
cycle_min: 10
function: tpi
tpi_coef_int: 2
tpi_coef_ext: 0.03
friendly_name: Thermostat Salle
supported_features: 401
```

Je suis bien sur la dernière version de versatile et de hass.

![Capture](https://github.com/user-attachments/assets/e3e2ab9e-c441-4beb-bfa7-b12bcfb8278f)

**Comment by jmcollin78** [comment]
Hello @gael1980 ,

In your, VTherm attributes, the presence is off:
```
presence_sensor_entity_id: binary_sensor.maison_occupee
presence_state: off
```

So I don't know what happens. Maybe you have errors in logs ?

**Comment by gael1980** [comment]
Merci pour ton aide, désolé, je vais répondre en français, mon anglais est...
Je ferai un essai vendredi.


Il n’y a personne dans la maison à part mes chats, qui doivent déclencher le détecteur.

Il semble que, même en l’absence de personnes à la maison, tant que le détecteur de mouvement est “on”, le chauffage continue de fonctionner.

Le système attend que le détecteur passe en “off” pour couper le chauffage.

Est-il possible de forcer le vtherm à passer en “off” lorsque la maison n’est plus occupée, même si le détecteur de présence reste “on” ?

Cependant, une fois qu’il est passé en “off”, même si un chat passe devant le détecteur, il ne remet pas le chauffage en route (ce qui est logique, puisqu’il n’y a personne à la maison).

Comme tu peux le voir sur l'historique.
<img width="1162" alt="Capture d’écran 2024-10-16 à 20 28 40" src="https://github.com/user-attachments/assets/2b8c9bd4-2644-4428-82e0-1284fb9a98d2">

**Comment by jmcollin78** [comment]
Le fonctionnement que tu décris ne me choque pas. Chaque évènement (détecteur, sortie de la maison, ...) déclenche des changements lorsqu'il arrive et sont indépendants. Je comprends que dans ton cas, ce ne soit pas pertinent mais on pourrait très bien vouloir l'inverse : chauffer si le détecteur bouge mais que la présence est off. C'est mon cas, quand la femme de ménage passe. Elle n'est pas dans la présence mais fait bouger les détecteurs de mouvement et elle a le droit a du chauffage.

Tu devrais plutot régler le problème de fond qui est que les chats font bouger le détecteur de mouvement : tu vas avoir le problème tout le temps, allumage des lumières, déclenchement du chauffage, ...  Y a peut être une sensibilité à régler ou le capteur à changer.

**Comment by jmcollin78** [comment]
In English,

Using presence and motion feature in combination is not recommended. Each sensor can give contradictory information and the VTherm could have a weird (but finally logical) behavior.
