### ISSUE TITLE
Ignore set temperature changes from underlying if outside of configured min/max range

### ISSUE THREAD

**Issue by gpayer** [jmcollin78/versatile_thermostat#576]
Any set temperature changes sent by an underlying should be filtered by using the configured min/max temperature values.
This way VTherm usage via the HA UI and via an underlying behave the same way.

**Is your feature request related to a problem? Please describe.**
And additionally stupid behaviour (like sending a set temperature of 5.0 °C if switched off) by underlyings (looking at you, Bosch BTH-RA) is ignored.

**Describe alternatives you've considered**
Abusing the light auto-correction, so set temperature changes from underlyings are ignored. However this might lead to suboptimal heating behaviour.

Originally I had planned to implement this myself, as this is a pretty minor change, but I simply can't find the time to do so.

**Comment by jmcollin78** [comment]
Hello @gpayer ,

Yes this is a nice suggestion. I would love a PR for doing that because, my time is also so short.
I could help if needed, i seems to be easy to implement.

**Comment by jmcollin78** [comment]
Thank you @gpayer !
You are now a member of the family contributor: https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.4.1
