### ISSUE TITLE
Central mode "Stopped" ignored

### ISSUE THREAD

**Issue by tibsys** [jmcollin78/versatile_thermostat#582]
My setup uses a central, I have the device and different heating devices configured with `thermostat_over_climate`.
All the heating devices are configured to use the central (all the attributes are checked in the control panel of the devices).

When I set the `Central Mode` to `Stopped` I expect the boiler to stop. But it is not the case, it continues to work : the switch state is still `on` and the `Central boiler`sensor is also `on`.

I suspect this feature does not work as expected, the plugin though is absolutely amazing.

![settings_1](https://github.com/user-attachments/assets/6545ba17-f74d-4527-8140-3965a05249f6)

**Comment by jmcollin78** [comment]
Please give me more informations (VTherm attributes at least) and respect the template of issue.
Central Mode set to Stopped doesn't stop the boiler directly but stops the heater. If correclty configured this should lead to the stop of the boiler.

Check (or post) the configuration of the central Vtherm in which you have the boiler commands.
Check that all VTherm are stopped when you click on Central mode / Stopped.
Check that independently, of the central mode, when each VTherm is turned of, the central boiler is turned off.
Check the number of VTherm seen as On (you have an entity for that in the central configuration device)

**Comment by tibsys** [comment]
Thank you for your answer. Obviously I misunderstood the role of the Central Mode.
What I want is the ability to totally disable the VTherm and the central boiler in one click, and immediately stop the heating, instead of having to set the temperature of each thermostat.
I think I can achieve that by using a scene or a virtual switch instead. So if the function does not exist, no problem, I'll do it another way.
Regards

**Comment by tibsys** [comment]
Thank you for your answer. Obviously I misunderstood the role of the Central Mode.
What I want is the ability to totally disable the VTherm and the central boiler in one click, and immediately stop the heating.
I think I can achieve that by using a scene or a virtual switch instead. Maybe I'll try it this way.
Regards

**Comment by jmcollin78** [comment]
Hello, I close this issue because it seems to be stale. Reopen if needed.
