### ISSUE TITLE
Minimum cycle time

### ISSUE THREAD

**Issue by rbjoensen** [jmcollin78/versatile_thermostat#586]
Hello and thank you for a super integration.
I have underfloor heating, and want it to be active in e.g. 20 minutes for each cycle.
As it is now, I can see it is active for approx. 5 minutes.
Is there a way I can define the minimum cycle time?
greeting

**Comment by jmcollin78** [comment]
Just read the documentation.... The cycle is one of the first parameter for each VTherm.

**Comment by rbjoensen** [comment]
Cycle duration is set to 30 minutes!
