### ISSUE TITLE
Disable unset preset mode if the temperature is manually defined on a thermostat

### ISSUE THREAD

**Issue by bilbon0bud** [jmcollin78/versatile_thermostat#587]
Versatile Thermostat unset the thermostat mode, because he think a have manually define a new temp set point on my TRV...
But, the probleme come from my Danfoss TRV, who doesn't execute the last set point temp change asked by versatile thermostat....

So here a simple explanation

1/ Preset to comfort (20°) on Vtherm, he send the set point the the TRV with a temp ajustement (21°) 
2/ The TRV doesn't execute the setpoint change, and tell the set point is 18°
3/ Vtherme disable the preset.

I have to reboot my TRV (Danfoss Ally under Z2M)

Could it be possible to disable the unset preset mode on some vtherm ?

Best regards

**Comment by jmcollin78** [comment]
> Could it be possible to disable the unset preset mode on some vtherm ?

No, it is a feature used by most people to be able to control their device manually.
You can notice that the next time the Scheduler will send a preset, the Vtherm will go back to the preset mode. The manual mode (without preset) is temporary until the next Scheduler change.
