### ISSUE TITLE
Cycle duration not working 

### ISSUE THREAD

**Issue by rbjoensen** [jmcollin78/versatile_thermostat#588]
Cycle duration is set to 30 minutes but stops after 5 minutes

hvac_modes:
  - heat
  - "off"
min_temp: 15
max_temp: 30
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 19.9
temperature: 20
hvac_action: idle
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 15
eco_temp: 15
boost_temp: 15
comfort_temp: 15
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 11.7
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 20
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-10-28T16:34:38.264024+01:00"
last_ext_temperature_datetime: "2024-10-28T16:46:06.590840+01:00"
security_state: false
minimal_activation_delay_sec: 300
device_power: 1
mean_cycle_power: 0.16
total_energy: 14.8
last_update_datetime: "2024-10-28T16:46:06.594500+01:00"
timezone: Europe/Copenhagen
temperature_unit: °C
is_device_active: false
ema_temp: 19.88
is_used_by_central_boiler: false
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_switch_0: switch.sonoff_1000e91693_3
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0.16
power_percent: 16
on_time_sec: 0
off_time_sec: 1800
cycle_min: 30
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
friendly_name: gang
supported_features: 401
icon: mdi:heat-wave

**Comment by jmcollin78** [comment]
Hello @rbjoensen,

Can you give me more clues. What is stopping after 5 minutes ? 
I see your configuration seems correct:
```
cycle_min: 30
```
but ytour thermostat is just not heating (no need):
```
current_temperature: 19.9
temperature: 20
hvac_action: idle
...
on_percent: 0.16
on_time_sec: 0
off_time_sec: 1800
```

Your thermostat is not heating because you tell him not to heat under 5 min (which is a good thing):
```
minimal_activation_delay_sec: 300
```

For me all is normal.

**Comment by rbjoensen** [comment]
sometimes it is more than 5 minutes but never more than 10 minutes

![Screenshot_2024-10-31-11-17-14-74_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/43262689-7fba-4351-8138-fd8a97ec1987)

**Comment by jmcollin78** [comment]
What do you think is a problem ? All I see is normal. The cycle is really 30 min, If I look at your graph.

**Comment by rbjoensen** [comment]
but the gap between heat is about 30 minutes
![Screenshot_2024-10-31-16-13-44-14_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/648fd0a5-e74d-4d1d-908f-9b0a1d34fb33)

**Comment by jmcollin78** [comment]
Eaxh cycle is 30 min long:
![Capture d’écran 2024-10-31 à 17 02 41](https://github.com/user-attachments/assets/4d1bf302-24ea-40a8-beb2-e5190bf40fe1)

You are confusing cycle length and heat period. During one cycle (30 min) and depending of the conditions, VTHerm can heat from 5 min (the threshold you gave) and 30 min. Curently the heating duration length is 9 min (28 % = on_percent value).
