### ISSUE TITLE
[Feature Request] Option to use local_temperature_calibration offset for self-regulation

### ISSUE THREAD

**Issue by 0verEngineer** [jmcollin78/versatile_thermostat#595]
**Is your feature request related to a problem? Please describe.**
- The self-regulation works by adjusting the target temperature on the thermostats which can be confusing because then they display a wrong target temperature
- It seems way easier to have a boolean to allow self-regulation with the `local_temperature_calibration` variable, just re-calculate and re-set the variable every time the external temperature sensor or the internal one change the temperature

**Describe the solution you'd like**
- Add a boolean if one wants to use the `local_temperature_calibration` instead of the current self-regulation that edits the target temperature
- The boolean switch can (if possible) be hidden if the TRV does not have a `local_temperature_calibration`

**Describe alternatives you've considered**
- There is no alternative besides the current self-regulation which has some drawbacks

**Additional context**
- Here is the discussion i found: https://github.com/jmcollin78/versatile_thermostat/discussions/494
- I opened this FR as an Issue instead of commenting on the discussion because i think it is important to use the `local_temperature_calibration` for this because that is the reason it exists and a developer who wants to contribute will not look through the discussions but the issues
- Here is a screenshot of the variable in homeassistant: 
![Screenshot_20241102_140035](https://github.com/user-attachments/assets/ace1bb55-2c55-45af-8fe2-bf02f682fc84)

**Comment by maia** [comment]
Which TRV exposes this specific variable? The tricky thing is that the vendors name these differently, usually it has „offset“ or „calibration“ in its name. Ideally vtherm would identify these (by regex or a lookup table for most common TRVs), otherwise users will have to enter the variable in the config.

**Comment by 0verEngineer** [comment]
- This is a Tuya TS0601 (_TZE200_p3dbf6qs) 
- Ok if this thing can be named differently by vendors the user should just be able to select it if he turns this feature on

**Comment by 0verEngineer** [comment]
Another discussion about this: https://github.com/jmcollin78/versatile_thermostat/discussions/342

It seems the Author don't want this, but for TRV's that have this settings this is just the correct way to do it and the current solution is just a workaround.

**Comment by hilburn** [comment]
I'll have a think about how to implement this in a fairly universal way and see if I can make a PR for him

**Comment by maia** [comment]
Variables used, taken from: https://www.zigbee2mqtt.io/supported-devices 

`local_temperature_offset`: Ubisys Hi
`regulation_setpoint_offset`: Danfoss Ally, Hive Radiator, Popp Smart Thermostat
`local_temperature_calibration`: Sonoff TRVZB, Avatto TRV06

For ZHA devices and probably also Matter the default seems to be `local_temperature_calibration`. So I guess this is the most common variable name.

**Comment by maia** [comment]
@hilburn In case you're very motivated, would you be interested in enabling the offset feature in the Matter implementation for Eve Thermo TRVs? It's visible in Matter Server: "Endpoint 1 > Thermostat > LocalTemperatureCalibration" but not accessible yet in HA.

**Comment by hilburn** [comment]
I'm afraid I don't know anything about matter setup so not able to help with the latter.

I should be able to query the trv device the climate is inside and find matching offset entities. We'll see how it goes

**Comment by maia** [comment]
This is exciting news.

**Comment by jmcollin78** [comment]
> It seems the Author don't want this, but for TRV's that have this settings this is just the correct way to do it and the current solution is just a workaround.

No, it is a very good solution if you are able to make it generical. I don't want to over-complexify but with a simple and universal solution, of course I'm ok. This solution avoid to display a wrong temperature (the regulated temp) to the user. This is a great enhancement.

**Comment by jmcollin78** [comment]
> I'm afraid I don't know anything about matter setup so not able to help with the latter.
> 
> I should be able to query the trv device the climate is inside and find matching offset entities. We'll see how it goes

I'm pretty you cannot do that. device is not an object in HA but only some attributes in entities.

**Comment by hilburn** [comment]
> @hilburn ,
> 
> > I should be able to query the trv device the climate is inside and find matching offset entities. We'll see how it goes
> 
> I'm pretty sure you cannot do that. device is not an object in HA but only some attributes in entities.

You can get the device id for the climate entity from the device registry helper
Then the entity registry helper can give you every entity for that device - you then just need to look for ones that match some offset/calibration strings

You can even get it working in templates
![image](https://github.com/user-attachments/assets/2b6dee4a-3f76-41d7-ac11-d7f75b9c4953)

**Comment by jmcollin78** [comment]
ok fine. But how to select the right number entity (if there is many number entity in the device) ?

**Comment by hilburn** [comment]
By only searching for certain suffixes - there are a few that @maia referred to above in https://github.com/jmcollin78/versatile_thermostat/issues/595#issuecomment-2453001332 
That is what that template used to filter out all the unrelated valve_opening/closing_degree and frost_protection number entities - without even checking for numbers it also filtered out the switches and battery sensors etc
There's not much reason why a device would have multiple entities that fit those strings

**Comment by hilburn** [comment]
As for how to actually apply it:
The offset that is currently calculated and applied to the set point temperature should instead be applied to the offset entity as a negative value

Current behaviour: 
1. Calculate some offset based on self-regulation and internal temperatue - room temperature
2. Set underlying climate temperature to VTherm + offset temperature

Offset behaviour:
1. Calculate some offset based on self-regulation and internal temperatue - room temperature
2. Set underlying climate temperature to VTherm temperature
3. Set offset to -offset

Another difference is that the temperature set point of the climate doesn't need to be updated when the offset changes - which happens much more often than the VTherm target temperature changes

**Comment by maia** [comment]
I find a simple regex for searching for the suffixes the best solution. It's possible that someone will mention a device that's not yet supported, but then all that's necessary is adapting the regex. A database feels like way too much work to maintain, as there are hundreds of TRVs out there.

**Comment by jmcollin78** [comment]
> By only searching for certain suffixes - there are a few that @maia referred to above in ...and that solidly falls under "not a bug, don't be a dick"

this make sense the only caveheat I see is that entity_id can be modified by user. I often localize my entity name to have it in French (I'm not the only user). Power is puissance, offset is décalage, ... So no need to be "a dick" to make the algo failed. I wonder if we should rather ask the user what is the entity name. As an optionnal field. If not given by to try to use offset, if "use internal temp" is checked -> set offset as room_temp - internal_temp (as today). This seems quite simple and universal. That makes one more parameters in the already complex self-regulation configuration. Maybe we should organize the self-regulation page differently: in a separate configuration page. Let think about how to organize this page if you think it is relevant. 

> An alternative would be making a registry of the models and entities associated with them, but that seems like a lot of work for very little gain

Me alive, this will not happens 😉

**Comment by jmcollin78** [comment]
> As for how to actually apply it: The offset that is currently calculated and applied to the set point temperature should instead be applied to the offset entity as a negative value
> 
> Current behaviour:
> 
> 1. Calculate some offset based on self-regulation and internal temperatue - room temperature
> 2. Set underlying climate temperature to VTherm + offset temperature
> 
> Offset behaviour:
> 
> 1. Calculate some offset based on self-regulation and internal temperatue - room temperature
> 2. Set underlying climate temperature to VTherm temperature
> 3. Set offset to -offset
> 
> Another difference is that the temperature set point of the climate doesn't need to be updated when the offset changes - which happens much more often than the VTherm target temperature changes

yes but we should keep the regulated temperature. Today sent temperature is regulated + offset. Tomorrow, set calibration in the dedicated entity, set setpoint to regulated. The regulated temp helps to reach the target.

**Comment by hilburn** [comment]
I think it makes sense to keep regulation and offset bundled together tbh - another config setting!

**Comment by jmcollin78** [comment]
> I think it makes sense to keep regulation and offset bundled together tbh - another config setting!

yes. I will think how to present the regulation configuration. Maybe next week, I will have some time.

**Comment by maia** [comment]
> I often localize my entity name to have it in French (I'm not the only user). Power is puissance, offset is décalage

I can understand using other languages for the device name, but you also manually localise the automatically assigned suffixes for the entities for a device? Oh wow, that sounds like lots of work, I think I currently have 1000-2000 entities.

**Comment by 0verEngineer** [comment]
Something to consider for this feature is that some (if not all) thermostats have a maximum and minimum for the offset/calibration variable, the TS0601 Tuya Thermostats i have allow a maximum of 9 in every direction, but i also have 2 TS0601 Tuya Thermostats (newer ones) that have a maximum of 10, i know there are also some with have it at 3.

**Comment by jmcollin78** [comment]
Sonoff TRVZB have -12 offset also. It will be a supplementary mess if it not possible to get the min and max in the entity itself. Is that the case ?

**Comment by 0verEngineer** [comment]
It seems they don't have a variable for the min/max, here is the state from zigbee2mqtt of one of my TRVs:
```
{
    "battery_low": false,
    "child_lock": "LOCK",
    "current_heating_setpoint": 23.5,
    "frost_protection": "OFF",
    "last_seen": "2024-11-15T18:07:54.657Z",
    "linkquality": 21,
    "local_temperature": 22,
    "local_temperature_calibration": 0,
    "running_state": "heat",
    "scale_protection": "ON",
    "schedule_friday": "06:00/21.0 08:00/16.0 12:00/21.0 14:00/16.0",
    "schedule_monday": "06:00/21.0 08:00/16.0 12:00/21.0 14:00/16.0",
    "schedule_saturday": "06:00/21.0 08:00/16.0 12:00/21.0 14:00/16.0",
    "schedule_sunday": "06:00/21.0 08:00/16.0 12:00/21.0 14:00/16.0",
    "schedule_thursday": "06:00/21.0 08:00/16.0 12:00/21.0 14:00/16.0",
    "schedule_tuesday": "06:00/21.0 08:00/16.0 12:00/21.0 14:00/16.0",
    "schedule_wednesday": "06:00/21.0 08:00/16.0 12:00/21.0 14:00/16.0",
    "system_mode": "heat",
    "error": null
}
```

Another problem for now is that zigbee2mqtt does not give the local_temperature_calibration to homeassistant, i can not see it in the states of homeassitant but i think there is a feature request to do this in zigbee2mqtt

**Comment by jmcollin78** [comment]
The number entity should have a min / max value set to 9, I guess.

**Comment by maia** [comment]
I’ve been using a TRVZB for 3 days and really appreciate the offset calibration (`number.device_name_local_temperature_calibration`). One suggestion:

Currently, the offset is recalculated and updated on the device at every interval (e.g., 5 minutes). While precise, this could cause unnecessary strain on the device’s NAND flash memory. I suggest using an exponentially weighted moving average (EWMA) for the offset calculation and updating the device only when the absolute offset exceeds the step size from the vtherm configuration (e.g., 0.5°C). This would prevent frequent updates due to transient changes, like a draft from an open door or a briefly opened window.

Here’s the offset data from the past 24 hours—smoothing it slightly could be an improvement:
<img width="560" alt="offset" src="https://github.com/user-attachments/assets/dca186dd-cc62-4ae2-81bd-70aa7302b555">

**Comment by jmcollin78** [comment]
Hello @maia,

> This would prevent frequent updates due to transient changes, like a draft from an open door or a briefly opened window.

I didn't have in mind that this could be an issue but it seems a godd idea to avoid too much solicitation. I will integrate that in the algo.

Is it possible to display the current temperature with the offset applied ?
What is the precision of the display with your TRV ?

**Comment by maia** [comment]
Great, thanks. As for the temperature display, I will need to check when I'm back home. I'm quite sure it's a 0.5°C step display on the Sonoff TRVZB and I would assume that it displays the temperature measured with the offset applied. I will have to get back to you.

**Comment by jmcollin78** [comment]
I should be able to get the step in the climate of the Sonoff TRVZB. I will this one

**Comment by maia** [comment]
As you have realised, I wasn't fully concentrated when replying earlier today, sorry for that. The step size on the Sonoff TRVZB is 0.5°C and obviously it displays the target temperature on the device.

**Comment by jmcollin78** [comment]
Done in https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.8.0
