### ISSUE TITLE
readme: links not working, text partly in french, auto start/stop not documented

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#597]
Version 6.5 adds a "auto start/stop" feature. I tried to find it, but the links at the top of the readme don't work. But I found this:

> auto_start_stop_enable | Indique si le VTherm est autorisé à s'auto démarrer/arrêter
> auto_start_stop_level | Indique le niveau d'auto start/stop
> hvac_off_reason | Indique la raison de l'arrêt (hvac_off) du VTherm. Ce peut être Window, Auto-start/stop ou Manuel

Besides the fact that this is french, it does not explain what the auto start/stop feature does. It's probably a great feature, if only we'd know what it is. :)

**Comment by jmcollin78** [comment]
Ooooh, the text is here: https://github.com/jmcollin78/versatile_thermostat/blob/main/README.md#automatic-startstop

You have to open the section to use the direct link or search. This is not very easy to use. I will have to review totally this documentation once a day.

**Comment by jmcollin78** [comment]
Fixed.

**Comment by maia** [comment]
Hmm, which section do I need to open first? Your link leads to the top of the page, not a specific content. It seems as if collapsible sections are more problem than help.

**Comment by maia** [comment]
Oh, just found it, its in „Configuration -> Select the driven entity“

**Comment by jmcollin78** [comment]
Yes I will remove the collapsible section. It is finally a bad idea, preventing people for searching.
