### ISSUE TITLE
readme: explanation of "Use internal temperature of the underlying" missing

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#598]
taken from here: https://github.com/jmcollin78/versatile_thermostat/discussions/561#discussioncomment-10963793

I suggest to rename the config option "Use internal temperature of the underlying" to "Adjust Setpoint for Room vs. TRV Temperature". 

Also I suggest to use this text for the readme: 

> Sometimes, a device’s internal temperature sensor (like in a TRV or AC) can give inaccurate readings, especially if it’s too close to a heat source. This can cause the device to stop heating too soon. For example:
> 
> target temperature: 20 °C, room temperature: 18 °C, device’s internal sensor: 22 °C
> If the target temperature is increased to 21 °C, the device won’t heat because it thinks it’s already warm (internal temperature is 22°C).
> The Adjust Setpoint for Room vs. TRV Temperature feature fixes this by adding the temperature difference between the room and the device’s internal reading to the target. In this case, VTherm would adjust the target to 25°C (21°C + 4°C difference), forcing the device to continue heating.
> 
> This adjustment is specific to each device, making the heating system more accurate and avoiding issues from faulty sensor readings.

By the way, I find it important to use exactly the same phrases in the UI and the readme, because when I don't understand a config option I search the readme for exactly the words used in the option.

**Comment by jmcollin78** [comment]
Done: https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/over-climate.md#follow-underlying-temperature-changes
