### ISSUE TITLE
Pas de prise en compte de Group de Présence 

### ISSUE THREAD

**Issue by PtiBen69** [jmcollin78/versatile_thermostat#60]
Durant le wizard, si le "Gestion de la présence" est active. 
Le choix (dans "Capteur de pésence entity id") d'un groupe de présence n'est pas possible. Seulement un object présence classique est sélectionnable.
![image](https://user-images.githubusercontent.com/13793290/223057066-635650ff-2ac9-4be1-a09c-dc95f5ff3b78.png)

Exemple de Groupe de présence:
![image](https://user-images.githubusercontent.com/13793290/223057643-c35c2f92-c111-4d85-b401-1d3f9b8a0aa4.png)
   
![image](https://user-images.githubusercontent.com/13793290/223057209-48c4264f-2426-4d61-a248-535e02564825.png)

**Comment by jmcollin78** [comment]
Hello @PtiBen69 ,

Ca marche avec les groupes créé via les entrées (Paramètres / Appareils et Services / Entrées)

![Capture d’écran 2023-03-07 à 07 02 02](https://user-images.githubusercontent.com/1712374/223334085-c1291678-fb70-4c4f-8048-85f386602ed2.png)

Il faut que le groupe soit de l'un de ces domaines:

domain=[
                            PERSON_DOMAIN,
                            BINARY_SENSOR_DOMAIN,
                            INPUT_BOOLEAN_DOMAIN,
                        ]

A vérifier dans Outils de dev / Etats si c'est bien le cas.

**Comment by jmcollin78** [comment]
Hello @PtiBen69 ,

May I close this issue ? Do you succeed to solve your point ?

**Comment by PtiBen69** [comment]
Hello, 

J'ai utilisé ta technique :) et ça marche.

Merci pour ton travail.
