### ISSUE TITLE
negative consumption after changing settings

### ISSUE THREAD

**Issue by SRI44760** [jmcollin78/versatile_thermostat#600]
depuis la remise en route de mon chauffage, avec l’intégration Versatile thermostat, je rencontre un phénomène étrange sur ma consommation,n j’ai des consommations négatives sur mes appareils :
_Since the start of my heating, with the versatile thermostat integration, I encounter a strange phenomenon about my consumption, do I have negative consumption on my appliances:_

![image](https://github.com/user-attachments/assets/b0b6c759-fe9d-4a3d-8c91-e96d529c3361)
—> hier soir, j’ai changé de sonde de température dans la cuisine, les radiateurs concernés sont entrée -0,7, chambre 1 -0,58
_last night I changed the temperature probe in the kitchen, the radiators concerned entered -0.7, room 10 - 0.58_

![image](https://github.com/user-attachments/assets/9e490e37-552d-4cef-a671-429e55cceea3)
—> at 19h bedroom 2 -0,76, bedroom 1 -1,05
à 22h entrance -0,77, bedroom 1 -0,25

![image](https://github.com/user-attachments/assets/66097083-12f0-46cd-81b3-31ecada0dda9)

voilà la consommation de l’entrée et chambre hier :
_This is the consumption of the entrance and room yesterday:_

![image](https://github.com/user-attachments/assets/7a14f039-4f94-4bca-9cb8-c2e8876c332c)  
![image](https://github.com/user-attachments/assets/1caa5123-fa9e-47d1-b37f-3cdc688a2e16)
la descente est à 23h14:18, ce qui correspond assez bien a l’heure de la modif de sonde de température dans cuisine
_the descent is at 11:14:18, which corresponds quite well to the time of the temperature probe in the kitchen_

pour info, l'année dernière, j'ai utilisé et modifié de nombreuses fois l'intégration et, après avoir vérifié l'ensemble de l'année, je n'ai aucune consommation négative telle que celle-ci
_for info, last year, I used and modified integration many times and, after checking the whole year, I have no negative consumption such as this one._

merci à toi,
_Thank you,_
Stéphane

Installed version Versatile Thermostat 6.4.1 
Home Assistant :
Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Interface utilisateur 20241002.4

**Comment by jmcollin78** [comment]
Hello @SRI44760 ,

Thank you for your report and the details. There was already an issue with the same problem. But it has not been reproduce and the closed: https://github.com/jmcollin78/versatile_thermostat/issues/485

I will keep your open and make further investigations.

**Comment by HiFuGa** [comment]
Hello,

I have maybe the same problem.

yesterday evening, I checked the settings on few devices and their values « energy » have been reseted.



![IMG_7005](https://github.com/user-attachments/assets/1610358b-dcfb-468c-9330-24167d037972)

![IMG_7008](https://github.com/user-attachments/assets/d7b0c83e-09d9-4800-b172-01f9fecaf7bc)


Only the two devices I didn’t check didn’t get their energy value reseted.

![IMG_7006](https://github.com/user-attachments/assets/ac13306f-bae6-4d6f-9e03-b1201c70cdb1)

**Comment by jmcollin78** [comment]
Hello @HiFuGa ,

> yesterday evening, I checked the settings on few devices and their values « energy » have been reseted.

Do you have change the VTherm configuration ?

**Comment by jmcollin78** [comment]
Hello @HiFuGa @SRI44760 , 

I have built a specific beta release with some logs to try to understand what happens (I don't have the issue on my side but I don't really use the energy calculated) : https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.6.1.beta1

To install a beta release, you should explicitly ask for this release in HACS.

After installing this beta release, you should update your logger.yaml file as describe in the release note, restart and when you find the issue then send me the logs when the energy have changed (so around the time you change the configuration).

Thank you  !

**Comment by SRI44760** [comment]
de mon coté, je viens d'installer la version beta,
je n'ai par contre pas compris où récupérer les logs, j'ai activé les journaux sur l'intégration pour le moment, je ne sais pas si c'est mélangé dans le reste des logs CORE ou ailleurs 

merci à toi,

On my side, I just installed the beta version,
I didn't understand where to retrieve the logs, I've activated the logs on the integration for the moment, I don't know if it's mixed in the rest of the CORE logs or elsewhere 

Thank you,

**Comment by jmcollin78** [comment]
The logs are available in the config directory. The file is named: homeassistant.log. You should install VSCode or Samba plugin to get direct access to this directory.

**Comment by SRI44760** [comment]
bonjour,
j'ai fait un test ce matin de modifier le paramètre TPI dans la configuration centrale, j'ai eu 2 radiateurs qui sont repartis dans le négatif quelques minutes après,
j'ai aussi les logs, dis moi si tu est intéressé pour que je les envoi ou si ce que tu a est suffisant.
--

Hello,
I did a test this morning to change the TPI parameter in the central configuration, I had 2 radiators that went back into the negative a few minutes later.
I also have the logs, tell me if you're interested in sending them or if what you have is enough.

**Comment by jmcollin78** [comment]
Hello,

Here you have a beta release that seems to fix the issue: https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.6.1.beta2

Can you please give it a try ?

**Comment by SRI44760** [comment]
Hello,
the update is made by me,
I'm doing some editing tests and I'll keep you up to date
Thank you.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.6.1

**Comment by SRI44760** [comment]
bonjour, avec la version beta d'hier,
et après plusieurs modifications de paramètres,
je n'ai eu aucun problème sur ma courbe de consommation

merci à toi

Hello, with yesterday's beta version,
and after several parameter modifications,
I didn't have any problems on my consumption curve.

Thank you.
Stéphane

**Comment by jmcollin78** [comment]
Du coup j'ai releasé !
