### ISSUE TITLE
Bug regulated temperature and preset mode 

### ISSUE THREAD

**Issue by Emixam91** [jmcollin78/versatile_thermostat#601]
Good morning, 

here is my problem, following the addition of radiators working with Voltalis, I have an error which keeps coming back: 
"This error comes from a custom integration

Logger: custom_components.versatile_thermostat.thermostat_climate
Source: custom_components/versatile_thermostat/thermostat_climate.py:201
integration: Versatile Thermostat configuration (documentation, issues)
First occurred: 10:44:10 (5 occurrences)
Last recorded: 10:46:10

VersatileThermostat-Kitchen - don't send regulated temperature cause VTherm target_temp (None) is None. This should be a temporary warning message."

I'll show you the example of the kitchen, but the problem is the same on the others. 
In addition, the presets are not accessible, it says "presets" but I cannot select one even though they are indeed setting.

I would still like to point out that out of my 5 radiators, only one works correctly, the first that I added.

Thank you in advance and see you soon.

**Comment by jmcollin78** [comment]
Sadly you don't respect the issue template. Sometime I wonder why people think to not respect this.
So I can't help you.

**Comment by Emixam91** [comment]
Bonsoir,

Il s'agit de mon premier post et je ne sais pas à quoi correspond le 'modèle'. Ni quelle est son utilité.
Je vois d'après vos dire "Parfois, je me demande pourquoi les gens pensent ne pas respecter cela." que cela vous agace et j'en suis désolé.

**Comment by Emixam91** [comment]
Ceci dit ça ne vous empêchez pas d'être poli et de dire bonjour, ce qui ne nécessite pas de grandes connaissances informatiques.

Cordialement.

**Comment by jmcollin78** [comment]
Hello @Emixam91 ,

L'idée ce n'était pas d'être désagréable et c'est tombé sur toi, c'est pas de chance et j'en suis sincèremenet désolé. Lorsque tu crées une issue tu as un sorte de formulaire à remplir. Ca ressemble à ça:
```
<!-- This template will allow the maintainer to be efficient and post the more accurante response as possible. There is many types / modes / configuration possible, so the analysis can be very tricky. If don't follow this template, your issue could be rejected without any message. Please help me to help you. -->

<!-- Before you open a new issue, search through the existing issues to see if others have had the same problem.

If you have a simple question or you are not sure this is an issue, don't open an issue but open a new discussion [here](https://github.com/jmcollin78/versatile_thermostat/discussions).

Check also in the [Troubleshooting](#troubleshooting) paragrah of the README if the aswer is not already given.

Issues not containing the minimum requirements will be closed:

- Issues without a description (using the header is not good enough) will be closed.
- Issues that don't follow this template could be closed

-->

## Version of the custom_component
<!-- If you are not using the newest version, download and try that before opening an issue
If you are unsure about the version check the manifest.json file.
-->

## Configuration

<!-- Copy / paste the attributes of the VTherm here. You can go to Development Tool / States, find and select your VTherm and the copy/paste the attributes. Surround these attributes by a yaml formatting ```yaml <put the attributes> .... ```
Without these attribute support is impossible due to the number of configuration attributes the VTherm have (more than 60). -->
```

Comme beaucoup comme toi, ne prennes pas la peine de le remplir

**Comment by Emixam91** [comment]
Bonjour @jmcollin78,

Pas de soucis, je comprends ça, j’ai manqué de vigilance lors de l’ouverture de cette issue !
J’en suis tout à fait conscient, j'utilise déjà l’intégration Voltalis qui est de vous et j’étais intervenu pour résoudre un soucis d’un autre utilisateur, j’ai pu constater votre implication. 

Dans tout les cas merci de votre retour, je vais prendre le temps de lire et créer une issue avec toutes les informations nécessaires.

**Comment by jmcollin78** [comment]
>  j'utilise déjà l’intégration Voltalis qui est de vous

L'intégration Voltalis n'est pas de moi. Je ne la connais pas du tout.

**Comment by Emixam91** [comment]
Oh oui mince erreur de ma part ! 

Je tiens à vous dire que mon problème est résolu, l'entité de présence et celle de température extérieure semblaient renvoyer de mauvaises informations. Une fois modifiées, tout est rentré dans l'ordre et tout semble fonctionnel.

En tout cas merci à vous pour votre excellent travail et bonne continuation.
