### ISSUE TITLE
Can't adjust TPI coef_ext value if the digit 0 is entered after the dot.

### ISSUE THREAD

**Issue by swknf** [jmcollin78/versatile_thermostat#605]
Hi,

I'm trying to modify coef_ext in TPI configuration.
Either in Central Configuration or individually in each vtherm.

And I expect to be able to set value like the default one such as 0.01 or 0.02

But I observe that I can't enter some value that contains 0 after the dot.
so the minimal value I can set i 0.11
vlaue like 0.01->0.09 or 0.10 0.20 can't be entered.
you cant set 0.11->0.19 / 0.21->0.29 etc...

This behavior occurs in current 6.6.0 ( just upgraded ) but I observed this in all previous version that I used ( Verstatile since 6.4.0 )

**Comment by jmcollin78** [comment]
Hi,

Yes this is a bug in the UI and it is not under control of VTherm. You have to cpy/paste the value to set it as you need.
