### ISSUE TITLE
For some reason versatile thermostat changes temperatures on it's own.

### ISSUE THREAD

**Issue by tomtom13** [jmcollin78/versatile_thermostat#615]
Me again ;) 

Sooooo. I've left the versatile thermostat running on it's own, with simple schedule setting it's desired temperature.
Schedule is:
0:00 - heat @ 21C
2:00 - frost protection preset (that preset is at 10C)
8:00 - heat @ 21C
20:00 - heat @ 23C

And for some odd reason I get this behavior from the thermostat
<img width="554" alt="Screenshot 2024-11-07 at 23 27 36" src="https://github.com/user-attachments/assets/44014f75-f294-40b7-9f4a-2a1f4a98eb6c">

The configuration is that: 
- there is a single central configuration.
- there is a single thermostat controlling TVR over a climate.

Please advise on how I shall extract the configuration to attach it here if required.

Just a simple update:
After writing this post I decided to lower the temp to 23C as intended, and what happened was that thermostat just self changed to 29C. 
<img width="1231" alt="Screenshot 2024-11-07 at 23 51 17" src="https://github.com/user-attachments/assets/122dbb8a-2580-457c-99af-37a26c18716c">

**Comment by Zsoltt-dom** [comment]
Hi!
I have the same issue. It changing the target temperature on it's own.

**Comment by jmcollin78** [comment]
> Please advise on how I shall extract the configuration to attach it here if required.

as described in documentation: https://github.com/jmcollin78/versatile_thermostat/blob/main/README.md#custom-attributes



> And for some odd reason I get this behavior from the thermostat
> <img alt="Screenshot 2024-11-07 at 23 27 36" width="554" src="https://private-user-images.githubusercontent.com/22304458/384172652-44014f75-f294-40b7-9f4a-2a1f4a98eb6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMDMzNzYsIm5iZiI6MTczMTEwMzA3NiwicGF0aCI6Ii8yMjMwNDQ1OC8zODQxNzI2NTItNDQwMTRmNzUtZjI5NC00MGI3LTlmNGEtMmExZjRhOThlYjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDIxNTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YTI4NGQ4ZDYyMjI5NThiZDBmMGRmMjAwYzkwYjUwYjBlNjFlMThkZGJkOWRhYjgyMjMwNjY5YTZkMzQwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wwir7MGBLFclTNMTDr2ehM3TJhhoCLNGnkCiHirxc7Y">

What is the yellow and blue line ? I suppose that orange is when the heater heats ?
What do think is odd in this graph ?

> After writing this post I decided to lower the temp to 23C as intended, and what happened was that thermostat just self changed to 29C.

I will repeat with my word: you change manually the target temperature to 23°C (with the button of UI Card I think) and then the VTherm displays 29°C as target temperature. Is that correct ?

If yes, can you send me the logs when this happens please ? I suppose you have logs saying:
```
Underlying climate <name> have changed. new_hvac_mode is ...
```

**Comment by tomtom13** [comment]
The graphs is default graph when one click more info and then goes to graph icon:
Yelow - a setpoint on thermostat
Blue - a room temp from temp sensor
Orange fill - when the thermostat indicates that it's "heating"
As per:
<img width="453" alt="Screenshot 2024-11-08 at 22 20 15" src="https://github.com/user-attachments/assets/0066bc6f-e6e2-4653-aa27-58a74ae9d417">

'''
I will repeat with my word: you change manually the target temperature to 23°C (with the button of UI Card I think) and then the VTherm displays 29°C as target temperature. Is that correct ?
'''
No.
1. schedule set the temp to 23C
2. Thermostat self set it's setpoint to 25.5C
3. I've intervened when I've notice that it's to toasty and set the temp via buttons in the UI temp to 23C as I desire
4. After several minutes thermostat self set to 29C


HOWEVER:
If you look at the graphs - the thermostat self set's to different temperatures on it's OWN. In the first graph I've had NOT input of any kind into it. The thermostat is not connected to any automation other than the schedule. Thermostat is NOT exposed to home kit, or other users.
This thermostat is (or more acurately: was) more or less sandboxed. 

I shall attempt to find the logs for you, however the thermostat was removed and replaced by other solution that I'm testing now (to eradicate TADO).

**Comment by jmcollin78** [comment]
You may have old logs in old homeassistant.log.x files 

<img width="174" alt="Capture d’écran 2024-11-08 à 23 52 35" src="https://github.com/user-attachments/assets/888a894e-10a1-491e-ba1e-b50f198f42fd">

**Comment by tomtom13** [comment]
nope - nothing that far back.

**Comment by jmcollin78** [comment]
Hello bug is reproduced. I will do a patch rapidly.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.6.2

**Comment by theyv** [comment]
![Image](https://github.com/user-attachments/assets/3b4324dd-997d-4eb5-a182-a1a844684535)

Same thing happened to me. 

At 19:36, I changed the temperature on the thermostat in the home office.

At 19:40, the thermostat in the living room (which was off at the time) suddenly set itself to 25.5°C.

I then turned it on, set it manually to 23°C, and switched the mode to cooling.

About 10 seconds later, it jumped back to 25.5°C.

I changed it again to 23°C—and this time it stayed at that temperature.
However, I’ve seen it revert on its own in the past.

For context: the "Follow underlying temp change" option is enabled in both rooms, though I tried disabling it and it didn’t seem to make a difference.

I haven’t touched the physical AC remote.

**Comment by tomtom13** [comment]
@theyv I think your issue alto looking similar might be "unrelated". 
This issue WAS as follows:
you set the VHT to OFF -> it set's the TRV to frost protection and OFF state.
schedule / user comes in and changes the temperature set point on the VHT, WITHOUT switching it back on.
VHT sheepishly, would set the new temperature on the thermostat (it would not switch it back on !) 
TVR would be there like "hmmm somebody gave me a new set point - let's switch ourself back on because you know they might want this stupid setpoint to be maintaned" and would switch from OFF to HEAT.
VHT would look at the thermostat: "wait a minute, somebody switched it back to HEAT, it means that we should switch back on as well". 

And that would happen if YOU, open window detection, schedule switched the VHT off.
