### ISSUE TITLE
Vtherm over valve "Last seen" seems to become inconsistent then serurity mode is activated

### ISSUE THREAD

**Issue by Kumalo** [jmcollin78/versatile_thermostat#620]
Version v6.6.2

----
I have two vtherm over valve on a sonoff trvZB with an external temperature in the same room : the problem only happens on one of theses.

The _last seen temperature_ switches to the last time when the temperature has changed and not more the last time the temperature has been received

On the screenshot's example, the last seen is 07:38 between 07:39 and 07:57 and become 05:51  between 07:57 and 08:18

"08:18" is the last time of modified temperature

=> the security mode is set to  true  and I have to restart to unlock the state.

---

* screen shot:
![image](https://github.com/user-attachments/assets/e746ae43-ef6d-441b-9940-2c867cc12fe4)

![{22189047-24AC-45F5-B281-A883DD1AF54B}](https://github.com/user-attachments/assets/0d5fc20a-53eb-4633-bf32-4ecd5c71da9b)

**Comment by jmcollin78** [comment]
Hello @Kumalo ,

Sorry but I will not look at your issue. There is an issue template and you choose to not respect it and I will loose my time asking for details. So please, check the README (in French) to help with security mode and if you still have the issue open a correct issue with the informations required.

**Comment by Kumalo** [comment]
Hello @jmcollin78 

I apologize for the model : I will do better next time.

I had read the readme but I was confused by the "Minimum Power Percentage" in combination with the external temperature sensor (See [message](https://forum.hacf.fr/t/nouveau-thermostat-type-proportionnel-avec-gestion-des-presets-portes-et-fenetres-detection-de-mouvement-gestion-de-presence-et-surconsommation/19160/2041))

The case did not happen again this week with active logs.

On the other hand, what I still can't understand is why the the last temperature date is 07:38 between 07:39 and 07:57 and becomes older 05:51 between 07:57 and 08:18: It seems that the value of last temperature date has become that of last external temperature date.

I will continue to monitor and I will tell you if it happens again

Regards,

**Comment by jmcollin78** [comment]
Hello @Kumalo,

You should avoid to post the same issue at two places: I read both and I answer all post, so this make me the double work (the time I understand I already make a response elsewhere).

So I will close this one.
