### ISSUE TITLE
[Feature request] - Add an option to disable the "VTherm follows its underlying setpoint" in `over_climate`

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#628]
In `over_climate` many issues are due to the fact that VTherm follows its underlying. When this arrives, what ever the reason is, the VTherm goes to manual mode (no preset) and set the target to the value to the underlying target temperature value.

This lead to misunderstanding, misconfiguration and bad feeling by the user that don't understand what happens. Only checking logs can show the is due to the underlying changes.

The underlying can change itself because (non exhaustive causes found) :
1. it have self regulation algorithm,
2. it detects the windows is open,
3. a user change manually the setpoint directly on the device (with a remote command or by turning the TRV),
4. ...

To avoid that, we should have a switch entity associated with the `over_climate` VTherm device named 'follow underlying temperature change'. When this switch is enabled, VTherm will take care of the temp setpoint change made directly on the physical device, else not.

As an impact, it will be then possible to have a misalignment between what is currently running on the device and what is programmed on VTherm. Each time VTherm will send the setpoint (during self-regulation or preset change), it will re-align the set points. So this misalignment should be a temporary situation.

VTherm will always continue to follow the on/off made directly on the physical device.

**Comment by ooii** [comment]
Totally agree with this behavior. In my opinion, the goal of VTherm is to stop using the underlying. So changing user values with those of the underlying do not make sense for me.
Thanks @jmcollin78 for this new feature.

**Comment by carlolars** [comment]
Auto start/stop and disabled "follow underlying climate" using this new switch works as expected for me. (my problem with auto off and underlying climate described here https://github.com/jmcollin78/versatile_thermostat/discussions/603#discussioncomment-11219256)

Thanks for the quick resolution, and lots of thanks for all the time you put into this project!

**Comment by jmcollin78** [comment]
> auto off and underlying climate described here [#603 (comment)](https://github.com/jmcollin78/versatile_thermostat/discussions/603#discussioncomment-11219256))

This is fixed by #653 (in the next release)
