### ISSUE TITLE
Expose the humidity of an underlying in over_climate VTherm is available.

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#638]
### Discussed in https://github.com/jmcollin78/versatile_thermostat/discussions/633

<div type='discussions-op-text'>

<sup>Originally posted by **ZaGaPonG** November 14, 2024</sup>
Hello @jmcollin78,

First, thanks for this really good addon 🥇 

Could you envisage to manage to "current_humidity" attribute from climate entity please?

In fact, as my room temp sensors added to each thermostat deliver humidity as well that could be nice if we could link this humidity sensor to the climate entity. I have a climate entity delivered by Tado addon which display the twice: current humidity and current temp.

Exemple with the Tado climate on the top and climate entity created with your addon below:
<img width="336" alt="image" src="https://github.com/user-attachments/assets/ff8834b3-07e1-4138-88d5-f595fce38001">

Thanks in advance
</div>

**Comment by jmcollin78** [comment]
Hello @ZaGaPonG,

Can copy/paste the attribute of your underlying climate entity which shows the humidity attribute ?
It is available in Developement Tools / State.

**Comment by ZaGaPonG** [comment]
Hello @jmcollin78,

`hvac_modes:
  - "off"
  - auto
  - heat
  - cool
  - heat_cool
  - dry
  - fan_only
min_temp: 16
max_temp: 31
target_temp_step: 1
fan_modes:
  - medium
  - auto
  - low
  - high
preset_modes:
  - away
  - home
swing_modes:
  - vertical
  - horizontal
  - both
  - "off"
current_temperature: 19
temperature: 19
current_humidity: 66.4
fan_mode: auto
hvac_action: "off"
preset_mode: home
swing_mode: "off"
offset_celsius: 0
offset_fahrenheit: 0
default_overlay_type: MANUAL
default_overlay_seconds: null
friendly_name: Climatisation
supported_features: 441`

**Comment by jmcollin78** [comment]
Will be in the next release.

**Comment by ZaGaPonG** [comment]
Thank you very much for reactivity 👍

**Comment by jmcollin78** [comment]
There is the 6.8.0 beta that have this feature. It could be great if you give it a try. I have no way to test that

**Comment by ZaGaPonG** [comment]
Just installed this version but a didn't see any new field into the conf to add the humidity sensor.

**Comment by jmcollin78** [comment]
No, there is no humidity sensor. You just want that VTherm expose the humidity of the underlying climate. That is what I do. That is what I understand from our discussion:

![Capture d’écran 2024-11-17 à 19 23 17](https://github.com/user-attachments/assets/60bbc486-3c86-4010-bacd-d4d68232d354)

As said in this discussion, I will not add a humidity sensor in VTherm. Too much complications for a very small added value

**Comment by ZaGaPonG** [comment]
Ok, I have not well understand, sorry.
So, what you mention working well. Just tested
