### ISSUE TITLE
what setting to put in device power when thermostat over multiple switches

### ISSUE THREAD

**Issue by alexinthesky** [jmcollin78/versatile_thermostat#639]
Hi I have a thermostat over switch with multiple switches ( both controlling 2000W electric heaters.) what should I set in the termostat's "device power' to get an accurate report in the energy sensor  ?

**Comment by jmcollin78** [comment]
<img width="820" alt="Capture d’écran 2024-11-15 à 23 19 39" src="https://github.com/user-attachments/assets/da9f5d6d-ae01-45b6-89f4-1e1c5442ad9a">
