### ISSUE TITLE
Zero after the decimal point

### ISSUE THREAD

**Issue by tiluxus** [jmcollin78/versatile_thermostat#652]
## Versions
Home assistant 2024.11.2
Versatile Thermostat : 6.7.0

## Configuration
My VTherm attributes are the following:
hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 35
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 18
temperature: 18
hvac_action: heating
preset_mode: comfort
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 13
eco_temp: 16
boost_temp: 19
comfort_temp: 18
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 10.3
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: comfort
saved_target_temp: 18
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-11-17T13:10:24.387282+01:00"
last_ext_temperature_datetime: "2024-11-17T13:12:00.095014+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: 0.15
total_energy: 5190.08
last_update_datetime: "2024-11-17T13:13:43.822810+01:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
ema_temp: 18
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_entities:
  - switch.flush_pilot_5
  - switch.flush_pilot_4
on_percent: 0.15
power_percent: 15
on_time_sec: 46
off_time_sec: 253
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.02
friendly_name: Thermostat - Salon
supported_features: 401

## Bug description
In thermostat configuration, when we want to modify value with decimals, zero cannot be entered immediately after the decimal point unless it is followed by an already existing digit. If you do so, the decimal point and decimals are erased. Only the units remain.

## Replicating the bug
In example, to indicate 0.02
 - type 0.0
 - it deletes .0
 - only 0 is displayed

## A way around the bug
In example, to indicate 0.02 
  - type 0.2
  - move the cursor to just before the 2 and then type 0.
  - 0.02 is now displayed.

**Comment by jmcollin78** [comment]
Hello, yes this is knwon bug of the UI and I can't do nothing for this. What you can do is to copy/paste the value you want to set.
