### ISSUE TITLE
The list of valve seems incorrect + add Sonoff installation informations in README.

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#656]
I had a working setup with the the Sonoff TRVZB with firmware 1.1.X and using a switch as thermostat. 
I have upgraded the firmware to 1.2.1 and I'm tying to setup the thermostat using climate + the SONOFF TRVZB mode but nothing really happens anymore in my system. 

For example, I don't understand why in this situation the heating is not on 
![screenshot_001786@2x](https://github.com/user-attachments/assets/a439087a-f622-4534-9aa6-d7a3a6c84784)

This is my first attempt to setup Versatile Thermostate, so might be missing something trivial

UPDATE: 

Using a valve thermostate and using the valve opening degrees as underlying managed to turn on the boiler + the valves on my thermostates. 

![screenshot_001787@2x](https://github.com/user-attachments/assets/ad0e1e41-f6a5-49d5-8caa-cd571bf26f6e)

_Originally posted by @gbasile in https://github.com/jmcollin78/versatile_thermostat/issues/645#issuecomment-2491348958_

**Comment by eflye** [comment]
@gbasile dit you enable manually Valve closing degree and Valve opening degree on your trv entity in HomeAssistant. You have to do it first in order to have Sonoff TRV native support on Vth.

**Comment by jmcollin78** [comment]
ok @eflye , this is an important information, by default thoses entities are not visible I understand

**Comment by gbasile** [comment]
Thanks for creating a dedicated issue for my problem 🙌 

> @gbasile dit you enable manually Valve closing degree and Valve opening degree on your trv entity in HomeAssistant. You have to do it first in order to have Sonoff TRV native support on Vth.

I have missed this piece of information. Can you point me to the right direction?

**Comment by jmcollin78** [comment]
Thank you the beers ! Cheers 🍻 

You have to go to Parameters / Devices. Find you Sonoff device and click on "more attributes" (or something like that) . Then you will able enable the missing attributes.
Example:
<img width="287" alt="Capture d’écran 2024-11-21 à 22 23 59" src="https://github.com/user-attachments/assets/ffeec4f3-1747-4804-b772-e3880b4e2e08">

**Comment by gbasile** [comment]
I think I have misunderstood the previous message (I was looking for an attribute called`manually valve closing degree`)

In my device the following are available, without any manual change from my side:
- Valve opening degree
- Valve closing degree

These attributes are the ones that currently are driving the TRV when configured in `valve mode`. For some reason when I configure the thermostate as `climate mode` with the sonoff configuration enabled, the. system is not working anymore

![screenshot_001789@2x](https://github.com/user-attachments/assets/002adbc6-b652-4efc-ad75-03b338c00992)

**Comment by jmcollin78** [comment]
ok. Then can you give me the attribute of the VTherm ? (see: https://github.com/jmcollin78/versatile_thermostat/blob/main/README.md#custom-attributes)

**Comment by eflye** [comment]
maybe Diagnostic one should be enabled? In order to get curent value <img width="341" alt="image" src="https://github.com/user-attachments/assets/1844a4eb-4e7c-48cb-ae3e-ecbf70a68335">
It creates **sensor**.<your trvname>_valve_opening_degree and **sensor**.<your trvname>_valve_closing_degree
wheras the one you see on the Configuration are 
**number**.<your trvname>_valve_opening_degree and **number**.<your trvname>_valve_closing_degree

Which want do you use @jmcollin78

**Comment by gbasile** [comment]
@eflye I have enabled them now

![screenshot_001790@2x](https://github.com/user-attachments/assets/51c4a139-4e23-491d-b876-87336b5b86e6)

**Comment by jmcollin78** [comment]
Oooh there is a problem:
```
underlying_entities:
  - climate.mqtt_trv_1_living_room

...
underlying_sonoff_trvzb_entities:
  - number.mqtt_trv_2_office_valve_opening_degree
  - number.mqtt_trv_2_office_valve_opening_degree
  - number.mqtt_trv_2_office_valve_opening_degree
  - number.mqtt_trv_2_office_valve_opening_degree
  - number.mqtt_trv_1_living_room_valve_opening_degree
  - number.mqtt_trv_1_living_room_valve_opening_degree
  - number.mqtt_trv_1_living_room_valve_opening_degree
```

This should be not possible. there is trv2 and too many `underlying_sonoff_trvzb_entities`.

This is clearly a bug. I think you will have to recreate it from scratch.

**Comment by gbasile** [comment]
I'm happy to give it and recreate the entire configuration from scratch. 
Just to be on the same page, I will: 
- Remove all the devices from the Versatile Thermostat integration
- Recreate a central configuration and the single thermostats

I will not: 
- Unpair/Pair again the MQTT devices
- Factory reset the physical devices

Is that correct?

**Comment by jmcollin78** [comment]
No need to recreate the central configuration. Only the VTherm which uses the Sonoff TRVZB (in beta). And only the one who is incorrect. No need to removes the others if you have and if they works fine

The others points are correct.

**Comment by gbasile** [comment]
Well, in that case I don't think much will change:  this Thermostat has been recreated now as part of the effort of understanding the problem with the climate mode.

Basically my journey today has been: 
- configure the thermostat with climate + sonoff config (not working)
- delete this thermostat and recreate it with valve (working)
- [as part of the investigation for this issue, 30 minutes ago] delete the thermostat and recreate it with climate + sonoff in order to share the attributes

**Comment by jmcollin78** [comment]
Nice but there is a bug in the list.

**Comment by gbasile** [comment]
Exposing `xxx_opening_degree` and `xxx_closing_degree` from the diagnostic makes the thermostat valves to move in the system. 

I wonder whatever we should: 
- Investigate if possible to avoid the manual step of exposing these attributes 
- Update the documentation and/or the UI of the sonoff config to warn the user about this requirement

**Comment by gbasile** [comment]
There are still some behaviours that I don't fully understand. Are these as expected or not?

1. I turn the thermostat to 24 degree (1.6 higher then room temperature)
2. Valves opens to 100% ✅ 
3. Thermostat is not requesting for heating ❌ 
4. Boiler is off ❌ 

Screenshot for more context
![screenshot_001794@2x](https://github.com/user-attachments/assets/4a96ae1c-729b-4cb9-a2b5-d38568f2f46d)

**Comment by jmcollin78** [comment]
> * Update the documentation and/or the UI of the sonoff config to warn the user about this requirement

Yes !

**Comment by jmcollin78** [comment]
> 3\. Thermostat is not requesting for heating ❌

Yes, there is still a bug on this reported in the main thread. It is requested for heat if the valve is open, but the display seems wrong.

> 4\. Boiler is off ❌

Yes this is a consequence of the point /3. The boiler is started if VTherm are requested for heat.

**Comment by jmcollin78** [comment]
Maybe we can keep this thread only for documentation and valve list and come back the main thread because you have solve your main issue. Your points can interest the others.

**Comment by gbasile** [comment]
Regarding the valve list: 

- Yesterday night I have clean-up the configuration to remove the duplicates (set state)
- Today the list is corrupted again 

I am able to reproduce in this way: 
1. Clean the duplications and set new state
2. Reload the VTherm thermostat from the integration page
3. Duplication re-appear again

**Comment by msd3287** [comment]
Hi,
I have Sonoff TRVZB in 1.2.1 release too and I note that now, I'm quite sure it worked fine before, If I manually change the wished temperature on the valve itself, this change is not reflected on the associated versatile Thermostat. Same on the Versatile Thermostats of my daughter's house (different HA instance).
If I change the wished temperature on the V-th, it's well change on the valve.

**Comment by gbasile** [comment]
> If I manually change the wished temperature on the valve itself, this change is not reflected on the associated versatile Thermostat.

I have the same issue as well

**Comment by jmcollin78** [comment]
Hello @gbasile , @msd3287 ,

Did you check the "Follow underlying temperature change" entity (in the VTherm device) ?

**Comment by gbasile** [comment]
![screenshot_001799@2x](https://github.com/user-attachments/assets/c65a21c0-7ee0-4254-bb04-ac160d8e8a4b)

I guess this is the setting you are talking about, right? In that case, yes

**Comment by jmcollin78** [comment]
No. I'm talking about this one:
![Capture d’écran 2024-11-24 à 16 28 43](https://github.com/user-attachments/assets/a1bc259b-7922-43a1-8699-050b50919d09)

**Comment by gbasile** [comment]
ah, I was not aware of that control in the service 😓 
Of course IT DOES WORK when that option is set.

**Comment by jmcollin78** [comment]
It is a recent addition: https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.7.0

That is because you don't read the release notes 😉 (and it is badly documented that is true)

**Comment by msd3287** [comment]
![image](https://github.com/user-attachments/assets/4af7fed3-9b32-45d8-9528-11d783269ae1)

![image](https://github.com/user-attachments/assets/94a8af1f-b67b-45eb-a089-54cfeb6c391f)

**Comment by jmcollin78** [comment]
> ![image](https://private-user-images.githubusercontent.com/55650518/389288853-4af7fed3-9b32-45d8-9528-11d783269ae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0Njc4NjEsIm5iZiI6MTczMjQ2NzU2MSwicGF0aCI6Ii81NTY1MDUxOC8zODkyODg4NTMtNGFmN2ZlZDMtOWIzMi00NWQ4LTk1MjgtMTFkNzgzMjY5YWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDE2NTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZDBhYmE1MGNmYjI5ZDI0NTQwNjg1ZjhhYjc0ZWFhNjIyNmJjY2U1OGMzOGYzNjQ2ODVkNjNiNzZiZDAyNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mkfCIZTzDOnT8P-gs-upW6MJqNK5BKSkK8eKYq_HwZE)
> 
> ![image](https://private-user-images.githubusercontent.com/55650518/389288934-94a8af1f-b67b-45eb-a089-54cfeb6c391f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0Njc4NjEsIm5iZiI6MTczMjQ2NzU2MSwicGF0aCI6Ii81NTY1MDUxOC8zODkyODg5MzQtOTRhOGFmMWYtYjY3Yi00NWViLWEwODktNTRjZmViNmMzOTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDE2NTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZDY2MWY4YWIyNTlhM2IyOTc3YjUxYmYyNTQzZTIwMTU1MDdiY2Y4YzU0YjU1Y2U3NGM1MDUyM2UwOGUwY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-BPZO2YaOmDob07HcHLP9_0pxRLkJ-G2taBqH4iqZMw)

T'as un peu squatté le thread là. Celui-là c'était pour la liste qui ne s'affichait mal. Je vais le fermer dans qqes heures et ta question va disparaitre. Attend, je vais faire une mise à jour importante qui corrige pas mal de choses. Avec un peu de chance ça va marcher maintenant.

**Comment by msd3287** [comment]
Ok, merci  :)

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.8.0
