### ISSUE TITLE
central boiler doesn't work anymore woth 6.8.0beta

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#661]
The central boiler is no more activated event if the VTherm have hvac_action.

This is the case since 6.8.0beta7 and maybe before.
The number of active VTherm (in a specific entity attached to the Central configuration)

More informations here: https://github.com/jmcollin78/versatile_thermostat/issues/645#issuecomment-2496246628

**Comment by tbrasser** [comment]
It seems to work only sometimes for the new over_climate with the new trvzb settings (im on latest beta)

other existing vtherms seem not to have the issue

**Comment by jmcollin78** [comment]
Seems a configuration error for some of you. See https://github.com/jmcollin78/versatile_thermostat/issues/645#issuecomment-2498121858

**Comment by tbrasser** [comment]
I have configured my beta8 entities correctly. Mode is heating, valve is open 4%, number of devices for central boiler stays at 0

**Comment by jmcollin78** [comment]
The fix is coming.

**Comment by Hubert2208** [comment]
I'm Using HmIP with the over Climate feature. Since 6.8.0.beta9 central boiler isn't working anymore. Think this is an issu due the circumstance that the underlying HmIP doesn't have HVAC_Action. Central boiler works with no issue till 6.8.0.beta8.

**Comment by jmcollin78** [comment]
> I'm Using HmIP with the over Climate feature. Since 6.8.0.beta9 central boiler isn't working anymore. Think this is an issu due the circumstance that the underlying HmIP doesn't have HVAC_Action. Central boiler works with no issue till 6.8.0.beta8.

You should post another issue. This one is closed and the fix is working. You certainly ahve another issue or configuration issue. Give me also you attributes : https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/reference.md#custom-attributes

**Comment by Hubert2208** [comment]
Hi, thanks for your answer.
I open a new issue.

greetings
Hubert
