### ISSUE TITLE
Disabling auto-start/stop and the VTherm is off cause auto-start/stop 

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#662]
The case is the following:
1. put a VTherm in auto-start/stop,
2. wait for a stop,
3. disable auto-start/stop through VTherm UI Card,

What we observe: the VTherm stays OFF with reason auto-start/stop

What we want: the VTherm turns ON and restore its last state (preset, havc_mode) before it was turned off by the auto-start/stop feature.

**Comment by t0mb080** [comment]
Seems a bit similar to https://github.com/jmcollin78/versatile_thermostat/issues/653, although not exactly the same.

**Comment by jmcollin78** [comment]
Hello @t0mb080 ,

It is not the same and #653 is already fixed (available in the 6.8.0.beta pre-release). This one should have its own fix

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.8.1
