### ISSUE TITLE
Isssue when selecting a preset mode 

### ISSUE THREAD

**Issue by jhenninot** [jmcollin78/versatile_thermostat#670]
Hi,
I'm using Lovelace versatile thermostat card, but the issue is the same with the "standard" one.
When I select a preset mode :

![image](https://github.com/user-attachments/assets/6e9fe2b2-5076-4d3f-b2de-436973cea672)

the target temperature changes, but the preset mode is set to 'PRESET_NONE' (no icon) :

![image](https://github.com/user-attachments/assets/6b9fc6e4-9342-4a6a-91fd-ec0e8fe3cad5)

Looking at the code, I saw that the issue is caused by the target temperature change made by the code, which always set the preset mode to "PRESET_NONE" by the base_thermostat.py script :

![image](https://github.com/user-attachments/assets/9e3153b2-245d-40fb-9e60-624a6b8630eb)

I tried a few changes in the code that helps preventing this behaviour :

![image](https://github.com/user-attachments/assets/ab5befc3-ef13-4d50-9828-515399b34415)

This way, when the user is selecting a preset, it is set in a variable, and when the code is setting the target temperature, the preset mode is set to the one the user selected instead of being set to manual :

![image](https://github.com/user-attachments/assets/78994ca4-78dd-4d4c-8e48-06c1f6c7d576)

If the user manually selects a target temperature, the preset mode will be set to "PRESET_NONE"

**Comment by jmcollin78** [comment]
Hello @jhenninot 

Sadly you don't respect the issue template. So I don't what kind of VTherm you have nor the configured values for T°. What is your release ?

I use this feature 20 times per days, I'm very surprise this very basic feature don't work, but this can happens.

The method `async def async_set_temperature` is not used in preset change but only if you change the T° manually. The method used when you change the preset is `async_set_preset_mode` (which don't call `async_set_temperature`).

The change you made in your code shouldn' have fix the issue. Or I don't undersstand your explaination.

**Comment by jhenninot** [comment]
To provide more information:

- I use Hass OS 13.3 on a proxmox virtual machine
- I'm using the latest Versatile release (6.7.0)
- I only have one climate entity on Versatile, an it's an over switch thermostat with no absence nor window management.
- here is my climate entity status yaml : 

hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 25
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 20.8
temperature: 19.5
hvac_action: idle
preset_mode: comfort
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 7
eco_temp: 16.5
boost_temp: 20.5
comfort_temp: 19.5
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 3.5
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: comfort
saved_target_temp: 16
saved_hvac_mode: heat
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-11-28T09:02:53.727214+01:00"
last_ext_temperature_datetime: "2024-11-28T08:10:52.467079+01:00"
security_state: false
minimal_activation_delay_sec: 80
device_power: 1
mean_cycle_power: 0
total_energy: 2.76
last_update_datetime: "2024-11-28T09:03:59.147825+01:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: false
ema_temp: 20.39
is_used_by_central_boiler: false
temperature_slope: 3.78
hvac_off_reason: null
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_entities:
  - switch.nodon_rdc
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 900
cycle_min: 15
function: tpi
tpi_coef_int: 0.4
tpi_coef_ext: 0.03
friendly_name: Salon
supported_features: 401

When debugging, I saw that when you manually change the preset mode, it changes the target temp :

1/ the async_set_preset_mode_internal function calls the  _async_internal_set_temperature function :

![image](https://github.com/user-attachments/assets/10e4cbbb-eac4-4690-851c-f4a02182b630)

2/ then, the _async_internal_set_temperature function changes the target temperature :

![image](https://github.com/user-attachments/assets/4a28e3c9-7c31-4a0d-aa12-2787fd3aa7a6)

3/ then, for some reason, the async_set_temperature function is lauched (probably by home assistant itself because the temperature arribute is modified).

and this function sets the preset mode to "PRESET_NONE":

![image](https://github.com/user-attachments/assets/7c73b769-1c65-4626-a6af-2e8fe2113e52)

So, the purpose of my modification is:

1/ when a preset mode is manually selected, I store this preset in a dedicated variable:

![image](https://github.com/user-attachments/assets/f442227e-8df4-4c45-bced-27023e852c30)

2/ when the async_set_temperature funcrion runs, it detect is there's a preset mode choosen by the user and if so it ckecks it there is a chhosen preset, apply it, and clear the choosen_preset variable:

![image](https://github.com/user-attachments/assets/f2b867ad-8c69-48fe-bac2-8099db4afaac)

If there is no choosen preset (which means the temperature change is not due to a preset mode change), the preset mode is set to PRESET_NONE

I've tested it and it just works...

**Comment by jhenninot** [comment]
OK, I finally found what was really causing my issue :
I have a plug-in (Home-Assistant-Matter-Hub) that was interacting with the temperature setting....
I stopped using it and everything works fine now, without my code modification...
Thank you very much for your work on this nice tool !

**Comment by jmcollin78** [comment]
> I stopped using it and everything works fine now, without my code modification...
> Thank you very much for your work on this nice tool !

ok fine. I should have read all post before answering. I will then close the issue.
