### ISSUE TITLE
[FR] Expert self-regulation config per VTherm

### ISSUE THREAD

**Issue by 0verEngineer** [jmcollin78/versatile_thermostat#671]
**Is your feature request related to a problem? Please describe.**
I have quite a crazy expert self-regulation config and i eventually need another expert self-regulation config for another VTherm but this is not possible.

**Describe the solution you'd like**
Somehow be able to have a expert self-regulation per VTherm, over the UI or in the configuration.yaml

**Describe alternatives you've considered**
I think there is no other solution

**Additional context**

**Comment by jmcollin78** [comment]
Hello @0verEngineer ,

You are right, I have no other solution. I'm curious to know why you need 2 expert regulation with different parameters. Can you show me the both parameters you would like to have.

**Comment by 0verEngineer** [comment]
Hey, i don't need the second expert regulation at the moment, but it could be in the near future.
And because my expert regulation config is quite crazy i thought i will eventually need a second one: https://github.com/jmcollin78/versatile_thermostat/discussions/648

**Comment by jmcollin78** [comment]
I close this issue for now. Don't hesitate to reopen if needed.
