### ISSUE TITLE
[Feature Request] Use live electricity prices to override heating/cooling

### ISSUE THREAD

**Issue by vodkapmp** [jmcollin78/versatile_thermostat#675]
**Is your feature request related to a problem? Please describe.**
Sorta. Electricity prices vary a lot and all my heating/cooling is electric.

**Describe the solution you'd like**
I use the [Nordpool](https://github.com/custom-components/nordpool) integration which gives me my electricity prices live per hour, and my prices can change between being in the negative, and very expensive all in the same day.
I'd like for this integration to be able to use the live electricity price to not go hard on heating/cooling when the price is really high, and maybe go for a bit extra cooling/heating if the price is really cheap.

The Nordpool integration also gives you the electricity price for the entire day, and the next day. It could in theory look at prices over the day and change heating/cooling preemptively before a huge surge in costs to save money by using the home as a battery. 

**Describe alternatives you've considered**
Using an automation that checks the electricity price at the start of every hour, and if its over/under a specific value, it disables all schedules and manually overrides heating/cooling to either not do any heating/cooling when it's really expensive, or going full on heating/cooling if it's really cheap (or in the negative) to use the home as a battery. 
(this is what I'm currently doing)

**Comment by jmcollin78** [comment]
Hello @vodkapmp ,

To avoid too much complexity on Vtherm (this is already too much complex), i don't want to add too specific features like the one you propose.
You can always use the service (action) and the events to integrate the VTherm into your environment and needs.
