### ISSUE TITLE
TPI parameters "TPI_COEF_EXT cannot be modified properly

### ISSUE THREAD

**Issue by jeremushka** [jmcollin78/versatile_thermostat#681]
I have tried to tune the TPI_COEF_EXT through graphical interface and through YAML coed without success.

By default it is set at 0.01. I wanted to modified the value at 0.02. However, if you delete all the values you cannot enter a value less than 0.1 which is too much in my case.

seems the "." is a an issue to set up the value. However, no problem for the TPI_COEF_INT.

Regards,

**Comment by jmcollin78** [comment]
This is a bug in the UI and not in VTherm. You have to copy/paste the value

**Comment by maia** [comment]
As this bug has not been fixed in the past 12 months, do you happen to know if it's an open issue on the HA repo or if it still needs to be reported?
