### ISSUE TITLE
Increase the resolution of cycle time from minutes to seconds

### ISSUE THREAD

**Issue by Azimthz** [jmcollin78/versatile_thermostat#687]
**Is your feature request related to a problem? Please describe.**
In very small rooms 1 minute of cycle time will lead to a relatively powerful HVAC unit to overshoot the target temperature by several degrees.

**Describe the solution you'd like**
By increasing the resolution from minutes to seconds in the cycle time the HVAC unit will be able to stop sooner and thefore not overshoot the target temperature.

**Describe alternatives you've considered**
I tried to manually force the fan speed to 1 to ease out the temperature change but nevertheless it still overshoots when it needs to wait until the next cycle (worst case scenario 1min)

**Comment by jmcollin78** [comment]
Hello,

Having a cycle below one minute is totally useless. The temperature will never change with a resolution at the second.
If the case is to avoid overshoot the setpoint there is certainly others solution.

I don't know if you are in `over_switch` or not because you don't feel the issue template, but there is parameters that are there to avoid the overshoot (see TPI in README) or self-regulation if you are in `over_climate`.

**Comment by Azimthz** [comment]
Hi @jmcollin78 

Thanks for your answer. 
Sorry for not following the expected template, what happened was that I created a new feature request, because I assumed that increasing the resolution will be a new feature instead an issue request, and followed that template.

I reviewed the documentation before opening the request and I already set the self-regulation to strong (I'm over climate) and nevertheless I got overshoot by a significant margin just, for completeness here is my configuration. It's seems that for my particular use case even strong is not strong enough to not to overshoot.

It's just a relatively minor issue on a really exceptional component that improves my climate experience a lot. So even if it's marked as wont fix I just want to thank you for your work on this component. Keep it up!

## Version of the custom_component
6.7.0

## Configuration
My VTherm attributes are the following:
``yaml
hvac_modes: fan_only, dry, cool, heat, heat_cool, off
min_temp: 18
max_temp: 30
target_temp_step: 0.1
fan_modes: Auto, Silence, 1, 2, 3, 4, 5
preset_modes: none, frost, eco, comfort, boost
swing_modes: Off, Vertical, Horizontal, 3D
current_temperature: 19.8
temperature: 20
fan_mode: Auto
hvac_action: off
preset_mode: none
swing_mode: Off
is_on: false
hvac_mode: off
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 18
eco_temp: 18
boost_temp: 30
comfort_temp: 24
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 22
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 19.2
saved_hvac_mode: off
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: binary_sensor.sensor_h2_ventana_contact
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-12-06T12:44:08.769276+01:00
last_ext_temperature_datetime: 2024-12-06T12:43:09.793788+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0.18
last_update_datetime: 2024-12-06T12:44:08.770915+01:00
timezone: Europe/Madrid
temperature_unit: °C
is_device_active: false
ema_temp: 19.94
is_used_by_central_boiler: false
temperature_slope: -1.8
hvac_off_reason: null
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.daikin_habitacion_2
is_regulated: true
regulated_target_temperature: 18.5
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: -14.480781249999998
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: true
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
follow_underlying_temp_change: false
friendly_name: Habitacion 2
supported_features: 441
```

**Comment by jmcollin78** [comment]
Hello @Azimthz ,

If you have overshoot with strong regulation parameter you can switch to the expert mode and have a more stronger regulation. There is some in example in the README and in the issues or conversation.
Generally it solves the issue.
See here: https://github.com/jmcollin78/versatile_thermostat/blob/main/README.md#expert-mode-settings

I propose you set the parameters as follows:
```
versatile_thermostat:
     auto_regulation_expert:
         kp: 0.6
         ki: 0.1
         k_ext: 0.0
         offset_max: 10
         stabilization_threshold: 0.1
         accumulated_error_threshold: 70
```

Don't forget to use the 'expert' level of regulation and to uncheck the 'use internal device temperature' which is not recommanded with strong regulation.

Let me know if it fixes your regulation issue.
