### ISSUE TITLE
Déclenchement du chauffage malgré maison absente

### ISSUE THREAD

**Issue by gael1980** [jmcollin78/versatile_thermostat#70]
Bonjour,

Encore bravo pour ce thermostat que j'utilise depuis un peu plus d'un mois.

J'ai remarqué ce jour que le chauffage s'allume de temps en temps alors que la maison est "vide".

Sur le graphique vous pouvez voir que le thermostat a capté deux passages de mes chats :-) pendant mon absence.
Le preset de mon thermostat était réglé en mode  "activité" le temps de mon absence.

On dirait le thermostat garde la consigne de 18° qui correspond à la température confort du thermostat lorsqu'il ne détecte pas de mouvement. Il repasse naturellement à 19° lors des passages des chats, puis revient à 18°. 
Il ne passe jamais à 16° (réglage éco du thermostat), alors que d'autres thermostats qui n'ont pas la fonction "mouvement" de configurée repassent bien à 16°.

Est-ce que le mode "activité" est prioritaire sur le mode absent de la maison ? 
Si oui, je pense que cela devrait être le contraire. La maison doit être forcée en "eco" lorsqu'il n'y a personne dans la maison. 
Dois-je faire un automatisme qui repasse les thermostat en de "activité" à "eco" le temps de l'absence ?

Merci pour votre aide.

Gaël

## Configuration

Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Interface utilisateur : 20230309.1 - latest

Version 3.1.1 de Versatile Thermostat

<img width="1063" alt="Capture d’écran 2023-03-28 à 20 20 51" src="https://user-images.githubusercontent.com/35664315/228335612-90952b92-412d-4c3a-a78b-109855bcce5a.png">

**Comment by jmcollin78** [comment]
Hello @gael1980 ,

Ton cas est intéressant. Je viens de regarder car j'avais un doute et en fait il n'y a pas de pré-pondérance mais juste une réaction en fonction de l'ordre des evènements.

Tu es mode Activité, quelqu'un est détecté -> ca passe en Boost (disons que c'est configuré comme ça)
Plus personne n'est détecté -> ca passe en Confort (disons)
Absence -> Ca passe en Eco et ça mémorise l'état.
Fin d'absence -> Ca remet l'état mémorisé.

Donc en fonction de l'ordre des events on peut avoir des résultats différents. Exemple:
Qq'1 -> Boost,
Absence -> Eco
Fin de mouvement -> Confort


Dans tes courbes on voit l'ordre suivant:
Absence (16h25)-> Eco ( mais il doit y avoir du mouvement car on ne le voit pas passer à 16),
Fin de Motion 16h35 -> 18,
Motion 17h10 -> 19,
Fin de motion 17h20 -> 18.

Il faudrait avoir un event absence pour remettre 16 mais c'est pas comme ça que fonctionne le mode Activité.

Ce que je pourrais faire, c'est en fin d'activité, remettre le preset absence si presence est false. Ca me parait pas mal. Je vais regarder ça.

**Comment by gael1980** [comment]
Merci pour ta réponse.

Pour l’instant, j’ai fait un automatisme qui lorsqu’il n’y a personne à la maison, force le passage de mes 3 thermostats qui sont en mode « activité » (les autres passe bien en temps éco) vers le mode éco, je désactive les schedulers associer à ces thermostats. Comme ça, une fois que quelqu’un rentre dans la maison, j’ai une autre routine qui réactive les schedulers, comme ça le thermostat se remet automatiquement dans le bon mode.
 
Bon week-end

Gaël

**Comment by jmcollin78** [comment]
C'est toujours dommage de faire des automatisations par dessus alors que le 1er but du VTherm c'était justement d'éviter les automatisations.
Je fais pouvoir y faire qqe-chose (pas trop eu le temps hier) donc je tiens au courant quand ce sera fait.
En gros ce serait, quand plus de mouvements, je mets le preset 'Away' si absent sinon le preset programmé dans la conf du mouvement. Ca va intéresser des personnes.

Chez moi, si pas de mouvement, je mets Eco qui est le même preset qu'en cas d'absence, mais tout le monde ne fait pas ça.

**Comment by jmcollin78** [comment]
C'est fixé en 3.2.0 release.
En cas de changement du capteur motion, je change le preset en tenant compte de la présence ou pas.
Ca devrait résoudre ton problème.

Merci pour le signalement !

**Comment by gael1980** [comment]
Merci beaucoup, je vais tester demain.

Gaël
