### ISSUE TITLE
Cannot change temperature - TRV and valve regulation

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#700]
Yes - even when setting the temp in VTherm

The Pi Heating Demand measured on Danfoss TRV never comes up, even if Tdiff between ref and actual temp is more than 1 degrees

![image](https://github.com/user-attachments/assets/259ed7d1-030e-4646-94f9-b80f8d36685b)

This used to work

_Originally posted by @jkbkster in https://github.com/jmcollin78/versatile_thermostat/issues/696#issuecomment-2532565686_

**Comment by jmcollin78** [comment]
@jdeksup please give me your attributes (Development Tools / States).

**Comment by jmcollin78** [comment]
@jdeksup it is here !

Please give me your attributes and your regulation curves like explain here: https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/additions.md#regulation-curves-with-plotly-to-fine-tune-your-thermostat

and the attributes are described here: https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/reference.md#custom-attributes

**Comment by jkbkster** [comment]
Trying to make PlotLy work .. struggling with it.

Attrib:
hvac_modes: off, heat
min_temp: 17
max_temp: 25
target_temp_step: 0.1
preset_modes: none, frost, eco, comfort, boost
current_temperature: 18.4
temperature: 20
hvac_action: heating
preset_mode: eco
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 17
eco_temp: 20
boost_temp: 17
comfort_temp: 22
frost_away_temp: 17
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 3.1
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 20
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-12-11T12:56:36.849392+01:00
last_ext_temperature_datetime: 2024-12-11T12:31:27.925595+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: 2024-12-11T14:05:22.230801+01:00
timezone: Europe/Copenhagen
temperature_unit: °C
is_device_active: true
nb_device_actives: 1
ema_temp: 18.34
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.danfoss_etrv0100_termostat
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
auto_start_stop_last_switch_date: null
follow_underlying_temp_change: false
friendly_name: Elisa Versatile Thermostat6.8.2
supported_features: 401

**Comment by jkbkster** [comment]
![image](https://github.com/user-attachments/assets/26bc2a08-2282-4054-89c0-acaa05800073)

**Comment by jmcollin78** [comment]
Y a un soucis sur les courbes. La consigne est en général très régulière (longue ligne droite) et la T° essaye de s'en rapprocher. Ca doit ressembler à ça : https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/fr/additions.md#courbes-de-r%C3%A9gulattion-avec-plotly

**Comment by jmcollin78** [comment]
Hello,

yes this is the right curve and it is very bad. There is no power_percent (or always 0). When looking at your attributes, you don't have activated the valve_regulation:
```
have_valve_regulation: false
```

So the title of this issue lisled me: "TRV and valve regulation".

So we will have to start from the begining 😮‍💨 

If your VTherm don't reach the target temperature in `over_climate`, just active one self-regulation method.
If you have a TRV and your valve is directly controlable in HA (with a `number` entity) you should try to activate the valve regulation.
else just activate the self reguation as explained here: https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/self-regulation.md

**Comment by jkbkster** [comment]
I've tried all settings.
Today at 1300 I set light, and then a moment later Medium.

It doesn't change the actual heating demand of the TRV - it is not being requested to open. 

I can see the TRV receives the new values, when self regulation is changed.

![image](https://github.com/user-attachments/assets/6e42acec-baec-4aaa-8b96-0e1702ba5f6b)
![image](https://github.com/user-attachments/assets/7c6048d9-5ee9-40cf-b080-4bc1afb9688f)

I've got versatile configured in 8 rooms, and this is the room where I am struggling the most to make it work.

**Comment by jmcollin78** [comment]
Hello @jkbkster 

<img width="533" alt="Capture d’écran 2024-12-15 à 22 24 20" src="https://github.com/user-attachments/assets/5d096e00-c794-44d4-8a09-91de40398367" />

This is great regulation curve but the room temperature is under. Just set the self-regulation to strong. If it is still not enough set the self-regulation to expert with the values explained in README : https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/self-regulation.md#self-regulation-in-expert-mode

**Comment by jkbkster** [comment]
It is now at strong for some days - but response is too slow. So I guess I have to work with expert. 

Will spend Christmas to see if I can make it work better

![image](https://github.com/user-attachments/assets/896ffe89-c44e-4c01-ad09-17b84beff97f)

**Comment by jmcollin78** [comment]
Hello,

If I try to synthetise your case:
1. you have an `over_climate` VTherm,
2. the underlying is a Danfoss TRV,
3. you don't use the Valve regulation but only the 'Light / Medium / Strong',
4. the room temperature is always below the target temperature and seems to grow up very slowly,
5. the internal temp of your TRV is increasing but not the room temperature.

If I correctly understand your case, this is not a matter of self-regulation but just your heater that don't work.
Its internal temperature is increasing but not the room temperature. This should not be possible. Your TRV is broken or something like that.

You can replace it with a Sonoff TRVZB which is now directly supported by VTherm with the valve regulation. This is the best regulation mode you can have.

I will close this issue which is not related to VTherm now. You can continue to discuss here if you need more explaination
