### ISSUE TITLE
Service check shredding

### ISSUE THREAD

**Issue by adi90x** [jmcollin78/versatile_thermostat#71]
Hello,

Whenever I start/stop something that consume a lot of power ( Water heater) I would like to check power shredding or at least restart a new cycle to make sure I am not over consumming  ?

Not sure if it make sense for you ?

Regards,
Adrien

**Comment by jmcollin78** [comment]
Hello, @dominig et @adi90x ,

Je vais prendre la demande qui me parait généralisable à pas mal de contextes.
Je vais publier les sensors complémentaires demandés par @dominig:
- l'énergie demandée à l'instant T. : je l'ai déjà,
- l'énergie max demandable (tous les radiateurs actifs dans un groupe) : facile à faire,
- l'énergie min utile (1 radiateur actif dans un groupe) : je l'ai déjà,
- le delta entre la consigne et la température de la pièce en ° Kelvin :-) :  je l'ai déjà sous la forme de 2 sensors dans l'unité de Home Assistant,

et j'ajoute un service qui permet de :
1. forcer un check d'overpowering,
2. ou de forcer le mode overpowering,
3. ou de stopper le mode overpowering.

Ca permettrait une régulation par une unité externe.

**Comment by adi90x** [comment]
Hello,

Ça me semble être une très bonne idée, concernant la conso des radiateurs lorsqu'il y en a plusieurs de géré, est ce qu'il ne serait pas possible de préciser la conso de chacun ? Ex potentiellement avoir un petit radiateur qui tourne même si la somme de tout les radiateurs est supérieur au max ?

Bonne soirée et bonne fêtes de pâques !

**Comment by jmcollin78** [comment]
Désolé @adi90x pour le délai. Est-ce que tu penses que c'est toujours d'actualité ?
Je vais m'y remettre.

**Comment by adi90x** [comment]
Hello, 

Je réouvre :)  
Avec le froid qui revient je me relance dans les thermostats !

Je pense qu'un service permettant de forcer l'overpowering et surtout de forcer un check peut être très pratique pour s'assurer de ne pas disjoncter. Une autre solution ( encore plus adapté à mon use-case , serait de pouvoir passer la valeur de consommation à un service pour que celui ci l'intégre.

Ex : Mon ballon fait 2kw : 

Cas 1 ) Service check overpowering :  j'allumer mon ballon, ma conso augmente de 2k, je force un check overpowering et il arrete certains chauffages, avec le risque de disjoncter à l'allumage du ballon

Cas 2 ) Je passe ma valeur de 2kw à vtherm lors de l'appel de mon service, celui ci fait son check overpowering , en ajoutant ce 2kw à la conso live, il coupe alor les radiateurs et mon ballon se lance en étant sur de ne pas disjoncter.

D'ailleurs ces deux cas peuvent être géré avec le meme service ( en passant par défault 0 au service de check overpowering ) 

Qu'en penses tu ? 

Bonne fin de week-end !

**Comment by jmcollin78** [comment]
Je comprends l'idée mais je vois 2 soucis :
1.  Cas1 : lorsque le chauffe-eau s'allume, je suppose qu'il y a un délai pour sa conso apparaisse dans la conso globale de la maison,
2. Cas 2 : les 2kw que tu passerais ils vont finir par être dans la mesure de conso globale. Donc si j'ajoute 2kw à la conso globale, je vais me retrouver avec 2kw de trop. Comment je fais pour ne plus prendre en compte les 2kw que tu m'as passé en paramètre ? Si j'attends la prochaine remontée de mesure rien ne me dit que les 2kw sont déjà dedans ou pas.

Tout ça c'est pas simple en fait. Donc pour moi, le mieux, c'est d'attendre la remontée de la conso suivante qui va bien finir par prendre en compte les 2kw et de réagir à ce moment là.
-> c'est ce qui est fait.

Provoquer un check overpowering via un appel de service, ne sert à rien tant que la mesure globale n'est pas à jour et dès qu'elle est à jour, je déclenche le check overpowering. Donc difficile de faire mieux.

**Comment by adi90x** [comment]
En utilisant Lixee, la remonté est de quelques secondes ( je crois 7 secondes par défault ) d'ou l'utilité de pouvoir forcer le check avant la fin du cycle "classique" qui est d'environ 10min sur mes radiateurs ...
Pour le cas 2, je pensais passer le 2kw uniquement lors de ce forcage, donc cela permet de laisser un cycle entier, si au cycle suivant mon ballon a bien était allumé alors j'ai la bonne valeur dans mon sensor sinon cela veut dire qu'il n'a pas été allumé. 
L'idée c 'est de pouvoir avoir une "petite fenetre" qui permet de lancer un appareil très consommateur ( ballon d'eau chaude dans mon cas, mais je suppose que cela pourrait aussi être utile si certains lancent la recharge d'un véhicule electrique ) , mon cas 2 était vraiment de se réserver une quantité d'éléctricité pendant un cycle du radiateur.

**Comment by jmcollin78** [comment]
> En utilisant Lixee, la remonté est de quelques secondes ( je crois 7 secondes par défault ) d'ou l'utilité de pouvoir forcer le check avant la fin du cycle "classique" qui est d'environ 10min sur mes radiateurs ...

Le calcul est fait dès qu'une remontée de la conso globale est disponible et pas seulement à chaque cycle.

**Comment by adi90x** [comment]
Ok j'avais en tête que c'etait fait à chaque cycle uniquement.
Du coup, question inverse : avec un capteur updaté toute les quelques secondes, est ce qu'on ne risque pas d'avoir un check trop souvent ? ( Admettons 4/5 vtherm, chacun vérifiant toute les quelques secondes , il n'y a pas de risque qu'ils se mettent "en boucle"  de check ? )

**Comment by jmcollin78** [comment]
Ca check souvent mais ca ne fait pas de boucle non. Et le check est rapide: on compare 2 nombres en fait.

Pour moi pas de risque. J'ai 10 Vtherm chez moi et une remontée toutes les 10 sec je crois. J'ai pas spécialement constaté de problème de perfs.

**Comment by adi90x** [comment]
Ok top ! En effet, en mettant un max un peu plus faible que la réalité on devrait pouvoir s'assurer de ne pas avoir de probleme !

**Comment by jmcollin78** [comment]
Voilà faut toujours garder une marge de manoeuvre
