### ISSUE TITLE
Syncronise the setpoints between TRV and VTherm

### ISSUE THREAD

**Issue by Riot2891** [jmcollin78/versatile_thermostat#710]
It would be fantastic iif there was a way to syncronise the setpoit of the trv climate entity with the setpoint of the VTherm climate entity. This way you could change VTherm's setpoint directly at the trv, no need to open home assistant. My wife tries this at our Sonoff TRVZB all the time and is quite confused about the fact that this is not possible. ;-)
Keep up the great work, all the Best
Max

**Comment by jmcollin78** [comment]
Hello @Riot2891 ,

Yes it would be wonderful.... And the fun fact is that it exists : https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/over-climate.md#follow-underlying-temperature-changes

**Comment by jmcollin78** [comment]
Please close the issue if this solves your case.

**Comment by Riot2891** [comment]
Hello jmcollin78, 
thanks for your fast reply, thats great news. I will read the changelog thoroughly the next time.
