### ISSUE TITLE
config_entry is deprecated

### ISSUE THREAD

**Issue by rkerian** [jmcollin78/versatile_thermostat#713]
HA logger throws the following error:

"Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 3:28:25 PM (1 occurrences)
Last logged: 3:28:25 PM

Detected that custom integration 'versatile_thermostat' sets option flow config_entry explicitly, which is deprecated at custom_components/versatile_thermostat/config_flow.py, line 934: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/jmcollin78/versatile_thermostat/issues"

VTherm version: 6.8.3

My VTherm attributes are the following:
hvac_modes: heat, off
min_temp: 0
max_temp: 120
target_temp_step: 0.1
current_temperature: 66
temperature: 63
hvac_action: idle
friendly_name: Master Bath Thermostat 1
supported_features: 401
is_on: true
hvac_mode: heat
preset_mode: eco
type: null
is_controlled_by_central_mode: true
last_central_mode: Auto
frost_temp: 45
eco_temp: 63
boost_temp: 45
comfort_temp: 71
frost_away_temp: 45
eco_away_temp: 45
boost_away_temp: 45
comfort_away_temp: 45
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 52.4
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 63
saved_hvac_mode: heat
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-12-16T15:23:04.707889-05:00
last_ext_temperature_datetime: 2024-12-16T15:23:04.712759-05:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: 0
total_energy: 14.55
last_update_datetime: 2024-12-16T15:23:17.377296-05:00
timezone: America/New_York
temperature_unit: °F
is_device_active: false
nb_device_actives: 0
ema_temp: 65.6
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_entities: switch.heater_power_switch
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 2700
cycle_min: 45
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
calculated_on_percent: 0
preset_modes: none, frost, eco, comfort, boost

I read the documentation on the README.md file and I don't find any relevant information about this issue.

**Comment by jmcollin78** [comment]
Hello,

yes it is on the way. Thank you for report.

**Comment by jmcollin78** [comment]
See explainations here: https://developers.home-assistant.io/blog/2024/11/12/options-flow

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.8.4
