### ISSUE TITLE
Question: what kind of thermostat card to use best?

### ISSUE THREAD

**Issue by MartinGoX** [jmcollin78/versatile_thermostat#719]
Hello.
I've just started to use your Vtherm integration as it sounds to be perfectly working together with a Sonoff TRVZB which I'm using. Thanks a lot for your work and time spent on it!

My rough configuration is as follows:
- TRVZB
- indoor and outdoor thermostate entities configured
- standard 'Thermostate' card used with the TRVZB climate entity
This card shows 2 temperatures: the set and current temperatures - but both coming from the TRVZB.

And in my case the current temperature (the one measured directly at the TRVZB) is -obviously- higher than the temperature of the more far away indoor thermostate.
Now my question: Is there a way (or thermostate card) to show the indoor measured temperature instaed of the temperature of the TRVZB?

Or do I miss something or understood something wrong?

Kind regards, Martin

**Comment by tbrasser** [comment]
Use the vtherm climate for the card/control. Also when using trvzb you should be able to have the underlying(s) and vtherm "in sync"

**Comment by MartinGoX** [comment]
> Use the vtherm climate for the card/control. Also when using trvzb you should be able to have the underlying(s) and vtherm "in sync"

Ahh, too easy. I wasn't aware of the additional climate entity... Thanks, that is working now

**Comment by sleveille4** [comment]
i use 2 different cards.

the vtherm one for settings pages where i tinker or go for mainetance etc... because it ha a lot of usefull info & features

the simpler mushroom one in the main dashboard, should i need a quick adjustment
