### ISSUE TITLE
Delta t is 2 < 10 which should be not possible

### ISSUE THREAD

**Issue by Sonic62** [jmcollin78/versatile_thermostat#72]
Hello

Je n'arrive pas à comprendre cette avertissement dans mon journal de HA 

![Capture d’écran 2023-04-08 224836](https://user-images.githubusercontent.com/103725660/230742011-baca7707-6129-4222-9a62-8d7fa7b2662c.png)

`Delta t is 2 < 10 which should be not possible. We don't consider this value
`

![Capture d’écran 2023-04-08 224939](https://user-images.githubusercontent.com/103725660/230742038-d8e1e1fd-f9df-4df4-85fc-dc6dced55f49.png)

Mauvaise config de mon coté ? ou normal ?

Merci

**Comment by jmcollin78** [comment]
Bonjour @Sonic62 ,

Non ce n'est pas une mauvaise config, c'est le thermomètre qui envoie des valeurs à qqes secondes d'interval (2 typiquement). Pour calculer la pente de la courbe de température, si le thermomètre envoi des valeurs trop rapprochées, le moindre petit écart de T° va faire une grosse pente. Pour éviter, ça je ne conserve les mesures que température que si elles sont espacées d'au moins 10 sec.

1 < 10 veut dire 2 mesures de T° a une seconde d'interval.

J'ai déjà eu quelqu'un qui se plaignait de ce message et qui a constaté que son thermomètre (un Sonoff SNZB-02) envoyait des mesures nommées last_seen. C'est la même mesure envoyée a des instants différents et avec une date de mesure identique. Donc il avait des 0 < 10 tout le temps.

Bref, ca vient du thermometre, rien de grave et je vais enlever ce message un peu perturbant pour le mettre en debug uniquement dans une prochaine version.

**Comment by Sonic62** [comment]
Hello

Ok , pas de souci c'etais juste pour savoir si j'avais pas fait une connerie dans ma config... :-)
