### ISSUE TITLE
Follow underlying temp change (auto refresh)

### ISSUE THREAD

**Issue by chris-issy** [jmcollin78/versatile_thermostat#720]
Hello,

I'm wondering if it could be available to refresh the setpoint of the TRV from the VTherm automaticaly. 

For now my workaround is to act with an automation on the VTherm so it will update the TRV with underlyinge "up to date" change.

For some reason the radiator's vincinity is definitely unstable and this auto refresh would be a charm !

Thanks

**Comment by jmcollin78** [comment]
Hello,

That is already the case. See here: https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/over-climate.md#follow-underlying-temperature-changes

**Comment by chris-issy** [comment]
It is done only at setting time of the setpoint. In order to have it refreshed, sonsidering that the offset is constantly moving, the only workaround to have the underlying temperature correctly followed is to either change +0.5 then -0.5 the VTherm or switch from Confort to Boost and rollback with an automation.

Is it more precise this way ?

**Comment by chris-issy** [comment]
sample automation YAML workaround :

alias: Refresh VTherm ETAGE
description: ""
triggers:
  - trigger: time_pattern
    minutes: /10
conditions:
  - condition: device
    device_id: XXXXX
    domain: climate
    entity_id: YYYY
    type: is_preset_mode
    preset_mode: comfort
actions:
  - sequence:
      - action: climate.set_preset_mode
        metadata: {}
        data:
          preset_mode: boost
        target:
          device_id: XXXXX
      - action: climate.set_preset_mode
        metadata: {}
        data:
          preset_mode: comfort
        target:
          device_id: XXXXX
mode: single

**Comment by jmcollin78** [comment]
> It is done only at setting time of the setpoint.

no. If you check the "follow the underlying temp change" each time the target temperature change on the underlying it is copied in the Vtherm. I suggest to give it a try.

**Comment by chuckiebronco** [comment]
Thanks, was wondering why manual override on the device itself had no impact. 
Wouldnt it make sense to be activated by default or to set by a checkbox in the configuration if possible? Behaviour otherwise is irritating imho...

**Comment by jmcollin78** [comment]
it causes many issues so it is deactivated by default. "Why is my Vtherm changing itself...".
So I will keep it false by default.

**Comment by chris-issy** [comment]
> each time the target temperature change on the underlying it is copied in the Vtherm

It is exactly what I'm saying too... 

Meaning that if when setting the target temp to 19 (T) the underlying is 19.5 (U) and real room temperature is 18.5 (R) the target is updated to 20 (UT).
At this time we are fine.
However the room will go to this values : 
(T) 19 (won't change wihtout manual action or schedule/automation)
(U) 20
(R) 18.7
(UT) 20
At this point the heating will stop while the real target is not reached. Acting on target would correctly update UT to 20.3 and then  heat again.

That's why I'm having automation to move preset every 10 minutes and rollback so I can ave the underlying target relfected correctly with underlying unstable temperature behaviors.

Hopefuly now it's a clearer explanation
