### ISSUE TITLE
Humidity Management

### ISSUE THREAD

**Issue by adi90x** [jmcollin78/versatile_thermostat#75]
Hey,

Again thank for your awesome work ! 

I came into a new issue/setup today, would it be possible to add a kind of humidity management ?
For example, whenever humidity sensor is over a threshold, start heating maybe at a given % ( or possibly switch on another switch for example a dehumidifier)
Could also be just a bypass of the window/door sensor ? I.e : for example when humidity over a threshold, apply heating even if windows/doors is open. A bypass service for windows opening can also do the trick !  

Regards, 
Adrien

**Comment by jmcollin78** [comment]
Hello @adi90x ,

It seems useful and easy. I will think about this new feature and come back with some proposals.
Are you developper ? If yes I can help you to make your own PR. I would love not to be alone on this integration.

**Comment by dbartelmus** [comment]
I’m looking forward to this feature. I have good result from Chat GPT resolving humidity dependence between relative indoor and outdoor percentages - overall pretty easy formula

**Comment by jmcollin78** [comment]
> I’m looking forward to this feature. I have good result from Chat GPT resolving humidity dependence between relative indoor and outdoor percentages - overall pretty easy formula

What would it be useful for ?

**Comment by jmcollin78** [comment]
After thinking, I will not implement this because I will be out of scope of a Thermostat. This will make two different code branch with heating or cooling which have no relations.

**Comment by adi90x** [comment]
Hello,
Won't be 2 branch just a trigger, heating on if humidy > xx%, it will just keep heating even if over set temperature
Regards,

**Comment by dbartelmus** [comment]
> > I’m looking forward to this feature. I have good result from Chat GPT resolving humidity dependence between relative indoor and outdoor percentages - overall pretty easy formula
> 
> What would it be useful for ?

Sorry for my delayed respond, so 3 main reason behind it, comfort, health and efficiency.
The main reason we perceive temperature is humidity, so it should be considered. Further more there is also efficiency consideration in this.
