### ISSUE TITLE
Add a PID mode

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#8]
As discussed here a PID mode should be interesting to study: https://forum.hacf.fr/t/smart-thermostat-le-chauffage-controle-par-pid/7633/2

**Comment by kadaan** [comment]
This would be awesome.  I wonder if it would be possible to refactor the PID control from https://github.com/ScratMan/HASmartThermostat into it's own component that could be used by both projects?

**Comment by jmcollin78** [comment]
The important part is here:

PID output value is the weighted sum of the control terms:
error = set_point - current_temperature
di = temperature change between last two samples
dt = time elapsed between last two samples
P = Kp * error
I = last_I + (Ki * error * dt)
D = -(Kd * di) / dt
output = P + I + D
Output is then limited to 0% to 100% range to control the PWM.

**Comment by jmcollin78** [comment]
@kadaan I will try to contact the author and see if it is possible to set something in commons.
But I have many work to do before this and TPI works pretty well.

**Comment by jmcollin78** [comment]
This is not needed. The TPI works well.

**Comment by lucaciraolo** [comment]
@jmcollin78 is it worth revisiting a PID mode now that you guys have started working on auto tuning for TPI mode? From my limited understanding, PID would be better if we can figure out how to tune it correctly
