### ISSUE TITLE
Boost mode

### ISSUE THREAD

**Issue by adi90x** [jmcollin78/versatile_thermostat#83]
Hello,

Not sure how boost mode is supposed to work but it seems that it goes over set temperature and then don't seems to be on 100% of time but something like 80%.
Is it what is expected in boost mode ?

Regards,
Adrien 
![Screenshot_20230513-085717_Home Assistant](https://github.com/jmcollin78/versatile_thermostat/assets/11168372/203f0599-27cc-4622-b946-74463ca95a10)

**Comment by jmcollin78** [comment]
Hello @adi90x ,

There is nothing special with boost mode. Only a different target temperature.

**Comment by adi90x** [comment]
Had an issue on the switch referenced by versatil thermostat so it may explain why it was not working as expected.
Still interested by how boost is supposed to be  ( 100% ) or just a preset like others  ?

**Comment by adi90x** [comment]
> Hello @adi90x ,
> 
> There is nothing special with boost mode. Only a different target temperature.

Thanks a lot for you message !! Closing this issue

**Comment by jmcollin78** [comment]
A preset like other
