### ISSUE TITLE
Fail to read presence detection

### ISSUE THREAD

**Issue by Bergoglio** [jmcollin78/versatile_thermostat#85]
When the thermostat use an entity like person.xxxx, it doesn't change status of presence (always away) but in the same time the entity person.xxx shows that the user is in house (so, entity person.xxx works fine)

If I set to use for presence a binary_sensor like this
`  - binary_sensor:
      - name: "Siamo a casa"
        state: "{{ is_state('group.gruppo_bergoglio_p1','home') }}"`
the thermostat works regularly. Entity group.gruppo_bergoglio_p1 is a goup of person.xxxx

**Comment by jmcollin78** [comment]
Hello @Bergoglio ,

I'm very surprise of this because I always use it myself. The person.xxx should have the value "home" when at home. Can you send me a screen with this entity set to "home" and a corresponding thermostat with presence to off please ? I have to be sure their is really a problem before investigating.

Use the Developper Tools / State to show me the state of the person.xxx and climate.xxx entities.

**Comment by Bergoglio** [comment]
Ok, I described what happens in issue 84.

The screenshots :

![Screenshot 1](https://github.com/jmcollin78/versatile_thermostat/assets/64399503/af9306e1-f0b1-4937-aed3-4b0dcfec796d)

![Screenshot 2](https://github.com/jmcollin78/versatile_thermostat/assets/64399503/cfd17b3b-ce70-4fbf-885b-0d8b6f730429)

![Screenshot 3](https://github.com/jmcollin78/versatile_thermostat/assets/64399503/23aa050b-068e-4c8e-860f-e3c12a6181cb)

![Screenshot 4](https://github.com/jmcollin78/versatile_thermostat/assets/64399503/9b085a8f-1b61-43d3-9984-631fbea85d16)

![Screenshot 5](https://github.com/jmcollin78/versatile_thermostat/assets/64399503/3dd70ce6-ec08-48c2-9194-6d064d191d8b)

**Comment by Bergoglio** [comment]
I made another test on window sensor and now I understand a problem : my sensor is on when the window is closed and off when the window is open (exactly the opposite of what Versatile wants....)
So, no problems on window detection.

**Comment by jmcollin78** [comment]
Ok, I think I've got it. Groups of person don't behave like a single person.

On my interface, it is not possible to create a group of person:
![Capture d’écran 2023-06-08 à 22 38 09](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/34175b5a-4b50-4bc3-97f4-a857ed315a11)

So I guess you have created your group with something like this in the configuration.yaml:
```
group:
  - habitants:
     name: "Groupe des habitants"
     entities:
      - device_tracker.portable_jmc

```

With this definition of group (the only possible on my opinion), it is not possible to add the group as presence detector in the VersatileThermostat configuration:
![Capture d’écran 2023-06-08 à 22 41 56](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/142518ff-f845-4eee-8885-bad638e44a1a)

Only binary_sensors, persons or group of binary sensors are possible in that field.

So I wonder how you manage to configure the group in the VersatileThermostat. Can you show me the "Gestione delle presenze" configuration page for this thermostat ?

On my home, I have done the following. I have a template like this (in template.yaml) :

- binary_sensor:
    - name: maison_occupee
      unique_id: maison_occupee
      state: "{{is_state('person.jmc', 'home') or is_state('person.chr', 'home') or is_state('input_boolean.force_presence', 'on')}}"
      device_class: occupancy

And I put this binary sensor as presence sensor and it is working as expected. So your workaround is the good solution.

**Comment by Bergoglio** [comment]
Pay attention : the presence detection is not working where I set to use only a person.xxx .
Where I set the group presence detection is working good.....

This is working good

![Screenshot 2](https://github.com/jmcollin78/versatile_thermostat/assets/64399503/bbf244cb-2acd-475c-9445-419be58408c0)

"Siamo a casa" is this in configuration.yaml

```
template:
  - binary_sensor:
      - name: "Siamo a casa"
        state: "{{ is_state('group.gruppo_bergoglio_p1','home') }}"
```

and group.gruppo_bergoglio_p1 is this in /config/groups.yaml

```
  gruppo_bergoglio_p1:
    name: Bergoglio P1
    entities:
      - person.cristiano_bergoglio
      - person.cristina_bergoglio
      - person.maria_semenova
```

**Comment by Bergoglio** [comment]
Tomorrow or Saturday I will report You another test that I'm doing, so, please, wait some times.

My test :

I changed manually in Developer Tools / States the binary_sensor.riscaldamento_bagno_nonna_presence_state from off to on 

![Screenshot 3](https://github.com/jmcollin78/versatile_thermostat/assets/64399503/676d8af4-6d36-498c-b41e-76905d303640)

I didn't touch Versatile climate.riscaldamento_bagno_nonna because I saw in Developer Tools / States that presence_state: home is right and opposite of what binary_sensor.riscaldamento_bagno_nonna_presence_state shows....

I will tell You....

**Comment by Bergoglio** [comment]
I cannot understand, binary_sensor.riscaldamento_bagno_nonna_presence_state seems to be completely locked and unlinked to Versatile thermostat (in fact I can see in Developer tools / State that the Versatile thermostat works fine also for presence detection).....

**Comment by Bergoglio** [comment]
Now I have no other tests in my mind.....

**Comment by Bergoglio** [comment]
I close this issue because Versatile is working good for presence detection, it the sensor entity (binary_sensor.XXX_presence_state that is wrong.
