### ISSUE TITLE
Where to find the grafic interface code?

### ISSUE THREAD

**Issue by Bergoglio** [jmcollin78/versatile_thermostat#87]
I am aware this might not be the correct way of asking a clarification, but I didn't know how else to reach you.
I would like to know where the code to the grafic interface is located, if there is code provided for the viewing at all. More specifically the pages that pop-up when configuring a new thermostat. I would also like to know if it is possible to apply some changes to them to fit new funcionalities. 
Thank you for your time.

**Comment by jmcollin78** [comment]
Hello, i'm available on discord. My pseudo is : jm.collin

**Comment by Bergoglio** [comment]
Hi,
we are sorry but my daughter was full of works in these days (yesterday she reached a degree in python data analist).
We will start to work on Versatile soon.
We thought on some ideas only in general.
