### ISSUE TITLE
Contact for developing

### ISSUE THREAD

**Issue by Bergoglio** [jmcollin78/versatile_thermostat#88]
Hi, my daughter is trying to develop on the code of Versatile, but she has a lot of problems to understand guidelines and she needs to be more in contact with You and other developers. How can she contact You ?

**Comment by jmcollin78** [comment]
See on Discord jm.collin

**Comment by Bergoglio** [comment]
Hi,
we are sorry but my daughter was full of works in these days (yesterday she reached a degree in python data analist).
We will start to work on Versatile soon.
We thought on some ideas only in general.
