### ISSUE TITLE
Add the Absence mode

### ISSUE THREAD

**Issue by Merangle** [jmcollin78/versatile_thermostat#93]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
As far as I understand, you have implemented the three modes : Eco, Confort, Boost. 
Eco is used to lower the heat temperature by a few degrees when you are away for a short periode of time. 

Dou you plan to implement the 'absence' mode with a low temperature (e.g 7°C) to avoid freezing in the room ? 
Many thanks for your work. 

**Describe alternatives you've considered**
We could also lower the eco temperature when it's less meaningful.

**Additional context**

**Comment by salaun29** [comment]
Activating the AWAY and SLEEP presets would be perfect !

**Comment by jmcollin78** [comment]
@salaun29 , The way it is working with Versatile Thermostat (VTherm) is not exactly this one. Instead of having multiple Preset, the VTherm is defining the preset temperature when someone is present and when nobody are present.
You should configure the "presence management" to use this feature. Then the thermostat will switch itself to away temperatures when everybody leaves.

Many people will want to have specific presets: sleep, anti-freezing, ... I don't want to implement all specific needs to keep it simple and easy to use and configure.

@Merangle this does not answer to the "anti freezing" mode which is not implemented because not very usefull (my opinion). The objective of VTherm is to be automatic: you configure a VTherm and a Scheduler to switch presets and . For anti-freezing I'm not able to et an event to switch automatically to this preset. This is always possible to force the VTherm using the services which can set the preset to "manual" and set the temperature you need. Let me know, if you agree with that.
If many people asks for it I will review my opinion.

**Comment by Merangle** [comment]
I already managed my electrical heaters with automations, TPI and Google calendar to switch from Eco to comfort and back. 
Your solution seems to be much more cleaner than mine with additional options (presence management, windows open without windows sensor, ...) I'm interested. 

I do not use the climate entities in HA.
The target temperature is set when I switch to Eco or Comfort. and in my TPI automations,   I use this target temperature.

When I select the Away mode I set the target temperature to the Away temperature. 
In the calendar automation, I do not modify the target temperature if the Away mode is set. 

I never modify the target temperature of each mode.
When I come back from holidays, I just disarm the Away mode and the Calendar automation continues switching to Eco or Comfort temperature according to the calendar.

I understand that your proposal is to modify the target temperature of Eco and Comfort to the Away temperature.
With this proposal I have to modify 7 heaters * 2 target temperature * 2 (when leaving and coming back). 
Do I understand right ? 
 
The anti-freezing  is usefull during holidays or travel to lower the temperature to a constant one. Otherwise you have to modify both Eco and Comfort. 

Happy to shaer with you. 
And thanks for the work. It's great.

**Comment by jmcollin78** [comment]
> I understand that your proposal is to modify the target temperature of Eco and Comfort to the Away temperature.
With this proposal I have to modify 7 heaters * 2 target temperature * 2 (when leaving and coming back).
Do I understand right ?

Yes. At initial configuration of each Versatile Thermostat (one per room), you set the temperature for each preset when present and when absent. So if you have 7 thermostats (7 heater), you have to configure one time : 7 x 3 (presets: eco, comfort, boost) x 2 (away, present) temperature.
And then you never have to modify it again.

> The anti-freezing is usefull during holidays or travel to lower the temperature to a constant one

yes

> Otherwise you have to modify both Eco and Comfort.

Not mandatory. You have a Manual preset in which you set manually the temperature. I propose to use this manual operation for anti-freezing which should be rare. I limit the number of presets to keep it simple. All other cases than eco, comfort and boost can be handled with the manual mode. That is my proposal.

**Comment by Merangle** [comment]
To make sure I understand some parameters : 
What is the Away temperature ? is it the temperature I have to set in the presence tab in order to slightly decrease the temperature (in Eco, Comfort,Boost) when nobody is at home ? Is it something different ?
Right now, I set Away temperature to Mode temperature minus one degree. 

`I propose to use this manual operation for anti-freezing which should be rare. I limit the number of presets to keep it simple. All other cases than eco, comfort and boost can be handled with the manual mode. That is my proposal.`

Not so rare, if you have to be away for your job or your child are not at home for a long period of time. 
With your proposal, do I have to understand that if I manually modify the target temperature it overrides the target temperature set previously by the mode you have selected before ?

Regards


Let's assume I manually lower the target temperature (to 7°C as an exemple). 
And my calendar is still running. 
At the next switch in the calendar (from Comfort-19°C to  Eco-17°C), the ECo mode will be selected.
Wwhat will be the target temperature ? 
7°C the one manually set 
17°C the Eco temperature set by the calendar. 

Does the manually changed temperature override the temperature selected in a mode ?

**Comment by jmcollin78** [comment]
> What is the Away temperature ? 

Away temperatureS are the presets temperature (eco, comfort, boost) when presence management detects that nobody is at home.

> if I manually modify the target temperature it overrides the target temperature set previously by the mode you have selected before ?

Exactly. When changing manually a temperature (that have been set with a preset let say), the VTherm switch to "Manual" and the configured temp overrides the preset temp.

Example:
initial state (in comfort preset temp):
![Capture d’écran 2023-07-31 à 16 58 01](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/ed44b893-b1e9-4cda-96c4-870b6c54c07c)

I change manually the target temperature. Then I've got this (preset change to "None"):
![Capture d’écran 2023-07-31 à 16 58 53](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/8c7f3580-11f3-43b6-b0ea-5a9f3c290960)

> Let's assume I manually lower the target temperature (to 7°C as an exemple).
> And my calendar is still running.
> At the next switch in the calendar (from Comfort-19°C to Eco-17°C), the ECo mode will be selected.
> Wwhat will be the target temperature ?
> 7°C the one manually set
> 17°C the Eco temperature set by the calendar.
> Does the manually changed temperature override the temperature selected in a mode ?

At next switch of the calendar, the thermostat will switch to what the calendar sets -> 17°C (Eco mode in your example).
To avoid this I have done this in my house:
![Capture d’écran 2023-07-31 à 17 02 24](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/c1b8403a-a288-406c-8f9f-df9fbb75e9ef)

I set the select to Automatic to control the Scheduler. When Scheduler seen Automatic it is working else it is in standy (you have condition in Scheduler). I don't know with Google Calendar.

**Comment by jmcollin78** [comment]
What I suggest is to try with a fake switch (or a switch you don't need). It is always more easy to understand when trying than when reading the doc.

**Comment by Merangle** [comment]
Ok thanks I understand now !

I will set a button for the away mode. 
When On the automation will lower the temperature to the away temperature and the calendar will know it must not select a mode 
When Off I will select the eco mode and leave the calendar do what needs to be done. 
 




> What I suggest is to try with a fake switch (or a switch you don't need). It is always more easy to understand when trying than when reading the doc.

Ok thanks
Regards

**Comment by jmcollin78** [comment]
Feel free to ask more question on the Discord jm.collin if necessary.
